google/go-cloud

runtimevar/example_test.go

According to the [context documentation](https://golang.org/pkg/context/#Context):
>        // If Done is not yet closed, Err returns nil.
>        // If Done is closed, Err returns a non-nil error explaining why
So using ctx.Err() seems better than selecting the ctx.Done() channel (easier to read and probably a bit faster)

runtimevar: simplify context usage

---

wire/README.md

This is a small typo I noticed in the wire readme file.

wire: Fix typo in README.md ProvideBaz example.

---

samples/guestbook/gcp/variables.tf

Without an example, the regions-zones page makes it seem like the zone should be something like "a", but that doesn't work. It has to be something like 'us-central1-a', so it should help to show an example of that.

Add examples of regions and zones in variables.tf

---

wire/README.md

A function called initializeApp was returning a foobarbaz.Baz.

Wire: fix typo in README: App -> Baz

---

samples/guestbook/inject_aws.go
samples/guestbook/inject_gcp.go
samples/guestbook/inject_local.go
wire/cmd/wire/main.go

samples/guestbook: replace panic(wire.Build(...)) with wire.Build(...), return

---

blob/gcsblob/gcsblob_integration_test.go
blob/gcsblob/gcsblob_test.go
go.sum
internal/testing/setup/setup.go
runtimevar/runtimeconfigurator/runtimeconfigurator_test.go

This partially addresses issue #214.

all: use -record instead of -short to turn on recording in tests

---

wire/cmd/wire/main.go
wire/internal/wire/analyze.go
wire/internal/wire/parse.go
wire/internal/wire/testdata/UnusedProviders/out.txt
wire/internal/wire/wire.go

Rename ProviderSet.Name to VarName, and ensure it is set when the ProviderSet is a package variable.

---

.gitignore
internal/contributebot/README.md
internal/contributebot/go.mod
internal/contributebot/go.sum
internal/contributebot/main.tf
internal/contributebot/outputs.tf
internal/contributebot/variables.tf
internal/contributebot/webhook/README.md
internal/contributebot/webhook/app.yaml.in
internal/contributebot/webhook/main.go

Includes Terraform configuration for adding the Pub/Sub topic.
Updates #216

internal/contributebot/webhook: add App Engine listener

---

internal/testing/checkpr.sh
internal/testing/wirecheck.sh

The latest sync of vgo from upstream brought in https://golang.org/cl/126655, which changed the syntax of the `go mod` operations.
Fixes #294

internal/testing: use `vgo mod vendor`

---

server/server.go

A RequestLogger does not log HealthChecks. This commit documents that
fact.
Fixes #155.

server: Add note about RequestLogger to server.New docs

---

blob/blob.go

blob: document storing a ctx in blob.Writer

---

blob/blob.go
blob/driver/driver.go
blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go
blob/gcsblob/gcsblob.go
blob/s3blob/s3blob.go

At [Sajari](https://github.com/sajari) we have been doing something similar to [blob](https://godoc.org/github.com/google/go-cloud/blob) with our own [storage](https://github.com/sajari/storage) pkg for quite some time now.
I started working on [migrating](https://github.com/sajari/storage/pull/5) our [storage](https://github.com/sajari/storage) pkg to use [go-cloud/blob](https://godoc.org/github.com/google/go-cloud/blob) underneath, and noticed that modification time was not a part of the [`driver.ObjectAttrs`](https://github.com/google/go-cloud/blob/master/blob/driver/driver.go#L64) struct. This is something that we use internally and is a part of our [`storage.File`](https://github.com/sajari/storage/blob/master/storage.go#L15) struct. 
This adds ModTime to …

blob: add modification time to driver.ObjectAttrs

---

CONTRIBUTING.md

Please do not merge until everyone has approved.

CONTRIBUTING: add section about squashing

---

runtimevar/runtimevar_test.go

As near as I can tell this just creates a stub implementation and then tests the stub.

runtimevar: remove unnecessary stub test

---

wire/internal/wire/testdata/ValueFromFunctionScope/foo/foo.go
wire/internal/wire/testdata/ValueFromFunctionScope/foo/wire.go
wire/internal/wire/testdata/ValueFromFunctionScope/pkg
wire/internal/wire/testdata/ValueFromFunctionScope/want/wire_errs.txt
wire/internal/wire/wire.go

wire: check that wire.Value values are from package scope

---

runtimevar/drivertest/drivertest.go
runtimevar/filevar/filevar.go

I wasn't able to repro the flake, but this is definitely a bug. I also added more info on the test failure message which may prove helpful if it flakes again.

runtimevar/filevar: return ctx.Err() instead of nil error when ctx is Done

---

AUTHORS

"The Go Cloud Authors" are the ones specified by this list, so the existing entry was self-referencing. While the paradox might be an interesting way to keep away robot lawyers, the copyright owner for the Googlers contributions is Google LLC.

AUTHORS: fix Google LLC entry

---

internal/contributebot/main.go
internal/contributebot/process.go
internal/contributebot/process_test.go

Instead of comparing the repo name.

internal/contributebot: check whether a PR is from a fork directly

---

tests/gcp/app/cloudbuild.yaml
tests/gcp/test.sh

tests: build GCP test app using go 1.11 instead of vgo

---

blob/blob.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/attrs.go
blob/fileblob/fileblob.go
blob/gcsblob/gcsblob.go
blob/gcsblob/testdata/TestConformance/TestMetadata/empty.yaml
blob/gcsblob/testdata/TestConformance/TestMetadata/valid_metadata.yaml
blob/gcsblob/testdata/TestConformance/TestMetadata/valid_metadata_with_empty_body.yaml
blob/s3blob/s3blob.go
blob/s3blob/testdata/TestConformance/TestMetadata/empty.yaml
blob/s3blob/testdata/TestConformance/TestMetadata/valid_metadata.yaml
blob/s3blob/testdata/TestConformance/TestMetadata/valid_metadata_with_empty_body.yaml

Fixes #324.
The most controversial thing in this PR is force-lowercasing the Metadata keys during reading and writing. Provider behavior is inconsistent on this. I think both S3 and GCS store keys case-sensitive, but GCS claims it is case-insensitive 
- GCP claims to be case-insensitive (search for "Field names are case-insensitive" [here](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata)). However, the backend is actually case-sensitive. The JSON and XML-based APIs handle casing, but the HTTP one does not. Further discussion [here](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1132).
- S3 claims to store them in lowercase (search for "user-defined metadata keys in lowercase" [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata …

blob: Add support for key/value Metadata

---

wire/README.md

I read README to study wire command. and I had a feeling of strangeness in this sample.
`injectReader` returns `io.Reader`,  and `wire.Build` argument indicates `io.Reader`. Therefore, I think return value does not need `Foo{}`. 
```go
func injectReader() io.Reader {
wire.Build(wire.InterfaceValue(new(io.Reader), os.Stdin))
return Foo{}
}
```
I would appreciate it if you could check this PR.

wire: Fix sample code in README of wire

---

blob/blob.go
blob/drivertest/drivertest.go
blob/gcsblob/testdata/TestConformance/TestMetadata/valid_metadata_with_content_type.yaml
blob/s3blob/testdata/TestConformance/TestMetadata/valid_metadata_with_content_type.yaml

I missed that if ContentType is specified, `blob.NewWriter` was returning early; the code to set the metadata field in `driver.WriterOptions` was after the early return, so it wasn't be set correctly. This just moves the metadata code block earlier, and adds a testcase. The testcase failed before the fix.

blob: fix setting of metadata when ContentType is specified

---

health/health.go

This patch adds a small function to write out the HTTP headers in the health check handlers since they're more or less the same.

health: factor out code to write HTTP headers

---

blob/drivertest/drivertest.go

blob/tests: don't fail test if Reader returns n > 0 and io.EOF

---

CONTRIBUTING.md

Clarify the Go Cloud *team* can generate replay files, not Go Cloud itself.

CONTRIBUTING: Small doc nit

---

wire/README.md

wire: fix typo in example code

---

blob/drivertest/drivertest.go
blob/fileblob/fileblob_test.go
blob/gcsblob/gcsblob_test.go
blob/s3blob/s3blob_test.go

This change just changes the `drivertest.Harness` interface to have a `MakeDriver` instead of `MakeBucket`. All of the tests still use the driver.Interface to immediately create a `*blob.Bucket`, so they are unchanged. In most cases, I think testing using the concrete type is fine; it allows for testing of the concrete type functionality as well, and provides a better end-to-end test. However, this change opens the door for more direct testing of the driver interface as well.

blob/tests: modify drivertest harness to use a driver.Bucket, not a *blob.Bucket

---

wire/internal/wire/analyze.go
wire/internal/wire/testdata/MultipleBindings/want/wire_errs.txt
wire/internal/wire/testdata/MultipleMissingInputs/want/wire_errs.txt

wire: use multiline instead of one single line for errors with traces

---

blob/blob.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/gcsblob/gcsblob.go
blob/s3blob/s3blob.go

Given that we don't think there's a major performance cost to retrieving extra blob attributes, and that the concrete type interface is an iterator, there's no need to expose the page size.
This PR removes this option from the concrete type.
The driver interface is still paged, so `PageSize` is still exposed on the driver's `ListOptions`. It is only used in tests. I think it's reasonable to have the driver expose a paged interface still; otherwise, each driver would need to implement an iterator over what is likely a paged/bulk interface to the backend.
Fixes #564.

blob: remove ListOptions.PageSize

---

runtimevar/example_test.go
runtimevar/filevar/example_test.go
runtimevar/filevar/filevar.go
samples/guestbook/inject_local.go
samples/guestbook/wire_gen.go

For consistency with `etcdvar` and `constantvar`.
`filevar.NewVariable` stutters; `filevar.New` is better.
I left `NewVariable` for `runtimeconfigurator` and `paramstore` because for those packages, it is not a top-level function, but rather a method of `Client`.

runtimevar/filevar: rename NewVariable -> New

---

blob/blob.go
blob/drivertest/drivertest.go
blob/example_test.go

BREAKING CHANGE
ListIterator.Next now returns (nil, io.EOF) at the end
of the iteration.
Fixes part of #565.
The other part is looping when ListPaged returns zero elements, to
be addressed in another PR.

blob: iterator returns io.EOF

---

blob/blob_test.go

Check that the ListIterator.Next implementation can handle
a driver that returns empty pages.

blob: add a test for empty pages

---

blob/example_test.go
blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go
blob/s3blob/s3blob.go
samples/guestbook/inject_aws.go
samples/guestbook/inject_local.go
samples/guestbook/wire_gen.go
samples/tutorial/setup.go

This is questionable -- why add an empty `Options` struct? But I think it's wise to do so, because otherwise if we ever want to add options (which seems quite likely at least for `s3blob`), we'll end up with either multiple constructors (`OpenBucketWithOptions`), or a breaking change.
I could be convinced that we'll never add options to `fileblob` so we should leave it off there.
I also re-ordered the arguments to `s3blob.OpenBucket` to be consistent with `gcsblob`.
There are some unrelated changes to `wire_gen.go` because I re-reran `go generate`.
Fixes #592.

blob: add empty options to fileblob and s3blob, for future extensibility

---

wire/cmd/wire/main.go
wire/internal/wire/parse.go
wire/internal/wire/testdata/BuildTagsRelativePkg/pkg
wire/internal/wire/testdata/Cycle/want/wire_errs.txt
wire/internal/wire/testdata/EmptyVar/want/wire_errs.txt
wire/internal/wire/testdata/InjectInputConflict/want/wire_errs.txt
wire/internal/wire/testdata/InjectorMissingCleanup/want/wire_errs.txt
wire/internal/wire/testdata/InjectorMissingError/want/wire_errs.txt
wire/internal/wire/testdata/InterfaceBindingDoesntImplement/want/wire_errs.txt
wire/internal/wire/testdata/InterfaceBindingInvalidArg0/want/wire_errs.txt
wire/internal/wire/testdata/InterfaceBindingNotEnoughArgs/want/wire_errs.txt
wire/internal/wire/testdata/InterfaceValueDoesntImplement/want/wire_errs.txt
wire/internal/wire/testdata/InterfaceValueInvalidArg0/want/wire_errs.txt
wire/internal/wire/testdata/InterfaceValueNotEnoughArgs/want/wire_errs.txt
wire/internal/wire/testdata/MultipleBindings/want/wire_errs.txt
wire/internal/wire/testdata/MultipleMissingInputs/want/wire_errs.txt
wire/internal/wire/testdata/NoImplicitInterface/want/wire_errs.txt
wire/internal/wire/testdata/UnexportedStruct/want/wire_errs.txt
wire/internal/wire/testdata/UnexportedValue/want/wire_errs.txt
wire/internal/wire/testdata/UnusedProviders/want/wire_errs.txt
wire/internal/wire/testdata/ValueFromFunctionScope/want/wire_errs.txt
wire/internal/wire/testdata/ValueIsInterfaceValue/want/wire_errs.txt
wire/internal/wire/wire.go
wire/internal/wire/wire_test.go

The primary motivation is to permit a move to using `go/packages` instead of `go/loader`. `go/packages` runs exclusively by shelling out to the go tool, which precludes use of the in-memory "magic" GOPATH being used up to this point.
This has a secondary effect of removing a lot of code to support "magic" GOPATH from the test infrastructure. This is on the whole good, but necessitated a change in the error scrubbing: since the filenames are no longer fixed, error scrubbing also must remove the leading `$GOPATH/src` lines.
Another related change: since all callers of `Generate` needed to know the package path in order to write out wire_gen.go (necessitating a find-only import search) and `Generate` already has this information, `Generate` now returns this information to the caller. This …

wire/internal/wire: use on-disk GOPATH in generate tests

---

.travis.yml

Currently breaking; not fully tested.
This reverts commit a06559596e75a37bf1db9d2fcadd18a5cca1ce14.
Re-opens #323

travis: remove Windows build

---

wire/internal/wire/wire_test.go

This does not change the results of the test, but should not be happening. I discovered this as a red herring while debugging #623.

wire: in tests, don't copy wire_gen.go into the temporary GOPATH

---

wire/README.md

This PR makes explicit in the `README` that you must add `$GOPATH/bin` to your `$PATH`, since that differs between `go generate` and other `go` commands.

wire: update README installation instructions 

---

internal/proxy/README.md

Instead of starting from zero, instruct proxy updaters to start from the current module cache by copying from the remote bucket. In common cases, this should reduce the probability of accidental removal of dependencies that other collaborators depend on in in-flight PRs.
There is still the possibility that someone else runs these steps concurrently and clobbers work, but that seems much more remote, and the resolution would be to go through the process again.
Fixes #661

internal/proxy: add step to copy from GCS

---

internal/testing/runchecks.sh

Fixes #625.
The previous code had a bug; doing `exec <cmd> && <cmd2>` never runs `cmd2`. We also only want to do code coverage on the root module.

all: only run coverage for the root module

---

wire/internal/wire/wire_test.go

We are seeing errors of the form "failed to cache compiled Go files" when running the tests on Travis. Hopefully this should reduce or eliminate the flakiness.
Updates #669

wire: serialize test execution

---

wire/internal/wire/testdata/BindInjectorArg/foo/foo.go
wire/internal/wire/testdata/BindInjectorArg/foo/wire.go
wire/internal/wire/testdata/BindInjectorArg/pkg
wire/internal/wire/testdata/BindInjectorArg/want/wire_errs.txt

The test current produces a wire error due to #547. It will be updated to actually work as part of fixing that bug.
Updates #547.

wire/tests: add a test for wire.Bind on an injector arg

---

internal/pubsub/acks_test.go
internal/pubsub/empty_sub_test.go
internal/pubsub/pubsub.go
internal/pubsub/pubsub_test.go

The context is only used for background work. Replaced with context.TODO()
for now while we consider how to manage background cancellation.
Fixes #733.

pubsub: remove ctx arg from NewTopic and NewSubscription

---

postgres/cloudpostgres/cloudpostgres.go
postgres/cloudpostgres/cloudpostgres_test.go
postgres/cloudpostgres/example_test.go

Brings consistency with the MySQL dialers and avoids pushing the user to escape usernames and passwords properly.

postgres/cloudpostgres: use structured parameters instead of connection string

---

internal/contributebot/README.md
internal/contributebot/prod/k8s/contributebot.yaml

This PR updates the container image tag and adds a link to the contributebot README for viewing deployment details.

internal/contributebot: add link to deployment details in README

---

blob/fileblob/attrs.go
blob/fileblob/fileblob.go
blob/gcsblob/gcsblob.go
internal/retry/retry.go
internal/retry/retry_test.go

Updates #750.
This is needed to make sure `As` works correctly.

blob/all: consistently return raw errors from drivers instead of creating new ones

---

internal/pubsub/mempubsub/mem.go
internal/pubsub/mempubsub/mem_test.go

All driver methods check for a non-existent topic and return an error.
(Non-existent subscription doesn't make sense for this package.)
Addresses #759 for mempubsub.
gcppubsub is TBD.

mempubsub: fail in driver methods on nonexistent topic

---

internal/batcher/batcher.go
internal/batcher/batcher_test.go

This makes it possible to use the batcher with an interface type.

internal/batcher: New takes reflect.Type

---

runtimevar/constantvar/constantvar_test.go
runtimevar/drivertest/drivertest.go
runtimevar/etcdvar/etcdvar_test.go
runtimevar/filevar/filevar_test.go
runtimevar/paramstore/paramstore_test.go
runtimevar/runtimeconfigurator/runtimeconfigurator_test.go

Fixes #797.
This simplifies the tests by not generally mucking around with the `WaitDuration`.

runtimevar/test: use driver.WatchVariable directly in some tests

---

runtimevar/filevar/filevar.go

The current code turns out to be broken, as I discovered with Printfs while adding #812. During that test, the `filevar` implementation blocks as it's supposed to, but it does it because it doesn't even notice the `Rename`, not because it notices it and then notices that the errors are the same. It is difficult to test because it's hard to inject different errors.
Updates #812.

runtimevar/filevar: always add files to the notifier after errors

---

internal/pubsub/pubsub_test.go

pubsub: return after t.Error call in goroutine to avoid nil dereference

---

internal/docs/design.md

Updates `design.md` to refer to the record mode flag in only one way, to reduce confusion.

internal/docs: refer to record mode flag in only 1 way

---

.travis.yml
internal/testing/runchecks.sh

Now we'll only run `-race` and coverage -> Coveralls for the `linux` build.
Updates #862.

travis: only generate coverage data for the linux build

---

go.mod
go.sum
internal/contributebot/go.sum
internal/testing/runchecks.sh
samples/guestbook/wire_gen.go

This ensures that the checked-in `wire_gen.go` files in our repository match what a fresh run of `wire` would generate.
Fixes #827.

tests: run "wire diff" in addition to "wire check"

---

internal/docs/design.md

I realized what I wrote before didn't cover the decision we made for sql's `Params`.

internal/docs: modify design about Options to cover sql.Params

---

docs/index.html

We plan to use the GitHub Pages site associated with this repo to
host redirection pages for our gocloud.dev vanity import path.
As a first step, we set up a trivial site to make sure the basic
Pages config is working.
Our site will live in the docs folder of the master branch.

docs: initial page for our GitHub Pages site.

---

AUTHORS
CONTRIBUTORS
samples/guestbook/wire_gen.go
server/sdserver/server.go
tests/gcp/app/app.go
tests/gcp/app/inject.go
tests/gcp/app/wire_gen.go

Adds a cleanup function fto the Stackdriver exporter, so that client
doesn't have to be aware of exporter.Flush() call.
This change also aligns to xrayserver.NewExporter's return signature.
Samples are updated and regenerated as well.
Fixes #867. 
NOTE: I can't seem to find specific tests needed to validate `sdserver`, (or `xrayserver`). Not sure if I had missed something obvious.

server/sdserver: add cleanup func for Stackdriver exporter

---

internal/pubsub/rabbitpubsub/examples_test.go
internal/pubsub/rabbitpubsub/rabbit.go
internal/pubsub/rabbitpubsub/rabbit_test.go

OpenTopic and OpenSubscription now succeed even if the resource doesn't exist.
They no longer need to return an error.
Also, implement the test harness MakeNonexitentSubscription method.

internal/pubsub/rabbitpubsub: succeed on open of non-existent resource

---

docs/index.html

We don't need a docs directory now that our Github Page comes from the gh-pages branch.

docs: remove

---

internal/contributebot/README.md

For the production Contribute Bot project, a Cloud Build trigger
automates creation of the Docker image, so kicking off a manual Cloud
Build is seldom necessary.
For verifying Contribute Bot being up, `kubectl` will give all the
relevant details without having to switch tools.

internal/contributebot: update build and verify instructions

---

internal/pubsub/pub_test.go
internal/pubsub/rabbitpubsub/examples_test.go
internal/pubsub/rabbitpubsub/rabbit.go
internal/pubsub/rabbitpubsub/rabbit_test.go
internal/secrets/drivertest/drivertest.go
internal/secrets/localsecrets/example_test.go
internal/secrets/localsecrets/localsecrets_test.go

internal: fix import paths

---

internal/testing/runchecks.sh

The parens are creating a subshell and so `result=1` isn't having any effect.
Fixes #960.

travis: actually fail if "wire diff" finds diffs

---

internal/pubsub/rabbitpubsub/doc.go
internal/pubsub/rabbitpubsub/rabbit.go

A previous PR accidentally lopped off the license comment at the top
of rabbit.go. Restore it.

rabbit: tweak file comments

---

blob/blob.go
blob/driver/driver.go

Note that the concrete type never actually sets PageSize (PageSize is not exposed to the end user in the concrete type's ListOptions). It is only included as a driver option so that we can test pagination without creating thousands of blobs.

blob/doc: clean up some docstrings about PageSize

---

wire/README.md

Some links may still exist to this directory, so I want to preserve the README to point elsewhere.

wire: add back README.md

---

blob/gcsblob/example_test.go
blob/gcsblob/gcsblob.go
blob/gcsblob/gcsblob_test.go
blob/s3blob/example_test.go
blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go
runtimevar/paramstore/paramstore.go
runtimevar/paramstore/paramstore_test.go
runtimevar/runtimeconfigurator/example_test.go
runtimevar/runtimeconfigurator/runtimeconfigurator.go
runtimevar/runtimeconfigurator/runtimeconfigurator_test.go
samples/guestbook/inject_aws.go
samples/guestbook/inject_gcp.go
samples/guestbook/wire_gen.go
samples/tutorial/setup.go

This makes more "general" parameters (i.e. what connection is this using) come first in the parameter list so that each argument is increasing specificity. See discussion on #988 for more background.
Fixes #988

all: order cloud client before resource name

---

blob/fileblob/example_test.go
blob/gcsblob/example_test.go
blob/memblob/example_test.go

These are kind of lame examples, but IMHO they are still useful as concrete examples of how to use the constructors, and it's nice to be consistent about providing them.

blob/test: add more example tests

---

internal/contributebot/main.go

The configCache was never populated.

internal/contributebot: populate cache

---

internal/contributebot/main.go

These events will be necessary for merges, but currently aren't used. Adding them now to clear them from the subscription backlog.
Updates #687

internal/contributebot: ignore check run and push events

---

internal/contributebot/design/README.md

internal/contributebot/design: move design doc under design directory

---

runtimevar/runtimevar.go

I don't see any reason to export the internals of `Decoder`, and using `NewDecoder` for `StringDecoder` and `BytesDecoder` saves code and is clearer.
The `stringDecode` and `bytesDecode` changes are independent, but I think are clearer since they are more standard Go than using `reflect`.

runtimevar: use NewDecoder internally, and avoid reflection in built-in decode fns

---

runtimevar/runtimevar.go

Hopefully this makes it more consistent with blob and improves the overall documentation for the major types.
I'll send separate updates to the Decoder stuff down below in this file, and to the providers + driver + example.
Updates #896.

runtimevar/doc: refresh runtimevar concrete type documentation

---

go.mod
go.sum
internal/contributebot/go.sum
internal/testing/replay/replay.go

To include https://github.com/dnaeon/go-vcr/pull/39.
This bug was tickling a problem for Azure.
There was an unrelated change in `go-vcr` since the previous version we were using, which changed it to replay recorded interactions in order. This allows (actually,  requires) us to simplify our matcher code, which previously assumed it was going to be called for all interactions starting from 0 for each request.

all: upgrade go-vcr dependency

---

.travis.yml

Provide the necessary Travis config to create our gh-pages site,
with import-path redirects for our packages, on pushes to master.
Requires a personal GitHub access token, which I've already set up
on the Travis settings page.
The only way to test this is to submit the PR and see what happens.

.travis.yml: generate gh-pages import redirects

---

.travis.yml

Temporary, so we can observe the gh-pages deploy.

.travis.yml: remove windows build

---

internal/contributebot/README.md
internal/contributebot/process.go
internal/contributebot/process_test.go

This simplifies development testing on test repositories, since a fork
would require a different user or organization.

internal/contributebot: make fork branch check configurable

---

blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go
blob/azureblob/testdata/TestConformance/TestAs/verify_ContentLanguage_can_be_written_and_read_through_As.yaml

Some of the previously chosen types were inappropriate, some were documented with the wrong type, and some As functions were not implemented.
The main interesting change is moving the creation of upload Options from `open` into `NewRangedReader` so that it's easier to call `BeforeWrite` with it.

blob/azureblob: flesh out and fix As functionality, and add a test for it

---

.travis.yml
internal/contributebot/go.mod
internal/contributebot/go.sum
internal/contributebot/sync.go

It seems that by setting this, the windows builds are not even running. They get started, and then are aborted to continue to the next stage. See any build [here](https://travis-ci.com/google/go-cloud/builds).
The Windows build is actually broken right now due to a Contribute use of `unix`, and we didn't notice at all; I'd rather have occasional flakiness.
Fixes #920.

travis: don't allow windows builds to fail

---

blob/gcsblob/example_test.go
runtimevar/drivertest/drivertest.go
runtimevar/etcdvar/etcdvar_test.go
runtimevar/runtimeconfigurator/example_test.go

Example tests don't run at all if there's no expected output, so I've modified a couple of GCP ones to use (dummy) JSON credentials and actually run. The previous method of using default credentials was wonky because it depended on the environment (e.g., behavior is different on my machine vs on Travis).
The other changes are small ones to improve code coverage on runtimevar; hopefully the `coveralls` output shows that.
Updates #676.

all/tests: extend some examples/tests to improve coverage

---

.travis.yml
internal/testing/runchecks.sh

There's no real reason to keep ContributeBot running on windows, and there's no reason to do the wire checks per-OS either.
Also configure the OSs to run all in one place. Pretty sure the semantics are the same, but I think this is more clear.
Updates #920.

travis: don't run wire checks or non-core module tests except on linux

---

internal/admin/main.tf
internal/admin/repository/main.tf

Contribute Bot will use this to track pull requests that should be kept in sync with the head branch. Adding the label before Contribute Bot uses it.
Also add "azure" label to Go Cloud repository, since that seems to have been added manually.
Updates #687
Output from `terraform plan`:
```
+ create
+ module.go_cloud_repo.github_issue_label.ready_to_submit
id:          <computed>
color:       "0e8a16"
description: "Pull request has been approved and should be merged once tests pass"
etag:        <computed>
name:        "ready to submit"
repository:  "go-cloud" …
```

internal/admin: add "ready to submit" label

---

blob/azureblob/azureblob.go

I think this got lost in the shuffle because it was added to `blob` while the Azure Pull Request was in flight. The conformance tests didn't notice because `MD5` is not a required field, so `nil` was accepted as valid.
Fixes #1087.

blob/azureblob: fill in MD5 for ListObject and Attributes

---

blob/s3blob/s3blob.go

Adds endpoint, disableSSL, and s3ForcePathStyle query options.
There are more options in aws.Config, but these three are the ones I needed in order to use the package with a local minio instance.
At least endpoint would be required by other s3-compatible services.

blob/s3blob: add query options to url parsing

---

azure/azurecloud/azurecloud.go
blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go
blob/azureblob/example_test.go
internal/testing/setup/setup.go
samples/tutorial/setup.go

Most of the types involved are specific to Azure storage, so I didn't add an `azure` package similar to `gcp` or `aws`. I did add a bunch of types and providers to `azureblob` itself.
In addition to the new types and ProviderSets, the main changes include:
* Support for "default" credentials loaded from the environment.
* You now pass in a `pipeline.Pipeline` (used to make HTTP requests) instead of a `ServiceURL`; given a `pipeline.Pipeline` there are no decisions to make about how to create the `ServiceURL` (other than setting SASToken).
* I moved the `SASToken` to `Options` instead of trying to provide parallel construction paths.
Fixes #1060.

azure: rework azureblob constructors and make them usable via Wire

---

blob/azureblob/azureblob_test.go

This simplifies the command line (I am tired of entering the `--settings` flag).
It also allows running tests from higher up in the tree, since the `--settings` flag is not defined for all providers. I will make use of this for benchmarks soon (e.g., so you can run benchmarks for all blob providers in one go).

blob/azblob: use env variables for tests instead of a settingsfile

---

blob/azureblob/azureblob_test.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob_test.go
blob/gcsblob/gcsblob_test.go
blob/memblob/memblob_test.go
blob/s3blob/example_test.go
blob/s3blob/s3blob_test.go

The benchmarks are implemented similar to conformance tests, so the provider implementation just has to create a `blob.Bucket`.
Sample output:
```
$ go test ./... -bench . | grep Bench
BenchmarkAzureblob/BenchmarkRead-12         	200	   5394847 ns/op
BenchmarkAzureblob/BenchmarkWriteReadDelete-12  100	  17338338 ns/op
BenchmarkFileblob/BenchmarkRead-12         	    50000    23963 ns/op
BenchmarkFileblob/BenchmarkWriteReadDelete-12   20000    76245 ns/op
BenchmarkGcsblob/BenchmarkRead-12         	    500	   2371446 ns/op
BenchmarkGcsblob/BenchmarkWriteReadDelete-12    100	 228282634 ns/op
BenchmarkMemblob/BenchmarkRead-12         	    50000    28073 ns/op
BenchmarkMemblob/BenchmarkWriteReadDelete-12    30000    52072 ns/op
BenchmarkS3blob/BenchmarkRead-12         	    100	  11489126 ns/op …
```

blob/all: add benchmarks for read and write/read/delete

---

internal/trace/trace.go
internal/trace/trace_test.go

A small package that helps add tracing to our APIs.

internal/trace: support for tracing

---

pubsub/gcppubsub/gcppubsub.go

It turns out there is a limit on the number of messages you can publish
in a single RPC. (I reached it during benchmarking.)

gcppubsub: cap the number of messages in a Publish RPC

---

samples/guestbook/README.md

Some of the changes are because I ran `mdformat`. I dropped `jq` and made it more clear that a subset of the requirements are needed to run locally.

docs: updates to samples/guestbook/README

---

README.md

all: fix markdown link to azure

---

go.mod
go.sum
internal/contributebot/go.sum
internal/testing/setup/setup.go

As of v1.18.0, the grpc package will hang when WithBlock is true and
the server it is connected to is not a true gRPC server.
This PR fixes that by creating a real server. It also updates go.mod
to use the latest grpc package.

internal/testing/setup: fix gRPC hang on replay

---

secrets/secrets.go

`wrapError` is only called with non-nil errors.

secrets: delete unused code in wrapError

---

blob/blob.go
blob/drivertest/drivertest.go

We need to unwrap the error before passing to the driver ErrorAs.

blob: fix ErrorAs

---

internal/gcerr/gcerr.go

This factors out code that all drivers using gRPC will need.

internal/gcerr: translate gRPC codes to our own codes

---

internal/admin/repository/main.tf

Output from `terraform plan`:
```
~ update in-place
~ module.go_cloud_repo.github_branch_protection.default_branch
required_status_checks.0.strict: "true" => "false"
~ module.wire_repo.github_branch_protection.default_branch
required_status_checks.0.strict: "true" => "false"
Plan: 0 to add, 2 to change, 0 to destroy.
```

internal/admin: allow stale branches to be merged in

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

Have ErrorAs recognize `os.PathError`s, since they are returned
from many filesystem operations.

blob/fileblob: ErrorAs supports os.PathError

---

runtimevar/blobvar/blobvar.go
runtimevar/blobvar/blobvar_test.go

Since blobvar is built on top of blob, its ErrorAs
method should use blob's.

runtimevar/blobvar: ErrorAs delegates to blob

---

README.md

Removing the suggestion to install wire explicitly in the README. wire is a dependency of go-cloud already, and relevant samples (like the guestbook) further suggest to install it.

all: remove "go get ... wire" from the installation instructions

---

gcerrors/errors.go
go.mod
go.sum
internal/contributebot/go.sum
internal/gcerr/gcerr.go

The xerrors package is the new official package for the error values
proposal.

gcerrors: switch to golang.org/x/xerrors

---

gcerrors/errors.go
gcerrors/errors_test.go
internal/gcerr/errorcode_string.go
internal/gcerr/gcerr.go

- Add codes that match the two context errors.
- Change gcerrors.Code to recognize the context errors and return the appropriate code.
This is sufficient to ensure that callers of `internal/oc.Tracer.End` will
record helpful codes in traces and metrics.

gcerrors: add Canceled and DeadlineExceeded

---

blob/blob.go
internal/gcerr/gcerr.go
pubsub/pubsub.go
runtimevar/runtimevar.go
secrets/secrets.go

APIs shouldn't wrap errors like context.Canceled and io.EOF, so callers
can test for them directly.

all: avoid wrapping certain errors

---

blob/oc_test.go
internal/testing/octest/diff.go
runtimevar/oc_test.go

Weaken the tests so that they work in the presence of -count > 1 and
other tests.

several: make OpenCensus tests more robust

---

pubsub/awspubsub/awspubsub.go

This reduces the verbosity and the amount of branching in in these methods.

pubsub: convert switch statements to maps in awspubsub ErrorCode methods

---

go.sum
internal/gcerr/gcerr.go
pubsub/awspubsub/awspubsub.go

In an attempt to keep to a minimal set of error codes, remove two codes
that map to PermissionDenied and one that maps to ResourceExhausted.

internal/gcerr: remove some error codes

---

internal/workerpool/pool.go
internal/workerpool/pool_test.go

With this change, there is no more lack of type safety in `workerpool.Run`.
This is based on an idea from @jba.

internal: simplify workerpool.Run to return funcs from nextTask, not interface{}

---

pubsub/awspubsub/awspubsub_test.go
pubsub/drivertest/drivertest.go

Fixes #1235.
It runs at about 10 messages per second, most likely indicating a problem in our code.

pusbsub: add benchmark for aws

---

internal/contributebot/go.sum
pubsub/pubsub.go

Fixes #1238.
There was a race condition: If `m.Ack()` results in a permanent error, that should be reported from the next call to `sub.Receive()` but if `sub.Receive()` acquires the subscription's mutex before that permanent error occurs then the call to `getNextBatch()` goes into an infinite loop waiting for a non-empty batch. This change replaces the empty batch loop in `getNextBatch()` with just its body so that it will return and the check for unrecoverable errors within `Receive()` can be reached again even if no more messages come in.
Before:
```
[ ~/src/gocloud.dev/pubsub ] go test -run=TestReceiveReturnsErrorFromSendAcks -count=10000
--- FAIL: TestReceiveReturnsErrorFromSendAcks (5.00s)
acks_test.go:341: got context deadline exceeded; last error: <nil>, want SendAcks failed
--- …
```

pubsub: remove looping logic from getNextBatch to eliminate a race condition

---

internal/proxy/makeproxy.sh

Our project doesn't depend on goveralls directly, but Travis uses it. Travis runs 
```
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
go install github.com/mattn/goveralls;
fi
```
Which ends up in our proxy. The proxy should, therefore, have goveralls installed.

proxy: add goveralls installation into makeproxy

---

blob/blob.go
internal/gcerr/gcerr.go
pubsub/pubsub.go
runtimevar/runtimevar.go
secrets/secrets.go

Define an ErrorAs helper in gcerr, and call it from all concrete
ErrorAs implementations.
This shortens the concrete implementations to a single line and removes
inconsistencies.
Also, add an addition check in ErrorAs for a nil-valued pointer.
Also, add pubsub.Subscriber.ErrorAs, inadvertently omitted.

all: factor out common ErrorAs behavior

---

pubsub/acks_test.go

This test detects the cause of #1238 without running multiple times.

pubsub: add TestReceiveReturnsAckErrorOnNoMoreMessages

---

internal/contributebot/go.sum

This should be similar to #1278, applied to contributebot module.
I see Travis failures
[https://travis-ci.com/google/go-cloud/jobs/176943405] that are due to
transitive dependencies the contributebot module brings. This change is
to sync the state of its go.sum with the state of go.sum in a clean
module cache (which Travis has)

contributebot: Update contributebot's go.sum when run with clean module cache

---

pubsub/drivertest/drivertest.go

These messages clutter the `go test -v` output.
We can add back debug messages when we need to debug something.

pubsub/drivertest: remove debug log messages

---

internal/admin/repository/main.tf

```
+ module.go_cloud_repo.github_issue_label.P2
id:         <computed>
color:      "cc9900"
etag:       <computed>
name:       "P1"
repository: "go-cloud"
url:        <computed>
+ module.wire_repo.github_issue_label.P2
id:         <computed>
color:      "cc9900"
etag:       <computed>
name:       "P1"
repository: "wire"
url:        <computed>
```

admin: add P2 priority to our repositories

---

pubsub/awspubsub/awspubsub_test.go

The `cfg` arg to `sns.New` is optional and doesn't do anything when it's empty.
https://godoc.org/github.com/aws/aws-sdk-go/service/sns#New

pubsub/awspubsub/test: Remove empty aws.Configs that don't do anything

---

internal/docstore/docstore.go
internal/docstore/driver/document.go
internal/docstore/driver/driver.go
internal/docstore/driver/util.go
internal/docstore/drivertest/drivertest.go
internal/docstore/example_test.go
internal/docstore/memdocstore/mem.go
internal/docstore/memdocstore/mem_test.go

This commit includes:
- The concrete Collection and Document types
- The corresponding driver types
- An in-memory implementation
- Some conformance tests
- An example
These include support for the six actions on maps.
Later I will add:
- optimistic locking
- struct support
- queries
- a Firestore implementation

internal/docstore: initial

---

internal/contributebot/main.go
internal/contributebot/setup.go
internal/contributebot/wire_gen.go

Switch from using Google Cloud Pubsub directly, to using it
indirectly via the Go CDK pubsub API.

contributebot: use Go CDK pubsub

---

pubsub/rabbitpubsub/fake_test.go
pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go

With a live rabbitMQ server, code coverage is over 87%.
It is lower with a fake, for the simple reason that the shims
for the live server in amqp.go are not touched. So the number
reported by our CI system is low.
Also, rework closing in the fake to remove a deadlock.

rabbitpubsub: increase code coverage

---

internal/contributebot/go.sum
pubsub/gcppubsub/example_test.go
pubsub/gcppubsub/gcppubsub.go
pubsub/gcppubsub/gcppubsub_test.go
samples/gcmsg/gcp.go

Remove the context.Context argument from OpenTopic and OpenSubscription.
By design, all external work (e.g. establishing client connections)
has already happened by this point, so there is need for a context.

gcppubsub: remove context args

---

internal/gcerr/gcerr.go
internal/gcerr/gcerr_test.go

(*Error).Error() now produces the same output as fmt.Sprintf("%s", ...).
Fixes #1356.

internal/gcerr: make Error() behave like %s

---

.codecov.yml

I think this should prevent `codecov` from blocking commits like it is in #1355 (because of the target=0).
Updates #1352.

travis: add codecov.yml with threshold=0

---

internal/admin/repository/main.tf

Fixes an unfortunate typo from #1321
```
~ update in-place
~ module.go_cloud_repo.github_issue_label.P1
color: "cc9900" => "ff6666"
~ module.go_cloud_repo.github_issue_label.P2
name:  "P1" => "P2"
~ module.wire_repo.github_issue_label.P1
color: "cc9900" => "ff6666"
~ module.wire_repo.github_issue_label.P2
name:  "P1" => "P2"
Plan: 0 to add, 4 to change, 0 to destroy.
```

admin: fix wrong label name

---

blob/gcsblob/gcsblob_test.go

I'm carrying forward an unrelated patch by @vangent from #1359.

blob/gcsblob: add more URL opener tests

---

blob/example_test.go
blob/gcsblob/example_test.go
runtimevar/runtimevar.go
secrets/secrets.go

Adding an example of As where the As call actually succeeds (the fileblog example in the main blob package shows how it can fail). Also renaming to make examples appear in the right places on godoc
Part of addressing #1274

blob: add As example

---

samples/gcmsg/main.go

samples: check for empty messages when publishing to gcp in gcmsg

---

blob/blob.go
runtimevar/runtimevar.go
runtimevar/runtimevar_test.go

Updates #1174.
I plan on adding per-driver openers in a separate PR.

runtimevar: add infrastructure for opening Variables via URL

---

secrets/gcpkms/example_test.go
secrets/gcpkms/kms.go
secrets/gcpkms/kms_test.go

Users will probably have a key resourceID copied from the UI or whatever.

secrets/gcpkms: use a string as the key resourceID instead of a struct

---

aws/aws.go
aws/aws_test.go
blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

This moves some code from `s3blob` to `aws`, in preparation for using it from other APIs.
Updates #1174.

aws: refactor aws.Config URL parsing to aws package

---

pubsub/awspubsub/awspubsub.go
pubsub/awspubsub/awspubsub_test.go
pubsub/azurepubsub/azurepubsub.go
pubsub/drivertest/drivertest.go
pubsub/gcppubsub/gcppubsub.go
pubsub/gcppubsub/gcppubsub_test.go
pubsub/mempubsub/mem.go
pubsub/pub_test.go
pubsub/pubsub.go
pubsub/pubsub_test.go
pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go

This is basically the same thing that was already done for `NewSubscription`, but for `NewTopic` this time.
In a separate PR, I will update the `drivertest` conformance tests to pass non-nil values for the batchers, so that record/replay tests are repeatable. Currently they are flaky because they are based on timing. For example, Windows is dog slow and so the second "ReceiveBatch" call has a different `maxMessages` argument than the current goldens (1000).
Updates #1423.

pubsub: add a batch constructor to NewTopic

---

blob/example_openbucket_test.go
blob/example_test.go

This shows the necessary blank import line when using `OpenBucket` only. Also added some comments inside the example.
Fixes: #1302

blob: split the openbucket example

---

blob/example_test.go

For `Error`, I'll do a followup example that uses `s3blob`.

blob: add examples for remaining As() types that gcsblob supports

---

README.md

This does make the example longer, but IMO more exciting because it's more real.

README: use URL opener for hero example

---

doc.go
internal/docs/design.md

This will make it easier for us to point to this documentation for more details from all the places where As is described
For #1274

docs: move As documentation to doc.go

---

internal/testing/setup/setup.go
secrets/awskms/example_test.go
secrets/awskms/kms.go
secrets/awskms/kms_test.go
secrets/gcpkms/example_test.go
secrets/gcpkms/kms.go
secrets/gcpkms/kms_test.go
secrets/localsecrets/example_test.go
secrets/localsecrets/localsecrets.go
secrets/localsecrets/localsecrets_test.go
secrets/vault/example_test.go
secrets/vault/vault.go
secrets/vault/vault_test.go

This is mostly mechanical, copying the pattern @zombiezen established for `blob`.
The interesting parts are probably:
* I made `localsecrets` register for 2 schemes, 'stringkey://" and "base64key://".
* `vault` is a bit interesting since the URL contains the Vault server address + token; I made it Dial but cache the result.
Updates #1174.

secrets: add support for URLOpeners to all drivers

---

internal/docstore/driver/codec.go
internal/docstore/driver/codec_test.go
internal/docstore/driver/document.go
internal/docstore/driver/document_test.go
internal/docstore/drivertest/drivertest.go
internal/docstore/internal/fields/README.md
internal/docstore/internal/fields/fields.go
internal/docstore/internal/fields/fields_test.go
internal/docstore/internal/fields/fold.go
internal/docstore/internal/fields/fold_test.go
internal/docstore/memdocstore/codec.go
internal/docstore/memdocstore/codec_test.go
internal/docstore/memdocstore/mem.go

Support for structs:
- Getting and setting struct fields (in driver/document.go)
- Encoding an decoding values (including structs) into native representations.
Add struct support to memdocstore.

internal/docstore: structs

---

blob/azureblob/azureblob_test.go
blob/blob_test.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/gcsblob/gcsblob_test.go
blob/s3blob/s3blob_test.go
internal/gcerr/gcerr.go
pubsub/mempubsub/mem.go
pubsub/pubsub_test.go
runtimevar/driver/driver.go
runtimevar/filevar/filevar_test.go
runtimevar/runtimevar_test.go

all: replace "concrete type" with "portable type" in doc strings

---

secrets/example_openkeeper_test.go

secrets: add a portable API example for OpenKeeper

---

pubsub/acks_test.go
pubsub/awspubsub/awspubsub.go
pubsub/azurepubsub/azurepubsub.go
pubsub/driver/driver.go
pubsub/gcppubsub/gcppubsub.go
pubsub/mempubsub/mem.go
pubsub/pubsub.go
pubsub/pubsub_test.go
pubsub/rabbitpubsub/rabbit.go
pubsub/sub_test.go

WIP: TESTS WILL FAIL
This allows providers to communicate whether they support Ack.  If a
provider doesn't, it needs to a provide an alternate implementation of
Ack.
Fixes #1378.

pubsub: add AckFunc method to driver Subscription

---

pubsub/gcppubsub/gcppubsub.go
pubsub/pubsub.go

Fix `gcspubsub` to `gcppubsub`

pubsub: fix typo

---

internal/docstore/drivertest/drivertest.go
internal/docstore/memdocstore/mem_test.go

Preliminary version of a test that checks that the docstore encoding
of values interoperates with a provider's native encoding.
See #1477.

docstore: a conformance test for native codecs

---

runtimevar/runtimevar.go
runtimevar/runtimevar_test.go

runtimevar: mark closed before shutting down background goroutine to avoid race

---

internal/docstore/driver/codec.go
internal/docstore/driver/codec_test.go
internal/docstore/memdocstore/codec.go

Add Encoder.EncodeSpecial and Decoder.AsSpecial methods to
support special-case encoding and decoding.
Remove Encoder.EncodeStruct.

docstore: support special cases in codec

---

internal/testing/runchecks.sh

As per [Maintaining module requirements][1], the recommended way of running `go test` in CI is with `-mod=readonly`. This causes the `go` command to fail if a new dependency was added without adding to go.mod.
(I happened to stumble across this recommendation from @rsc in an unrelated [thread on golang-dev][2].)
[1]: https://golang.org/cmd/go/#hdr-Maintaining_module_requirements
[2]: https://groups.google.com/d/msg/golang-dev/DD88cds-LuI/GiyP3Hf2BgAJ

travis: use -mod=readonly when invoking Go

---

doc.go

My plan is to do something similar to what Eli did for "As" -- remove most of the documentation from the actual code and point to here instead, so we can document well once instead of copypasta everywhere.

doc: add documentation for URLs

---

internal/testing/replay/replay.go
pubsub/pubsub.go

pubsub: ensure that the recorded message processing time is > 0

---

internal/docstore/drivertest/drivertest.go
internal/docstore/firedocstore/fs_test.go
internal/docstore/firedocstore/native_codec_test.go

For Firestore, the "native" codec is implemented by the cloud.google.com/go/firestore
client. Use gRPC interceptors to obtain the protos from this client.
Add an implementation of drivertest.CodecTester, and pass it to the conformance tests.
Remove uint and complex from the test. Firestore can't handle either type.
.
.

firedocstore: implement the codec test

---

internal/docstore/drivertest/drivertest.go
internal/docstore/firedocstore/fs_test.go

Test that the docstore codec can round-trip with itself using
a large set of types (ultimately, all the types that docstore supports).
For native-docstore round trips, let the driver tell the conformance
tests what types it doesn't support, so we can skip those in a
driver-specific way.

docstore: improve codec conformance tests

---

runtimevar/runtimevar.go
runtimevar/runtimevar_test.go

A follow-up PR will support `DecoderByName` used by URLOpeners.
Updates #1290

runtimevar: add a DecryptDecoder

---

internal/docstore/driver/codec.go
internal/docstore/drivertest/drivertest.go
internal/docstore/firedocstore/codec.go
internal/docstore/firedocstore/codec_test.go

Add support for time.Time and the two protos Timestamp and LatLng.
The Firestore service supports these natively, so we must intercept
the default driver codec (using EncodeSpecial/AsSpecial) to handle
them.
Also, add time.Time to the codec round-trip tests. I think every
native codec will support it.

firedocstore: support special types

---

pubsub/awspubsub/awspubsub.go
pubsub/driver/driver.go
pubsub/drivertest/drivertest.go
pubsub/mempubsub/mem.go
pubsub/rabbitpubsub/rabbit.go

This PR is a bit of a grab bag now, of things I discovered trying to add a conformance test for canceling an in-flight `Receive`.
* I found that we weren't returning the `Canceled` error code correctly for AWS; fixed (although I couldn't find a constant for that error).
* The test `isCanceled` function wasn't checking for `gcerr.Canceled`.
* `awspubsub` and `mempubsub` weren't handling "got no messages" consistently with what `driver.ReceiveBatch` says.
* I updated the docstring for `driver.ReceiveBatch` to be a bit more explicit.
* I added a comment about why adding a test for canceling an in-flight `Receive` is hard.

pubsub: modify mem/aws/rabbit behavior for 0 messages in ReceiveBatch; better cancel error checks

---

blob/fileblob/fileblob.go

Release 0.11.0 added support for SignedUrl with fileblob. The implementation however assumes the opts struct fields has been initialised when it calls `b.opts.URLSigner == nil`. Other blob providers such as gcs and s3 initialise opts to the empty struct if the one provided by openBucket is nil. This behaviour lets consumers use the field without checking it has been set. This adds similar code to fileBlob and will prevent the SignedUrl function from panicking, as happened here:
```
runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc000264000)
/usr/local/Cellar/go/1.11.5/libexec/src/net/http/server.go:1746 +0xd0
panic(0x147aa40, 0x18b1450)
/usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9 …
```

blob/fileblob: initialize opts to empty struct

---

pubsub/benchmark_test.go
pubsub/drivertest/drivertest.go
pubsub/pubsub.go

Sample output with the default settings:
```
$ go test --run TestReceivePerformance
Elapsed (sec)	Msgs/sec	Max Messages
0.000081	12318.001527	1
0.000223	7067487.437541	1000
1.000242	751985.161829	1000
2.000659	792669.396619	1000
3.001288	810490.673882	1000
4.001931	803483.069525	1000
5.002907	787231.494381	1000
6.003415	735626.551089	1000
7.003970	801555.034357	1000
8.005067	805116.952557	1000
9.005451	701730.566339	1000
PASS
ok  	gocloud.dev/pubsub	10.097s
```
Updates #1441.
My plan is to use this to experiment with different settings in pubsub.go. For example:
* What happens if `ReceiveBatch` takes 250ms every time?
* What happens if `ReceiveBatch` is fast but returns fewer than `maxMessages`?
* What happens if the application never calls `Ack`?
* What happens if message processing is …

pubsub: add a test that can be used to characterize Receive performance

---

internal/retry/retry.go
internal/retry/retry_test.go

After this PR, you can test if a retry error is the result
of cancelation using
```
xerrors.Is(err, context.Canceled)
```
Updates #1591.

internal/retry: support the errors.Is method

---

go.sum
internal/testing/check_api_change.sh
internal/testing/listdeps.sh
internal/testing/runchecks.sh

Fixes #1570.
The checks are relatively slow; it takes about 1 second to run `apidiff` on a package, and we need to run it twice (actually, we run it 4 times, but the `-w` ones to export pkg data are the expensive ones). We have about 50 packages.
It would be nice to use `git diff --names-only master` to quickly figure out which packages have changes, and skip packages that don't have changes, but it's not obvious to me how to map file names from `git diff` to package names from `go list`.

travis: add a check for incompatible API changes

---

pubsub/benchmark_test.go

Instead of running a single benchmark, the test now runs a suite of them.
[Here's](https://docs.google.com/spreadsheets/d/1c3mqHJ33mN64xBQrx42DY1GpYrMUi7IEl-6FRawIv70/edit) the sample spreadsheet I have set up with the results. `out` is the output of the benchmark suite with HEAD. `out2` is the output of the benchmark suite with a single change, to modify `pubsub.desiredQueueDuration` from 2s to 50ms. Each row of the graph corresponds to a specific benchmark profile; the current columns are messages/sec, RPCs/sec, and batch size (== `maxMessages`).
So, for example, you can see that reducing desiredQueueDuration would increase RPCs/sec significantly in various scenarios.
Feedback on the spreadsheet and the specific tests in the suite is welcome!
Updates #1441.

pubsub/tests: add a suite of benchmarks

---

pubsub/azurepubsub/azurepubsub.go
pubsub/azurepubsub/azurepubsub_test.go
pubsub/azurepubsub/example_test.go

The main change here is to only check for existence of the Subscription once, instead of once per `ReceiveBatch`. I also moved some other verification (e.g., that parameters are not `nil`) into the constructors.
I also add the benchmark harness so you can run:
```
$ go test -v -bench . ./... --run Benchmark
```
Finally, I tried to run the conformance tests in `servicebus.SubscriptionWithReceiveAndDelete` mode, but they do not pass. It looks like the semantics are not what we expect -- that options seems to delete the message even if there are multiple subscribers. I commented out the new test for now, and will open a separate issue to discuss.
Fixes #1569.

pubsub/azurepubsub: do more sanity checks in constructors; only do subscription-existence check once

---

runtimevar/blobvar/blobvar.go
runtimevar/blobvar/blobvar_test.go
runtimevar/blobvar/example_test.go

Per discussion on #1488.
Fixes #1488.
Fixes #1498.

runtimevar/blobvar: only support a single Bucket URL via env variable

---

internal/docstore/dynamodocstore/codec.go
internal/docstore/dynamodocstore/codec_test.go
internal/docstore/dynamodocstore/dynamo.go
internal/docstore/dynamodocstore/dynamo_test.go

Also let the encoder return `*dynamodb.AttributeValue` instead of `map[string]*dynamodb.AttributeValue` as that matches the native encoder's output type.

internal/docstore: implement codecTester for dynamodocstore

---

pubsub/benchmark_test.go
pubsub/pubsub.go

Previously, having the lines emitted as part of the callbook hook meant that runs of the test would result in different numbers of output points, which makes the results difficult to graph. Now it consistently emits a line every 25ms for the first half second, and every 500ms after that.
Also, I changed the single callback hook into 2, one that is called before `ReceiveBatch` and one after; this gives clearer results for situations where the simulated `ReceiveBatch` call takes a long time.
I also now run each profile as a subtest to make it easier to run a single one.
Updates #1441.

pubsub/tests: change benchmark to report on a ticker instead of callback

---

pubsub/pubsub.go

The heading algorithm doesn't like periods followed by whitespace, as in "vs. "

pubsub: make the delivery section of the package doc be a heading

---

internal/testing/check_api_change.sh

I accidentally checked this in after testing with it :-(.

travis/tests: remove grep for pubsub from breaking API change check

---

internal/docstore/memdocstore/codec.go
internal/docstore/memdocstore/codec_test.go
internal/docstore/memdocstore/mem.go

Follow encoding/json convention of having the destination second.

memdocstore: change arg order for decodeDoc

---

.travis.yml

Test failures/flakes should not stop the site from being pushed, and the Hugo deploy process does not take long.

travis: build website before running tests

---

internal/website/static/css/style.css
internal/website/static/css/syntax.css

Overflow of long lines will scroll, not wrap.
Since I was poking around the CSS for code blocks anyway, I simplified the rules and made the syntax highlighting match brand colors.
Fixes #1633

internal/website: constrain code blocks to width of content area

---

internal/docstore/drivertest/drivertest.go
internal/docstore/memdocstore/mem_test.go

The test in drivertest that verifies updates are atomic doesn't work
for all providers. So just test memdocstore.

docstore: move atomic-update test to memdocstore

---

internal/docstore/driver/util.go
internal/docstore/driver/util_test.go
internal/docstore/firedocstore/fs.go

More than one driver will want to split a list of actions to run into
groups to optimize RPCs. Since the logic is a little tricky, factor
out to a common function.
Use it for the Firestore driver.

docstore/driver: add SplitActions

---

pubsub/gcppubsub/gcppubsub.go
pubsub/pubsub.go

Benchmark results. The number represents the value of the 3 "max" constants in the code below.
```
HEAD: 1725.95 MB/s
PR: 2093.29 MB/s
```
Not a huge win, but something. The numbers get better (including the advantage from this change) if you increase the number of message for the benchmark; it tends to be pretty slow at startup, with each RPC taking a full second (not sure why), and then at some point it ramps up and gets going pretty good.
Fixes #1643.

pubsub/gcppubsub: make Pull requests in parallel

---

pubsub/awssnssqs/awssnssqs.go
pubsub/drivertest/drivertest.go

Benchmark results. The number represents the value of the 3 "max" constants in the code below.
```
HEAD: 102.99 MB/s
10: 509.93 MB/s
25: 1081.00 MB/s
50: 1887.33 MB/s
100: 2493.14 MB/s
250: 2022.15 MB/s
```
Based on that, I've chosen 100 as a sweet spot.
Fixes #1642.

pubsub/awssnssqs: send multiple receive and ack RPCs concurrently

---

go.mod
go.sum

I updated this single package and ran `go mod tidy`, which updated or removed several other dependencies. I used Go 1.12.1 to do this.
v0.19.1 and earlier had an annoying issue caused by references to `git.apache.org/thrift.git`. That's a dead repo (The Thrift project moved to `github.com/apache/thrift`). You can still see [the historical reference to it in their `go.sum` file](https://github.com/census-instrumentation/opencensus-go/blob/5ae9166f90ff989c557e45fcb9592ac59afa0fa0/go.sum#L3) along with [the updated repo URL](https://github.com/census-instrumentation/opencensus-go/blob/5ae9166f90ff989c557e45fcb9592ac59afa0fa0/go.sum#L9,L10).
This update will put the correct `github.com/apache/thrift` URL in your `go.sum` file.

all: Update opencensus-go v0.19.1 -> v0.19.2

---

internal/website/content/howto/secrets/_index.md
internal/website/content/howto/secrets/crypt.md
internal/website/content/howto/secrets/open-keeper.md
internal/website/content/howto/secrets/runtimevar.md

Like #1630, kept as draft for now to batch how-to guide for publication. This guide has some intentional outstanding TODOs for issues that I found while writing the guide. This will need to be addressed before publishing, but should not change the structure of the guides AFAIK.
Updates #1576
/cc @clausti @shantuo for context on issues I've been opening.

internal/website/content/howto/secrets: add section

---

internal/docstore/driver/codec.go
internal/docstore/driver/codec_test.go

- Report an error on failed int and uint decoding. We weren't failing
property if a value couldn't be decoded as an int or uint.
- Also, test non-integral floats converting to int and uint. Improve
the returned error.

docstore: improve codec for ints, uints

---

internal/admin/repository/main.tf

I'd like to be able to filter on documentation-only changes, since this
seems like a separate enough category.
`terraform plan` output:
```
+ create
+ module.go_cloud_repo.github_issue_label.documentation
id:          <computed>
color:       "edd782"
description: "Documentation change"
etag:        <computed>
name:        "documentation"
repository:  "go-cloud"
url:         <computed>
+ module.wire_repo.github_issue_label.documentation
id:          <computed>
color:       "edd782"
description: "Documentation change"
etag:        <computed>
name: …
```

internal/admin: create documentation label in repos

---

pubsub/pubsub.go

Before this PR, the behavior is inconsistent (it depends on driver behavior; some return an empty map, others return nil). Consistency is good.
I noticed this when running conformance tests that used a `nil` Metadata when sending and tried to verify that the received message matched; for some drivers, it did, and for others, it didn't (because the latter drivers returned an empty map instead of nil).

pubsub: ensure Message.Metadata is consistently nil if empty

---

pubsub/rabbitpubsub/rabbit.go

I found this hang exceedingly hard to reproduce, but I think the problem is that sometimes we'd end up looping forever in `ReceiveBatch`, holding the lock the whole time. Meanwhile, someone else is trying to ack/nack, but they can't get the lock. It's safer to return, give up the lock, and let the portable type call us back.
Fixes #1728.

pubsub/rabbit: give up the lock when we're not receiving anything

---

internal/docstore/drivertest/drivertest.go
internal/docstore/mongodocstore/codec.go

Test the decoder's AsInterface method, which decodes values
without knowing the intended type.

docstore: test blind decoding

---

pubsub/pubsub.go
pubsub/pubsub_test.go

Fixes #1454.
This is similar to the finalizer we have for blob.Reader/Writer:
https://github.com/google/go-cloud/blob/master/blob/blob.go#L658

pubsub: add a finalizer that complains if a message isn't acked/nacked

---

pubsub/awssnssqs/awssnssqs.go
pubsub/awssnssqs/awssnssqs_test.go
pubsub/awssnssqs/example_test.go

Migrated OpenTopic&OpenSubscription functions to use ConfigProvider: 
Fixes #1713.

pubsub/awssnssqs: OpenTopic&OpenSubscription use ConfigProvider

---

pubsub/drivertest/drivertest.go
pubsub/pubsub.go
pubsub/pubsub_test.go
pubsub/sub_test.go

Fixes #1743.
Recently I changed `pubsub` to convert from `driver.Message` to `Message` when messages arrive from the driver via `ReceiveBatch`, so they are stored in the queue as `*Message`. This interferes with accurate reporting of a `Message` going out of scope without ack/nack being called, because the array holding the queue often holds a reference to a message even after the message has been returned and re-sliced past it.
This PR changes pubsub back to converting to `Message` at the last minute, and holding `driver.Message` in the queue.
This flushed out a few more places in tests where we weren't calling `Ack`.

pubsub: convert to Message as late as possible

---

pubsub/awssnssqs/awssnssqs.go
pubsub/awssnssqs/awssnssqs_test.go
pubsub/awssnssqs/example_test.go

Changed pubsub/awssnssqs UrlOpener scheme from `awssnssqs` to `sns` and `sqs` respectively.
Fixes #1707

pubsub/awssnssqs: Changed UrlOpener scheme to awssns and awssqs

---

blob/s3blob/example_test.go
pubsub/awssnssqs/example_test.go
runtimevar/awsparamstore/example_test.go
secrets/awskms/example_test.go

all: Rename session-->sess in examples to avoid package name shadowing

---

blob/driver/driver.go

I think these were missed when converting to `gcerror`.

blob: fix up some comments about errors

---

internal/docstore/drivertest/drivertest.go

I'm separate the conformance tests out first since dynamo needs some rework to properly support query.

internal/docstore/drivertest: conformance tests for query

---

blob/azureblob/azureblob.go
blob/azureblob/testdata/TestConformance/TestCopy/Works.yaml
blob/blob.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/gcsblob/gcsblob.go
blob/gcsblob/testdata/TestConformance/TestCopy/Works.yaml
blob/memblob/memblob.go
blob/s3blob/s3blob.go
blob/s3blob/testdata/TestConformance/TestCopy/Works.yaml
blob/s3blob/testdata/TestConformanceUsingLegacyList/TestCopy/Works.yaml

cc @Zyqsempai 
This PR adds the portable API method, extends the driver interface, adds conformance tests, and implements `memblob` and `fileblob`.
It is marked as a breaking change due to the new method in the blob driver interface; since all drivers are in this repo this will not be a breaking change for our users.
Left for subsequent PRs (and marked with TODOs):
* Implementation for the 3 cloud provider drivers.
* Extending conformance tests for `As` to include `CopyOptions.BeforeCopy`.
* Verifying and documenting and testing the semantics for what happens if the destination already exists. Both `fileblob` and `memblob` overwrite, but I'm not sure what the cloud providers do yet.
Updates #1696.

blob/all: add a Copy method BREAKING_CHANGE_OK

---

pubsub/natspubsub/example_test.go
pubsub/natspubsub/nats.go
pubsub/natspubsub/nats_test.go

Fixes #1715 by renaming `CreateTopic`/`CreateSubscription` -> `OpenTopic`/`OpenSubscription`.
Fixes #1716:
* Clarified that "topicName" and "subscriptionName" are really NATS subjects by renaming various args and variables to "subject".
* Updated commented-out lines in example about NGS/credentials with a link.
* "Are there ways to set credentials and such in the URLOpener?" --> not currently no.
* Added a link to the centralized documentation for provider semantics to the ackfunc doc in a couple of places. The centralized documentation should probably be improved, but there's no need to repeat it for every driver.
* Lengthened some variable names in examples.

pubsub/nats: BREAKING_CHANGE rename CreateTopic/Subscription->OpenTopic/Subscription; doc improvements

---

internal/website/content/howto/blob/open-bucket.md
internal/website/static/css/style.css

(Because I know how much you enjoy reviewing CSS, @eliben.)
The part missing from the CSS before was declaring MainContent to be a new block formatting context. I do this by setting overflow to hidden.
Also includes some small content fixes.

internal/website: prevent code samples from widening main content region

---

internal/docstore/firedocstore/doc.go
internal/docstore/firedocstore/query.go
internal/docstore/firedocstore/query_test.go

Add support for locally evaluating some filters.
TODO: add multi-filter conformance tests (after the dynamo gets basic query support)
Updates #1338.

firedocstore: support multiple filters in queries

---

internal/cmd/gocdk/build.go
internal/cmd/gocdk/deploy.go
internal/cmd/gocdk/flagset.go
internal/cmd/gocdk/flagset_test.go
internal/cmd/gocdk/main.go

Otherwise, the control flow of when the flag parsing error is shown is unclear and buried inside the flag package.
@clausti This is the result of my yak-shaving: a large pile of hair worthy of its own PR. Keeping as draft until #1796 is merged in.

internal/cmd/gocdk: customize flag parsing setup

---

go.sum
internal/testing/check_api_change.sh

I also made changes suggested by [shellcheck](https://www.shellcheck.net/) to avoid escaping issues. They're made as separate commits if you want to isolate the changes for review.
Fixes #1802

internal/testing: don't break if upstream changes during test execution

---

internal/cmd/gocdk/apply.go
internal/cmd/gocdk/apply_test.go
internal/cmd/gocdk/main.go
internal/cmd/gocdk/main_test.go

implements a minimal `apply` command, with some initial tests
fixes #1816

internal/cmd/gocdk: apply

---

blob/azureblob/azureblob.go

blob/azureblob: fix construction of service URL when using SASToken

---

internal/website/content/tutorials/cli-uploader.md

Fixes the Azure environment variable credential names in the cli-uploader tutorial

cli-uploader tutorial: fix Azure env var names

---

internal/docstore/docstore.go
internal/docstore/docstore_test.go

Updates #1651 
First step, add to the portable API. Code is mostly adapted from blob package.

internal/docstore: add URL opener to portable API

---

internal/docstore/dynamodocstore/query.go
internal/docstore/dynamodocstore/testdata/TestConformance/Create.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Data.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Delete.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Get.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Put.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Query.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Replace.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Update.yaml

Fall back to using the Scan RPC if the conditions for a Query RPC
aren't met.

dynamodocstore: use Scan if we can't use Query

---

internal/docstore/dynamodocstore/codec.go

Encode just the key fields, not the entire document.

dynamodocstore: encode key fields more efficiently

---

internal/docstore/driver/document.go
internal/docstore/mongodocstore/mongo.go
internal/docstore/mongodocstore/mongo_test.go

Previously, we assumed the key field of every collection was "_id",
the same as MongoDB's key field. That forces every collection that
wants to be portable to use that field name.
Now, have the user provide a function to extract the ID from the
document. This allows any field (or even a combination of fields)
to be used as the MongoDB _id field.

mongodocstore: extract the ID field with a function

---

internal/docstore/dynamodocstore/dynamo.go
internal/docstore/dynamodocstore/query.go
internal/docstore/dynamodocstore/query_test.go
internal/docstore/dynamodocstore/testdata/TestConformance/Create.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Data.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Delete.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Get.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Put.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Query.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Replace.yaml
internal/docstore/dynamodocstore/testdata/TestConformance/Update.yaml

Take table indexes into account when deciding how to run a query.
Add tests for query planning.
Updates #1832. This PR builds and runs the RPCs, but we also need to
report the plan to the user.

dynamodocstore: query plan with indexes

---

blob/example_test.go
blob/gcsblob/gcsblob.go
blob/gcsblob/gcsblob_test.go

**BREAKING_CHANGE**
For consistency with `WriterOptions.BeforeWrite` and to preserve reader identity (don't want to duplicate state).

blob/gcsblob: return *storage.Reader from gcsblob escape hatch

---

blob/fileblob/fileblob.go

This improves the performance of ListPaged for the fileblob store when specifying a Prefix containing a path by modifying the `filepath.Walk`'s root to be based on the Prefix.
e.g. A Prefix of `foo/bar/baz` will start the `filepath.Walk` at `{bucket dir}/foo/bar` as any files in directories below would not match the prefix. This preempts Walking unnecessarily around the directory tree below `foo/bar/baz`.
This performance problem came up in an application with only a couple thousand files but with a deeply nested filesystem-like keying system where the app knows what "directory" to List entries in. 
Let me know if I should write tests -- I figured the existing List tests which included some keys with path separators might suffice, but I'm happy to extend if it is required.

blob/fileblob: improve ListPaged by adjusting root based on Prefix

---

blob/azureblob/azureblob.go
blob/blob.go
blob/blob_test.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/gcsblob/gcsblob.go
blob/memblob/memblob.go
blob/s3blob/s3blob.go

blob: return pointer to Attributes structs instead of copying

---

internal/docstore/memdocstore/mem.go
internal/docstore/memdocstore/mem_test.go

* `mem` is constent with `memblob` and `mempubsub`.
* Documented that the URL host is used as the keyField.
* Updated test to actually do that.

docstore/memdocstore: changes to URLOpener

---

pubsub/pubsub.go

Follow-up from an offline discussion about Pub/Sub where I learned how to use Nack properly from @vangent.

pubsub: document intended use of Nack

---

pubsub/rabbitpubsub/rabbit.go

pubsub/rabbit: remove stale TODO

---

pubsub/natspubsub/nats.go
pubsub/natspubsub/nats_test.go

pubsub/nats: only receive 1 msg at a time to avoid dropping queued messages

---

blob/s3blob/s3blob.go

blob/s3blob: check error when hex-decoding ETag to get MD5

---

blob/azureblob/example_test.go
blob/example_test.go
blob/fileblob/example_test.go
blob/gcsblob/example_test.go
blob/memblob/example_test.go
blob/s3blob/example_test.go
internal/website/content/howto/blob/data.md
internal/website/content/howto/blob/open-bucket.md
internal/website/data/examples.json
internal/website/layouts/shortcodes/goexample.html

Add Hugo shortcode to read from examples.json.
I rewrote the blob godoc examples to match what was in the how-to guides. The page rendering is slightly different, but no substantive content change.
Updates #1827

internal/website: rewrite blob how-to guide to use blob godoc examples

---

internal/docstore/mongodocstore/mongo.go
internal/docstore/mongodocstore/mongo_test.go
internal/docstore/mongodocstore/query.go

Updates #1675 
Mongo doesn't have a special type for `Find`, only add `As` support for the `Cursor` type.

internal/docstore/mongodocstore: add as to query

---

internal/docstore/dynamodocstore/query.go
internal/docstore/dynamodocstore/query_test.go

Unless a local index specifies ALL as its projection, it cannot in
general satisfy a query that wants all the fields of the
document. (The DynamoDB documentation claims that fields missing in a
local index are retrieved from the table, but apparently that only
applies to fields that are explicitly named in the query.)

dynamodocstore: reject a partial local index when selecting all fields

---

pubsub/azuresb/azuresb.go
pubsub/azuresb/azuresb_test.go

These are tests that don't run on Travis, and I must have failed to run them after making `drivertest` changes in #1787.

pubsub/azuresb: fix tests after recent drivertest changes

---

internal/cmd/gocdk/serve.go

Before:
```
$ gocdk serve
gocdk: 2019/04/29 16:04:51 Preparing to serve dev...
[Terraform stuff omitted]
gocdk: 2019/04/29 16:04:52 Building server...
^Cgocdk: 2019/04/29 16:04:53 Build: build server: wire: signal: interrupt
gocdk: 2019/04/29 16:04:53 Shutting down...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x7acd4a]
goroutine 10 [running]:
main.endServerProcess(0x0)
/usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/cmd/gocdk/serve.go:370 +0x6a
main.serveBuildLoop(0x8c87a0, 0xc00006e440, 0xc0000a81e0, 0xc00011a500, 0xc00005c320, 0xc00006e140, 0x0, 0x0)
/usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/cmd/gocdk/serve.go:194 +0xadb …
```

internal/gocdk: fix panic if ctrl-c early in gocdk serve

---

pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go

`TestCancelSendAndReceive` is flaky, and heavily overlaps with a conformance test of the same name.
`TestPublishConcurrently` overlaps with at least a conformance benchmark, and current configuration means `SendBatch` isn't called concurrently anyway.
Fixes #1950.

pubsub/rabbitpubsub: remove unnecessary and flaky tests

---

internal/contributebot/go.mod
internal/contributebot/go.sum

Travis is failing with 
`go: updates to go.mod needed, disabled by -mod=readonly`

internal/contributebot: update go.mod file

---

internal/docstore/firedocstore/fs.go

We don't need to support field paths in decoding, because we use
the field mask in the RPC to get only the fields we want from the service.

firedocstore: remove wrong TODO

---

go.mod
go.sum
internal/docstore/mongodocstore/codec.go
internal/docstore/mongodocstore/mongo.go
internal/docstore/mongodocstore/mongo_test.go
internal/docstore/mongodocstore/query.go

Add an option to OpenCollection that causes field names to be lowercased
on encoding, and also when mentioned in actions and queries.
See #1899 for rationale.
Fixes #1899.

mongodocstore: provide an option to lowercase field names

---

runtimevar/filevar/filevar_test.go
runtimevar/runtimevar_test.go
secrets/example_openkeeper_test.go
secrets/example_test.go
secrets/localsecrets/example_test.go
secrets/localsecrets/localsecrets.go
secrets/localsecrets/localsecrets_test.go

This PR updates the `localsecrets` methods `ByteKey` and `Base64Key` to error if not given 32 bytes of secret material (measured after decoding, in the case of `Base64Key`).
It also adds a convenience method for generating 32 random bytes to use. 
fixes #1664

secrets/localsecrets: error if secret material not 32 bytes

---

internal/testing/replay/replay.go
internal/testing/setup/setup.go

This is refactoring one of the last remaining uses of the `recorder` package - here used just for a flag, so I'm replacing it with a boolean.
This is currently stuck on #1972 since I can't test the recording properly (replay passes).
Updates #770

pubsub/gcppubsub: refactor usage of recorder flag

---

internal/docstore/drivertest/drivertest.go
internal/docstore/drivertest/util.go
internal/docstore/dynamodocstore/codec_test.go
internal/docstore/firedocstore/codec_test.go
internal/docstore/firedocstore/fs_test.go
internal/docstore/firedocstore/query_test.go
internal/docstore/memdocstore/codec_test.go
internal/docstore/mongodocstore/mongo_test.go

Avoid having to deal with the error from NewDocument for tests.

docstore: add a MustDocument method to simplify testing

---

internal/contributebot/go.sum
internal/testing/listdeps.sh
internal/testing/runchecks.sh

Removes the `-x` bash command so that we no longer echo every command, and inserts some explicit `echo`s to keep track of what's going on. IMHO this makes the output a lot more readable.

internal/travis: clean up runchecks.sh

---

internal/website/layouts/_default/sitemap.xml

Use a sorted range loop of data pages to prevent undefined order which
causes superfluous diffs
Updates #1994

website: add custom sitemap.xml template

---

internal/docstore/docstore.go

Don't insist that failures be attributed to specific actions. This
lets us use the MongoDB BulkWrite RPC for unordered action lists,
which is significantly faster than running the individual RPCs
concurrently.
See #1999.

docstore: relax the error semantics of unordered action lists

---

pubsub/pubsub.go

CanNack() is a method of Subscription, not Message.

pubsub/doc: delete obsolete sentence about Message.CanNack

---

internal/contributebot/go.mod
internal/contributebot/go.sum

This is failing Travis:
https://travis-ci.com/google/go-cloud/jobs/198855413
```
go: updates to go.mod needed, disabled by -mod=readonly
```
Not sure how it got past Travis during the original PR...?

internal/contributebot: fix mod file

---

internal/docstore/mongodocstore/mongo_test.go
internal/testing/runchecks.sh
internal/testing/setup/setup.go
pubsub/kafkapubsub/kafka_test.go
pubsub/rabbitpubsub/rabbit_test.go
runtimevar/etcdvar/etcdvar_test.go
secrets/vault/vault_test.go

Fixes #2005 
All tests that require Docker container to run will run when either:
1) Not on Travis.
2) On Travis Linux environment, where Docker is available.

all: run Docker dependent tests whenever possible

---

tests/aws/app/app_test.go

Returning from TestMain doesn't play well with `go test -json` (see #2041). Instead we'll properly skip these tests when no test environment is set up

testing: properly skip tests/aws/app tests when no environment is set up

---

internal/docstore/drivertest/drivertest.go
internal/docstore/dynamodocstore/dynamo.go
internal/docstore/dynamodocstore/dynamo_test.go
internal/docstore/dynamodocstore/example_test.go
internal/docstore/dynamodocstore/query.go
internal/docstore/dynamodocstore/query_test.go
internal/docstore/query.go

Return error if a non-trivial query requires a table scan.
Add an option that the user can set to opt in to scans.

dynamodocstore: require opt-in for table scans

---

internal/docstore/mongodocstore/mongo.go
internal/docstore/mongodocstore/mongo_test.go
internal/docstore/mongodocstore/query.go

mongo is a little bit different, it doesn't have special types for the inputs, but one can use the corresponding options types to do similar things like other drivers.
Fixes #1675

internal/docstore/mongodocstore: add BeforeQuery and BeforeDo

---

pubsub/rabbitpubsub/rabbit.go

We were creating a ticker on each call to ReceiveBatch, but we weren't
stopping it.  Also, we only care about the first channel send (if
any). So switch to a timer instead.
In informal CPU profiling of a simplified program, this helped
significantly with CPU usage.
Fixes #2103.

rabbitpubsub: use timer in ReceiveBatch, not ticker

---

blob/blob.go
blob/driver/driver.go
doc.go
internal/docs/design.md
internal/docstore/docstore.go
internal/docstore/driver/driver.go
internal/docstore/query.go
internal/website/content/concepts/as.md
pubsub/driver/driver.go
pubsub/pubsub.go
runtimevar/driver/driver.go
runtimevar/runtimevar.go
secrets/driver/driver.go
secrets/secrets.go

Using the same content as was in the package godoc with minimal formatting changes.
Updates #1469

internal/website: add concept guide for escape hatches

---

internal/cmd/gocdk/apply.go
internal/cmd/gocdk/serve.go

Prevents serve from prompting user for unset Terraform variables. The user should create .tfvars files or set environment variables for serve.
Updates #1821

internal/cmd/gocdk: add apply -input flag

---

internal/testing/runchecks.sh

Turns out `gofmt .` operates on the current directory plus all recursive subdirectories by default!

travis: simplify gofmt check

---

internal/testing/runchecks.sh

Fixes #2155.
Skip tests on Windows for a couple of internal modules.
* `internal/contributebot` will never run on Windows.
* `internal/gatherexamples` will never run on Windows.
Ideally this would be data-driven from `allmodules` instead of naming modules to skip explicitly; added a TODO for that.

travis: skip a couple of module tests on windows

---

internal/testing/runchecks.sh

Currently we send `codecov` results for the core module, then the core module + the next module, then 3 modules, ... etc.

travis: remove coverage.out file so it doesn't get resent

---

internal/docstore/dynamodocstore/benchmark_test.go

See which is faster if you want to retrieve N items with their
previous values: N calls to PutItem, or a call to BatchGetItem
followed by a call to TransactWriteItems.

dynamodocstore: benchmark PutItem and TransactWriteItem

---

internal/docstore/driver/codec.go
internal/docstore/driver/codec_test.go
internal/docstore/driver/document.go
internal/docstore/dynamodocstore/query.go

Add support for tags with keys "docstore".
Support "-" to mean omit field, and "omitempty" to mean omit the field
if the value is empty (using the same code as in encoding/json).

docstore: support struct tags

---

internal/cmd/gocdk/demo_test.go
internal/cmd/gocdk/serve.go
internal/cmd/gocdk/serve_test.go

Fixes #2155.
On Windows, the executable must end with `.EXE`.

gocdk: fix executable path for windows by adding .EXE suffix

---

internal/cmd/gocdk/apply_test.go
internal/cmd/gocdk/biome_add_test.go
internal/cmd/gocdk/demo.go
internal/cmd/gocdk/init.go
internal/cmd/gocdk/init_test.go

This provides a more realistic test for most use cases. The old helper just creates an empty directory with a `go.mod`, this one creates a real GoCDK project using `gocdk init`. It also saves some boilerplate to create the `pctx`.

internal/gocdk: add a newTestProject helper and use it

---

internal/testing/test-summary/test-summary.go

Without this change, when the build fails we get a very funky error from the summarizer (essentially a JSON parsing error). This PR makes it more intelligible.

testing: fix error reporting when the build fails

---

internal/testing/test-summary/test-summary.go

Following the discussion in #2171 
Fails/skips reported per test. Passes only reported for whole packages. This seems like a nice compromise between verbosity and utility. For more verboseness we always have the `-verbose` flag.
I've refactored the code a bit, and removed the `prevPkg` logic because it seems unnecessary now and it becomes more tricky to maintain when we only print pass for packages.
Sample output with `-progress` with no failures:
```
skip gocloud.dev (0.00s)
pass gocloud.dev/aws (0.00s)
pass gocloud.dev/gcerrors (0.00s)
pass gocloud.dev/health (0.00s)
pass gocloud.dev/health/sqlhealth (0.00s)
pass gocloud.dev/internal/batcher (0.00s)
pass gocloud.dev/internal/docstore/internal/fields (0.00s)
pass gocloud.dev/aws/awscloud (0.00s)
skip gocloud.dev/aws/rds (0.00s)
skip …
```

testing: -progress only reports 'pass' for packages

---

internal/testing/runchecks.sh

Forgot to remove this when I copied it to the loop above.

internal/travis: remove double check for go mod tidy at root

---

internal/cmd/gocdk/deploy.go

**Reminder:** Don't merge until after freeze.

internal/cmd/gocdk: fix argument length validation for deploy

---

internal/testing/runchecks.sh

internal/travis: append to the root-level coverage.out, not a local one

---

pubsub/kafkapubsub/localkafka.sh

Fixes #2185.
Before: 
```
$ cd pubsub/kafkapubsub
$ go test
PASS
ok  	gocloud.dev/pubsub/kafkapubsub	53.279s
```
After: 
```
$ cd pubsub/kafkapubsub
$ go test
PASS
ok  	gocloud.dev/pubsub/kafkapubsub	14.385s
```

pubsub/kafkapubsub/tests: make local kafka daemon rebalance faster, speeding up tests

---

internal/cmd/gocdk/apply.go
internal/cmd/gocdk/apply_test.go
internal/cmd/gocdk/biome.go
internal/cmd/gocdk/biome_add.go
internal/cmd/gocdk/biome_test.go
internal/cmd/gocdk/build.go
internal/cmd/gocdk/demo.go
internal/cmd/gocdk/demo_test.go
internal/cmd/gocdk/init_test.go
internal/cmd/gocdk/launch.go
internal/cmd/gocdk/main.go
internal/cmd/gocdk/main_test.go
internal/cmd/gocdk/serve.go
internal/cmd/gocdk/serve_test.go

Fixes #2210.
I started fixing #2210 (about "demo add" happening even when you're not in the project directory) and kind of went down a rabbit hole:
* I ended up modifying `findModuleRoot` to do the check for whether we're in a Go CDK directory, since we pretty much want this everywhere. I also renamed it to `ModuleRoot` on `processContext` since we always call it with `pctx.workdir`.
* I also renamed `findBiomeDir()` to `biomeDir()` and added `biomeRootDir()`. The `find` seems unnecessary since it's just constructing the path, not finding anything.
* I got rid of the `newTestModule` helper in favor of using `newTestProject`, which uses `gocdk init` to create a Go CDK project. This simplified a few tests where we were having to create `biomes` files etc. manually. In particular, …

internal/gocdk: consolidate some helpers && verify project root dir

---

internal/docstore/docstore.go
internal/docstore/docstore_test.go
internal/docstore/driver/codec.go
internal/docstore/driver/codec_test.go
internal/docstore/driver/driver.go
internal/docstore/drivertest/drivertest.go
internal/docstore/dynamodocstore/dynamo.go
internal/docstore/memdocstore/mem.go
internal/docstore/mongodocstore/codec.go
internal/docstore/mongodocstore/mongo.go

- Fix bug in driver codec where byte arrays are mistakenly encoded as byte slices.
- Distinguish between encoded and unencoded document IDs.
Also, remove driver code for len(mods) == 0 because that can't happen.
And some other minor changes.

mongodocstore: be more precise about encoding keys

---

internal/testing/alldeps
internal/website/data/examples.json
pubsub/natspubsub/example_test.go
pubsub/natspubsub/go.mod
pubsub/natspubsub/go.sum
pubsub/natspubsub/nats.go
pubsub/natspubsub/nats_test.go

Fixes #1556.
NATS also renamed their repo, so I had to update the `import` paths. Strangely, they chose a repo name that ends with `.go`.

pubsub/natspubsub: upgrade deps and enable previously-flaky test

---

.travis.yml
internal/releasehelper/releasehelper_test.go

Fix releasehelper test to be OS-agnostic w.r.t. path separators
Fixes #2264

releasehelper: fix test to be OS-agnostic

---

internal/cmd/gocdk/main_test.go

The `go 1.11` test failed :-(.

internal/gocdk: avoid bytes.ReplaceAll (1.12 only); fix test on Windows

---

internal/cmd/gocdk/main.go
internal/cmd/gocdk/main_test.go

1. We emit a different error if you're not in the right directory depending on `GO111MODULE` and what version of Go you're using; the exit "exit code 1" is not useful so I just trimmed the error message.
2. I tried to fix Windows in a previous PR but scrubbed using the `\', it should always be `/` so the replay file works on all platforms.

internal/gocdk: fix flaky record/replay tests

---

internal/testing/check_api_change.sh
internal/testing/gomodcleanup.sh
internal/testing/listdeps.sh
internal/testing/runchecks.sh
internal/website/gatherexamples/run.sh

This PR teaches all our shell scripts that procses allmodules to ignore
any additional whitespace-separated fields.
The next step will be to add special purpose fields for selective
tagging -- #2284
Updates #2111

testing: Add option to have extra fields in allmodules

---

allmodules
internal/releasehelper/releasehelper.go

This command runs 'git tag' to set a tag on all released modules. For
this purpose we start marking modules in allmodule as "released" or not.
Fixes #2284
Fixes #2111

release: add 'tag' command to releashelper

---

internal/docstore/driver/util.go
internal/docstore/firedocstore/fs.go
internal/docstore/memdocstore/mem.go
internal/docstore/memdocstore/urls.go

This does everything but dynamo, which is forthcoming.
See #2133.

docstore: add option to limit outstanding RPCs for action lists

---

internal/docstore/driver/util.go
internal/docstore/dynamodocstore/dynamo.go
internal/docstore/dynamodocstore/testdata/TestConformance/UnorderedActions.replay
internal/docstore/dynamodocstore/testdata/TestConformance/Update.replay
internal/docstore/dynamodocstore/testdata/TestConformance/UpdateQuery.replay

Fixes #2133.
Also, rewrite handling of actions. Two reasons:
- Factor out common code between transactional and non-transactional
execution.
- Pick all random values (new partition keys and revisions)
deterministically, before starting goroutines. This makes replay
work. Even though the random sequence is the same on every replay,
if random values are picked in goroutines, then different actions
may end up with different values, which means that different
requests could be created on each run.

dynamodocstore: add RPC throttling

---

internal/website/config.toml
internal/website/content/concepts/_index.md
internal/website/content/howto/_index.md
internal/website/content/news/_index.md
internal/website/content/news/wire-beta.md
internal/website/content/ref/_index.md
internal/website/content/tutorials/_index.md
internal/website/layouts/news/li.html
internal/website/layouts/news/list.html
internal/website/layouts/news/single.html
internal/website/static/css/style.css

Not visible in end site, but can be previewed locally by enabling drafts.
Creates a separate RSS feed for news content.
/cc @vangent @eliben FYI

internal/website: add draft news section

---

internal/cmd/gocdk/internal/probe/probe.go
internal/cmd/gocdk/internal/probe/probe_test.go
internal/cmd/gocdk/launch.go
internal/cmd/gocdk/serve.go
internal/cmd/gocdk/serve_test.go
internal/website/content/internal/cmd/gocdk/internal/probe/_index.md

Needed for launchers to be in a separate package.
Updates #2046

internal/cmd/gocdk: factor out WaitForHealthy to a separate package

---

internal/cmd/gocdk/init.go
internal/cmd/gocdk/init_test.go

internal/cmd/gocdk: infer module path if multiple GOPATH entries exist

---

internal/docstore/mongodocstore/cosmos_test.go
internal/docstore/mongodocstore/mongo_test.go
internal/docstore/mongodocstore/testdata/README
pubsub/azuresb/testdata/README

To enable the test, pass the -cosmos flag to `go test` with a connection string.
Fixes #2088.

mongodocstore: add cosmos test

---

docstore/memdocstore/mem_test.go
docstore/memdocstore/urls.go
docstore/memdocstore/urls_test.go

Mimic what mempubsub does: URLs have collection names, which are
remembered in the URLOpener.

memdocstore: give collections names in URLs

---

mysql/cloudmysql/cloudmysql.go
mysql/cloudmysql/cloudmysql_test.go
mysql/cloudmysql/example_test.go
samples/guestbook/inject_gcp.go
samples/guestbook/wire_gen.go

This package didn't previously have a URLOpener, so it adds one. Updated
guestbook injection to match new URLOpener usage.
Updates #1175

mysql/cloudmysql: substitute Open for URLOpener BREAKING_CHANGE_OK

---

.vscode/tasks.json

End-effect: Ctrl-Shift-T/Cmd-Shift-T runs all the project tests in VSCode.

.vscode: use runchecks.sh as default test action

---

azure/azuredb/azuredb.go
mysql/azuremysql/azuremysql.go
mysql/azuremysql/azuremysql_test.go
mysql/azuremysql/main.tf

While I was here, I overhauled azuredb to match the rds package.
This keeps the openers more consistent in their operation.
This does not require changes to Guestbook, since Guestbook uses
local SQL for Azure.
Updates #1175

mysql/azuremysql: substitute URLOpener for Open BREAKING_CHANGE_OK

---

internal/website/content/howto/secrets/_index.md
internal/website/content/howto/secrets/crypt.md
internal/website/content/howto/secrets/open-keeper.md
internal/website/data/examples.json
secrets/awskms/example_test.go
secrets/example_test.go
secrets/gcpkms/example_test.go
secrets/localsecrets/example_test.go
secrets/vault/example_test.go

Moved prose examples into godoc examples. Kept runtimevar page draft, since there is no runtimevar guide to point to.
Fixes #2363
/cc @cnguyen83 for doc review

internal/website: publish secrets how-to guide

---

internal/testing/prereleasechecks.sh

Leftover from #2137 and #2138. Tests work now, but the failure messages were still there.

internal/testing: remove remaining 'KNOWN FAILURE' messages

---

blob/drivertest/drivertest.go

Updates #2400.
I found these by adding a finalizer for `blob.Bucket` in `blob.NewBucket`. It seemed to find missing `Close`s in `drivertest`, but not in examples or package-level tests; I suspect the GC only cleans up local variables in sub-tests or something like that.
I tried the same for `runtimevar.Variable` and `pubsub.Topic/Subscription` with less success; both of those create references (e.g., `runtimevar.Variable` starts a goroutine, `pubsub` creates batchers) that make it harder for the garbage collector to notice that it's OK to cleanup right away.

blob/drivertests: fix some missed calls to bucket.Close

---

blob/azureblob/azureblob_test.go
blob/blob_test.go
blob/fileblob/fileblob_test.go
blob/gcsblob/gcsblob_test.go
blob/memblob/memblob_test.go
blob/s3blob/s3blob_test.go
docstore/docstore_test.go
docstore/firedocstore/urls_test.go
docstore/memdocstore/urls_test.go
docstore/mongodocstore/urls_test.go
pubsub/kafkapubsub/kafka_test.go
pubsub/natspubsub/nats_test.go
runtimevar/blobvar/blobvar_test.go
runtimevar/example_openvariable_test.go
runtimevar/gcpruntimeconfig/gcpruntimeconfig_test.go
runtimevar/oc_test.go
secrets/awskms/testdata/TestConformance/TestDecryptMalformedError.replay
secrets/drivertest/drivertest.go

Fixes #2400.
I found a bunch more places where we were missing `Close`/`Shutdown` calls by just printing a refcount and running the tests.
Note: I also re-recorded a `awskms` golden file that was printing an error; I suspect the test passes anyway because it's expecting an error, but it's not the "right" error.

all: add missing calls to Close/Shutdown where needed

---

docstore/doc.go
docstore/driver/driver.go
docstore/dynamodocstore/dynamo.go
docstore/firedocstore/fs.go
docstore/memdocstore/mem.go
docstore/mongodocstore/mongo.go

The constant is actually called "docstore.DefaultRevisionField".

docstore: fix references to docstore.RevisionField

---

internal/cmd/gocdk/build.go
internal/cmd/gocdk/build_test.go

Prevents potential bugs where a tag may be added in a surprising context.

internal/cmd/gocdk: validate implicit image name

---

internal/cmd/gocdk/go.mod
internal/cmd/gocdk/internal/launcher/ecs.go
internal/cmd/gocdk/internal/launcher/ecs_test.go
internal/cmd/gocdk/launch.go

This adds "ecs" as a launcher type recognized by `gocdk launch`, but doesn't add it as an option to `gocdk biome add` yet. The launcher pushes an image to ECR then starts a task on an EC2-based ECS cluster. I have tested this manually. The logic mostly follows the same steps that the Cloud Run launcher does.
The launch process is effectively everything needed, but there is a notable TODO to set up Docker auth for the ECR repository. This will be addressed in a subsequent PR.
Updates #2301

internal/cmd/gocdk: add ECS launcher

---

docstore/driver/codec.go
docstore/driver/document.go
docstore/internal/fields/fields.go
docstore/internal/fields/fields_test.go

This is something we would want if this package were ever made available for general use.
I did it so we could easily experiment with having docstore do case-sensitive field matching.

docstore/internal/fields: support both case-sensitive and case-insensitive matching

---

pubsub/pubsub_test.go

Fixes #2395.
This test is flaky because it captures the number of running goroutines and then expects to return to that value; sometimes there are goroutines running that have nothing to do with us (maybe GC?). I added some `Printf`s and saw:
Usually:
```
START: 3
NOW: 5
NOW: 3
```
but sometimes:
```
START: 3
NOW: 491
NOW: 3
```
I think the test flakes if you happen to get that `491` while the test is starting.
I don't think the test is adding much value, so I'm just going to remove it.

pubsub: remove flaky test

---

internal/cmd/gocdk/build.go
internal/cmd/gocdk/build_test.go
internal/cmd/gocdk/deploy.go
internal/cmd/gocdk/internal/docker/docker.go

This gives an easy-to-reference, immutable tag for each invocation of `gocdk build` (whereas before `gocdk build` would by default override the "latest" tag). This means that `gocdk build --list` will finally yield meaningful output out-of-the-box.
I've updated the deploy command to send the generated tag to launch. I am hoping this reduces flakiness with Cloud Run, since it should be receiving a new image reference each time, making failures more obvious.
Fixes #2350

internal/cmd/gocdk: generate unique tag per build

---

docstore/memdocstore/mem.go
docstore/memdocstore/mem_test.go
docstore/memdocstore/urls.go
docstore/memdocstore/urls_test.go

Add a Filename option that will load a collection from a filename if it exists, and save it
when the collection is closed.
Fixes #1760.

memdocstore: support saving to a file

---

pubsub/kafkapubsub/kafka_test.go

Still raced, need to verify both goroutines are closed before exiting the test, since exiting the test shuts down the subscription.

pubsub/kafkapubsub: one more fix to TestMultiplePartionsWithRebalancing

---

.gitignore
internal/testing/prereleasechecks.sh
internal/testing/runchecks.sh

Updates #2481.
This refactors `runchecks.sh` to:
1. run Go tests for all modules, then `go mod tidy` for all modules, then `wire diff`. I think this is clearer to read both in the bash code and in the output.
2. build the arguments for `go test` in a bash array so that we can just call it from one place (previously we had one call for coverage, another for non-coverage, with mostly the same command line).
3. add `-v` to `go test` for `pubsub/kafkapubsub`, which seems to time out a lot and needs more investigation.
4. built `test-summary` once instead of multiple `go run` calls.
5. got rid of the use of "pushd/popd" in a couple of places.
6. fixed a `shellcheck` warning about unescaped `\n` in `prereleasechecks.sh`.

internal/travis: various runchecks improvements

---

pubsub/drivertest/drivertest.go
pubsub/kafkapubsub/kafka_test.go

Updates #2481.
This PR makes sure that the `ctx` we pass to `Receive` in tests always has a 30 second timeout.
It also makes sure that `kafkapubsub`'s `TestMultiplePartionsWithRebalancing` doesn't hang when the `ctx` times out.

pubsub/tests: ensure tests fail faster by using a ctx with timeout

---

docstore/mongodocstore/mongo.go
docstore/mongodocstore/mongo_test.go

docstore/mongodocstore: clarify lowercase takes effect on all fields

---

samples/gocdk-runtimevar/main.go
samples/gocdk-runtimevar/main_test.go
samples/gocdk-runtimevar/runtimevar.ct

Also, stop the "watch" command when the context is canceled.
This test was complicated by the fact that the "watch" subcommand
needs to run concurrently with other test actions.

sample/runtimevar: add test

---

internal/website/content/howto/blob/data.md
internal/website/content/howto/blob/open-bucket.md
internal/website/content/howto/pubsub/publish.md
internal/website/content/howto/pubsub/subscribe.md
internal/website/content/howto/runtimevar/_index.md
internal/website/content/howto/secrets/crypt.md
internal/website/content/howto/secrets/open-keeper.md
internal/website/content/howto/secrets/runtimevar.md
internal/website/content/howto/sql/_index.md
internal/website/layouts/_default/list.html
internal/website/layouts/_default/single.html
internal/website/layouts/howto/list.html
internal/website/layouts/partials/page-toc.html
internal/website/static/css/style.css

This is enabled per-page using `toc: true` in the front matter. It will float a sidebar to the right on desktop and show the list inline with content after the title on tablet and smaller screens.

internal/website: add automatic table of contents

---

samples/gocdk-runtimevar/main_test.go

Fixes #2511 
I just removed the code that doesn't compile on Go 1.11 and it still seems to work fine :-).

samples/gocdk-runtimevar: fix broken build on go 1.11

---

internal/cmd/gocdk/internal/docker/docker.go
internal/cmd/gocdk/internal/launcher/ecs.go

These authorization tokens are short-lived, so issuing a `docker login` is crucial for a smooth experience.
Updates #2301

internal/cmd/gocdk/internal/launcher: authenticate to ECR during launch

---

samples/gocdk-pubsub/main.go

The race came from the order in which output of the receive command
was sent to stdout vs. stderr.
Fix by writing all output to stdout.
This is just a sample: it's not like we have to write a perfectly
ergonomic CLI.
Fixes #2496.

samples/gocdk-pubsub: fix race in test

---

internal/cmd/gocdk/internal/prompt/prompt.go
internal/cmd/gocdk/testdata/biome.ct
internal/cmd/gocdk/testdata/resource.ct
internal/testing/cmdtest/cmdtest.go
internal/testing/cmdtest/testdata/good-without-output/good-without-output.ct
internal/testing/cmdtest/testdata/good/good.ct

When I created these CLI tests, there was no way to run commands that required input from the user. @jba added support for doing so; thus, this PR is now fleshing out the CLI tests with a bunch of commands that require user input.
I made one change to `internal/testing/cmdtest`, which is to have its `echo` and `echof` commands (which write a string to stdout or to a file) replace a literal `\n` in the input with an actual `\n` character. This allows a test to write a file with contents something like "foo\nbar", which you can use as stdin in order to answer two prompts (the first with `foo`, the second with `bar`.
In a bunch of cases, the file piped to stdin is empty; since `echof` adds a `\n` to the input, this simulates the user hitting Enter once, which works for commands that require …

internal/gocdk: add CLI tests for commands that require stdin

---

internal/cmd/gocdk/main.go
internal/cmd/gocdk/testdata/biome.ct
internal/cmd/gocdk/testdata/build.ct
internal/cmd/gocdk/testdata/demo.ct
internal/cmd/gocdk/testdata/deploy.ct
internal/cmd/gocdk/testdata/init.ct
internal/cmd/gocdk/testdata/resource.ct
internal/cmd/gocdk/testdata/serve.ct

Fixes #2544.
Instead of exec'ing `go list` to find the root module, just start at the current directory and look for a `go.mod` file and a `biomes` directory. If not found, move up one.
This reduces the time needed for CLI tests from ~1 minute to ~2 seconds.

internal/gocdk: don't use 'go list' to find the project root dir

---

internal/cmd/gocdk/serve.go
internal/cmd/gocdk/serve_test.go

Fixes #2572.
Fixes #1954.
Don't call `wire` as part of building for "gocdk build".
Rationale: It seems pretty unlikely that Go CDK users will be using `wire`. Even if they do, they will need to make sure to call `wire` before they `gocdk build` or `gocdk deploy`; doing it for them as part of `gocdk serve` isn't necessarily saving much.
Also, IMHO it might be surprising to have generated code being modified on the fly by a background process.

internal/gocdk: remove explicit wire support from serve

---

internal/cmd/gocdk/build.go
internal/cmd/gocdk/deploy.go

We had more or less the same code to generate a tag in both `build` and `deploy`. This PR changes the `build` function to return the actual tags it uses, so that `deploy` can use them.
I changed the order of the default image refs so that the most specific one (the snapshot tag) would first and be used by `deploy`.

internal/gocdk: reduce duplicate code in "deploy" for generate image refs

---

internal/website/content/howto/docstore/_index.md

Fixes #2562 
I added the Cosmos section under the MongoDB section since it uses the mongodocstore package.

internal/website: add Cosmos DB to docstore how-to

---

internal/website/content/ref/secrets.md

It was missing from the docs, however, the implementation already exists (which is great!).

internal/website: add Azure KeyVault to provider list

---

internal/cmd/gocdk/main.go
internal/cmd/gocdk/testdata/help.ct

Fixes #2304.
Last one! This is for the top-level / root command, which is shown for `gocdk` or `gocdk help`.

internal/gocdk: update Help for the root command

---

internal/website/content/howto/pubsub/publish.md
internal/website/content/howto/pubsub/subscribe.md

Had to reorder things a big because of the way this howto was originally structured. If this looks good, I'll update the subscribe page similarly

docs: make pubsub howto consistent with the new howto template

---

.travis.yml
internal/cmd/gocdk/biome.go
internal/cmd/gocdk/biome_test.go
internal/cmd/gocdk/deploy.go
internal/cmd/gocdk/main_test.go
internal/cmd/gocdk/serve.go
internal/cmd/gocdk/testdata/biome-apply.ct

Fixes #1821.
Previous to this PR, during "biome apply" we would run `terraform init`, then `terraform apply`, and dump all of the stdout/stderr output from those commands to the terminal. That's a lot of confusing text.
This PR changes "biome apply" to:
* Run "terraform init", then "terraform plan" (which generates a "plan" file with all the needed changes), then "terraform apply" on the generated plan. The result is basically the same as before, but splits the plan + apply into separate steps so that we can prompt for approval in between, and so that we can be more judicious about what to output for the user to see. Terraform won't prompt in `plan`, and also won't prompt in `apply` if you give it an explicit plan.
* Capture the output from each call to `terraform`, and only sometimes …

internal/gocdk: capture output from Terraform during "biome apply"

---

docstore/mongodocstore/go.sum
go.mod
go.sum
internal/cmd/gocdk/go.sum
internal/contributebot/go.sum
internal/testing/alldeps
internal/testing/setup/setup.go
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.sum
runtimevar/etcdvar/go.sum
samples/go.sum
secrets/hashivault/go.sum

I moved both the gRPC and HTTP record/replay proxies to a new repo,
github.com/google/go-replayers.
I also changed their API somewhat, to make it cleaner and reduce
the dependence on Google-specific API packages.
This PR switches the Go CDK to use the gRPC record-replay proxy.
I had to rewrite the setup code a bit to accommodate the new API.
I also unexported a couple of functions that were never called outside
the package.

internal/testing/setup: use google/go-replayers for gRPC

---

internal/cmd/gocdk/biome.go
internal/cmd/gocdk/deploy.go
internal/cmd/gocdk/serve.go

Eliminates possibility of nil pointer panic when accessing apply options. I also slightly tweaked the fields such that the zero value is the same as the default flags, so that functions that call with the zero options value will provide the same inputs.
Fixes #2607

internal/cmd/gocdk: pass around biomeApplyOptions by value

---

internal/cmd/gocdk/deploy.go

A shadowed variable caused the build to occur, but the image reference to be ignored by the rest of the deploy process. The error would look like:
```
Error: gocdk deploy: cloud run launch: docker tag: docker push: Error parsing reference: "" is not a valid repository/tag: invalid reference format
```
@vangent for review

internal/cmd/gocdk: fix crash on deploying newly built image

---

docstore/awsdynamodb/dynamo.go
docstore/doc.go
docstore/gcpfirestore/fs.go
docstore/mongodocstore/mongo.go

This makes the introduction more consistent with other APIs as we reshuffle the content between godoc and how-tos.

docstore/godoc: Move service references from package to driver godoc.

---

blob/blob.go
internal/website/content/howto/blob/_index.md

Updates #2387
Add more details to "Opening" how-to section.

blob/docs: Migrate content from godoc to how-to.

---

internal/cmd/gocdk/build.go

internal/gocdk: run go build as part of gocdk build

---

internal/website/content/howto/blob/_index.md
internal/website/content/howto/docstore/_index.md
internal/website/content/howto/pubsub/publish.md
internal/website/content/howto/pubsub/subscribe.md
internal/website/content/howto/runtimevar/_index.md
internal/website/content/howto/secrets/_index.md

We were incomplete and inconsistent about our descriptions of how URLOpeners authenticate to GCP and AWS.

internal/website/howto: improve and make consistent description of auth for GCP and AWS

---

internal/cmd/gocdk/biome.go
internal/cmd/gocdk/deploy.go
internal/cmd/gocdk/serve.go
internal/cmd/gocdk/testdata/biome-apply.ct
internal/cmd/gocdk/testdata/biome-cleanup.ct
internal/cmd/gocdk/testdata/deploy-help.ct
internal/cmd/gocdk/testdata/serve-help.ct

This is needed because both `serve` and `deploy` can call `biome apply`, which normally hides the Terraform output if there are changes and says "re-run with --verbose to see details" or something like that.

internal/gocdk: add verbose options to serve+deploy

---

internal/website/content/howto/runtimevar/_index.md
internal/website/content/howto/secrets/_index.md
runtimevar/runtimevar.go
secrets/localsecrets/localsecrets.go
secrets/secrets.go

Updates #2387.
Add examples to "Opening" how-to sections.

docs: Migrate runtimevar and secrets intro from godoc to how-to.

---

docstore/doc.go
docstore/docstore.go
docstore/memdocstore/mem.go
internal/website/content/howto/docstore/_index.md
internal/website/content/howto/pubsub/_index.md
internal/website/content/howto/pubsub/publish.md
internal/website/content/howto/pubsub/subscribe.md
internal/website/data/examples.json
pubsub/example_test.go
pubsub/pubsub.go

Updates #2387.
Add examples to "Opening" how-to sections.
I kept some of the intro text in docstore godoc (now under Collection section) because it defines concepts that the rest of the godoc relies on. I plan to migrate this together with other sections in a separate PR.

docs: Migrate docstore and pubsub intro from godoc to how-to

---

docstore/mongodocstore/awsdocdb/main.tf
docstore/mongodocstore/awsdocdb/outputs.tf
docstore/mongodocstore/awsdocdb/variables.tf
docstore/mongodocstore/docdb_test.go

Also added a `awsdocdb` directory containing terraform files to provision the resources needed for running the tests.
Fixes #2294

docstore/mongodocstore: add a conformance test for Amazon DocumentDB

---

pubsub/azuresb/azuresb.go
pubsub/drivertest/drivertest.go

Fixes #2638 (shows the stack trace of the data race).
Previously to this PR, we created a goroutine and called `azuresb.Receive`, which can receive multiple messages. To do so, it creates 2 goroutines. It appears that those goroutines continue running even after `Receive` returns, sometimes in our handler code (I debugged this by adding a long `time.Sleep` inside our handler), sometimes not.
To avoid this, this PR simplifies things significantly by avoiding our goroutine entirely, and calling `azuresb.ReceiveOne` in a loop until enough time has passed or we have enough messages.
I tried to benchmark the difference in performance (if any), but it was difficult because the BEFORE benchmark usually crashed (in the azuresb code, probably due to a side effect of the race) :-|.
```
panic: …
```

pubsub/azuresb: use ReceiveOne in a loop instead of Receive to avoid data race

---

mysql/mysql.go

This commit removes the `mysql://` prefix before passing the DSN to the
MySQL driver for Go. The latter requires the DSN in a format like:
```
[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
```
as described in
https://github.com/go-sql-driver/mysql/blob/master/README.md#dsn-data-source-name.
It doesn't accept a `mysql://` prefix and, when used, will not parse the
DSN correctly.
Fixes #2644

mysql: remove mysql:// prefix when passing DSN to driver

---

internal/website/data/examples.json
pubsub/awssnssqs/awssnssqs.go
pubsub/awssnssqs/awssnssqs_test.go
pubsub/awssnssqs/example_test.go

pubsub/awssnssqs: fix docs/examples/tests to show SNS ARN in path, not hostname

---

internal/website/content/ref/blob.md
internal/website/content/ref/docstore.md
internal/website/content/ref/mysql.md
internal/website/content/ref/postgres.md
internal/website/content/ref/pubsub.md
internal/website/content/ref/runtimevar.md
internal/website/content/ref/secrets.md
internal/website/content/ref/server.md

Noticed we were missing a reference section for docstore, and fixed some inconsistencies along the way.

internal/website: add reference section for docstore; cleanup

---

docstore/mongodocstore/go.sum
go.mod
go.sum
internal/cmd/gocdk/go.mod
internal/cmd/gocdk/go.sum
internal/contributebot/go.sum
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.sum
runtimevar/etcdvar/go.sum
samples/go.sum
secrets/hashivault/go.sum

The older version of xerrors does not build with Go 1.13rc1.
xerrors issue fixed in the new version: https://golang.org/issues/32246
I tested this change by running `go test ./...` with both Go 1.12.9 and
Go 1.13rc1.

all: Update golang.org/x/xerrors for Go 1.13rc1

---

docstore/mongodocstore/go.mod
internal/contributebot/go.mod
pubsub/kafkapubsub/go.mod
pubsub/natspubsub/go.mod
pubsub/rabbitpubsub/go.mod
runtimevar/etcdvar/go.mod
samples/go.mod
secrets/hashivault/go.mod

Travis is expected to fail.
Doing a release due to #2666, to make sure we work with `go 1.13`.

release: prepare for release v0.17.0

---

blob/blob.go
blob/blob_writer_test.go

Fixes #2670.
The test fails without the change to `blob.go`.

blob: Fix n return value from blob.Writer when content sniffing is active

---

pubsub/awssnssqs/awssnssqs.go

pubsub/awssnssqs: drop leading slash from ARNs in SNS URLs

---

mysql/mysql.go

yueeong [pointed out](https://github.com/google/go-cloud/commit/a5f6c05207b2d477d31267b24edd23331ac6f228#commitcomment-35353748) that this use of `TrimLeft` should be `TrimPrefix`. `TrimLeft` trims all character in the "cutset" of its second argument, so `TrimLeft(s, "mysql://")` would remove any leading `m`, `y`, `s`, etc.. That's not what we want.

mysql: use TrimPrefix instead of TrimLeft

---

runtimevar/gcpruntimeconfig/gcpruntimeconfig.go
runtimevar/gcpruntimeconfig/gcpruntimeconfig_test.go

Use non-deprecated gRPC APIs in runtimevar/gcpruntimeconfig package.

runtimevar/gcpruntimeconfig: Use non-deprecated gRPC APIs

---

blob/gcsblob/gcsblob.go

Use non-deprecated gcs blob storage APIs

blob/gcsblob: Use non-deprecated gcs blob storage APIs

---

pubsub/azuresb/azuresb.go

Fix range variable captured by func literal in azuresb

pubsub/azuresb: Fix range variable captured by func literal

---

docstore/mongodocstore/cosmos_test.go
docstore/mongodocstore/go.sum

This avoids keeping a provisioned empty database on Cosmos.

docstore/mongodocstore: drop the db for Cosmos after testing

---

pubsub/gcppubsub/gcppubsub.go

Fixes #2694
Adds support for connecting to GCP pubsub emulator when default conn is used.

pubsub/gcppubsub: add support for pubsub emulator

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

Fixes #2700.
When fileblob gets a URL like `file://`, it ends up using the relative path "." and getting things wrong after that. We should convert "." into an absolute path using `filepath.Abs`.

blob/fileblob: Handle empty filepath better

---

internal/website/content/howto/docstore/_index.md

Fixes a broken link out to Firestore.

docstore/docs: Fix broken link to Firestore.

---

blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go

Fixes #2716
Updated 12/24/19 to reflect changes in implementation:
The current go-cloud azureblob implementation always targets "blob.core.windows.net" when attempting to open a bucket, making USGovernment, China, and German cloud buckets inaccessible. 
With this addition, users can specify the Azure Cloud Environment they would like to target by setting  the AZURE_STORAGE_DOMAIN environment variable to a value like "blob.core.govcloudapi.net", "blob.core.chinacloudapi.cn", etc. allowing them to access the different Azure blob storage endpoints for each of these clouds. 
If users leave the AZURE_STORAGE_DOMAIN variable unset, the bucket opener will target "blob.core.windows.net" by default, which is the public domain that most users are likely already using. Any changes made by this …

blob/azureblob: Add support for specifying Azure Cloud Environment 

---

blob/blob.go

Allows the caller to detect the error type instead of returning a
formatted string

blob: Let readFromWriteTo return the original err

---

server/requestlog/requestlog.go

responseStats should support connection hijacking if underlying response
writer does.
Signed-off-by: Alex Snast <alexsn@fb.com>

server/requestlog: responseStats should implement http.Hijacker

---

gcp/gcp.go

Currently, an anonymous GCP client has to be constructed manually via
```
client := &gcp.HTTPClient{Client: http.Client{Transport: gcp.DefaultTransport()}}
```
While this works, it is not very intuitive. This PR adds a simple
constructor for an anonymous client, making sure this capability is
visible in the godocs and easy to discover.

GCP: Add NewAnonymousHTTPClient

---

internal/oc/metrics.go

opencensus provides similar functionality to `mustKey` so use it instead.

oc: use tag.MustNewKey on tag key creation

---

.travis.yml
docstore/mongodocstore/go.mod
docstore/mongodocstore/go.sum
go.mod
go.sum
internal/testing/runchecks.sh
internal/website/go.mod
internal/website/go.sum
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.mod
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.mod
pubsub/rabbitpubsub/go.sum
runtimevar/etcdvar/go.mod
runtimevar/etcdvar/go.sum
samples/go.sum
samples/gocdk-runtimevar/main_test.go
samples/gocdk-runtimevar/runtimevar.ct
secrets/hashivault/go.sum

I had to drop some stuff from the `gocdk-runtimevar` sample; it was racy and got more racy with go 1.14.
I also had to upgrade `go-cmp` due to https://github.com/google/go-cmp/issues/167.

all: drop go 1.11 support and make go 1.14 the current version.

---

blob/gcsblob/gcsblob.go

blob/gcsblob: add comments about required ordering of types for multiple calls to BeforeWrite

---

runtimevar/awsparamstore/awsparamstore.go
runtimevar/awsparamstore/testdata/TestConformance/TestAs/verify_As.replay
runtimevar/awsparamstore/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.replay
runtimevar/awsparamstore/testdata/TestConformance/TestDelete.replay
runtimevar/awsparamstore/testdata/TestConformance/TestInvalidJSON.replay
runtimevar/awsparamstore/testdata/TestConformance/TestJSON.replay
runtimevar/awsparamstore/testdata/TestConformance/TestNonExistentVariable.replay
runtimevar/awsparamstore/testdata/TestConformance/TestString.replay
runtimevar/awsparamstore/testdata/TestConformance/TestUpdate.replay
runtimevar/awsparamstore/testdata/TestConformance/TestUpdateWithErrors.replay

`WithDecryption=true` has no effect if the parameter is not encrypted, so it's safe to just always set it.
Fixes #2764.

runtimevar/awsparamstore: Use WithDecryption=true to decrypt encrypted parameters

---

internal/testing/runchecks.sh

The Windows build was reporting:
`grep: -P supports only unibyte and UTF-8 locales`
and skipping all tests.

internal/testing: replace use of grep -P with piped grep; grep -P is no longer supported on windows

---

pubsub/mempubsub/mem.go

mempubsub.(*subscription).add() which is called on every subscription
for topic updates driver.Message.AsFunc while pubsub.(*Subscription).Receive()
reads its value.
WARNING: DATA RACE
Read at 0x00c0004bb030 by goroutine 134:
gocloud.dev/pubsub.(*Subscription).Receive()
/Users/alexsn/go/pkg/mod/gocloud.dev@v0.19.0/pubsub/pubsub.go:586 +0x935
Previous write at 0x00c0004bb030 by goroutine 114:
gocloud.dev/pubsub/mempubsub.(*subscription).add()
/Users/alexsn/go/pkg/mod/gocloud.dev@v0.19.0/pubsub/mempubsub/mem.go:242 +0xee
gocloud.dev/pubsub/mempubsub.(*topic).SendBatch()
/Users/alexsn/go/pkg/mod/gocloud.dev@v0.19.0/pubsub/mempubsub/mem.go:163 +0x323
gocloud.dev/pubsub.newSendBatcher.func1.1()
/Users/alexsn/go/pkg/mod/gocloud.dev@v0.19.0/pubsub/pubsub.go:309 +0x1c1 …

pubsub/mem: fix race on msg.AsFunc access

---

secrets/azurekeyvault/akv.go

Azure keyvault has multiple regions, as described [here](https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault#resource-endpoints)
This PR updates the regex currently used to detect a valid azure
keyvault region to include:
- Azure US Government: https://<vault-name>.vault.usgovcloudapi.net
- Azure China 21Vianet: https://<vault-name>.vault.azure.cn:443
- Azure Germany: https://.vault.microsoftazure.de:443
See
for …

secrets/azurekeyvault: add support for other azure keyvault regions

---

secrets/azurekeyvault/akv.go

Azure KeyVault's Decrypt operation returns strings in the RawURL encoding of Base64, not the Standard encoding, for example this value obtained today:
`ku7k4JuFKhOdDG68myd3Ton7kkmhv6bBm_Lh5pNgLQo`
This commit updates the KeyVault Decrypt implementation to decode the response using the base64.RawURLEncoding instead of base64.StdEncoding.

secrets/azurekeyvault: Use RawURLEncoding for Azure KeyVault responses

---

internal/website/data/examples.json
pubsub/awssnssqs/example_test.go

remove "http://" from queueURL so we get the correct awssqs://sqs.us-east-... url in the OpenTopic function call.

pubsub/awssnssqs/example_test.go:remove http:// protocol from URL in Example_openSQSTopicFromURL

---

docstore/mongodocstore/mongo.go

Adding an extra space turns these into bulleted lists on godoc.org instead of a single run-on paragraph.

docstore/mongodocstore: fix godoc format

---

docstore/awsdynamodb/dynamo.go
docstore/driver/driver.go
docstore/gcpfirestore/fs.go
docstore/memdocstore/mem.go

Using the internal type in the interface makes it impossible to write external drivers.
Fixes #2779.

doctore: use gcerrors in driver interface

---

pubsub/awssnssqs/awssnssqs.go
pubsub/kafkapubsub/kafka.go

The types are the same, but this is more clear since the driver interface expects a `gcerrors.ErrorCode`, which is the public type.
Updates #2779.

pubsub: use gcerrors instead of internal/gcerr where possible

---

docstore/mongodocstore/go.mod
docstore/mongodocstore/go.sum
go.mod
go.sum
internal/contributebot/go.mod
internal/contributebot/go.sum
pubsub/kafkapubsub/go.mod
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.mod
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.mod
pubsub/rabbitpubsub/go.sum
runtimevar/etcdvar/go.sum
samples/go.mod
samples/go.sum
secrets/hashivault/go.sum

The v0.8.0 version has an incomplete go.mod file which was leading to
ambiguous import errors for consumers.  The missing dependencies have
been fixed in v0.9.0.
No functional changes are included in this version update.
Fixes https://github.com/google/go-cloud/issues/2722

blob/azureblob: update azure-storage-blob-go version

---

blob/gcsblob/gcsblob.go
blob/gcsblob/gcsblob_test.go
blob/gcsblob/iam.go
blob/gcsblob/iam_test.go
go.mod

This enables to use blob.SignURL out-of-the-box by setting the required values, primarily the GoogleAccessID and a PrivateKey—where available—, and a default signing behaviour.
By moving the IAM Credentials API client into the bucket, it's henceforth possible to use it in `bucket.Options.SignBytes()` without any external wrapper.
Previously users ran into `SignURL` working properly with the likes of S3 without doing anything special, and GCS has been the outlier that needed additional work degrading productivity and developer experience.
closes #2653

blob/gcsblob: set defaults for SignURL

---

blob/gcsblob/gcsblob.go

Vanilla GCE is one of the environments without any credential file that can be used to obtain a *GoogleAccessID*. Fortunately an API method exists and has been added to `cloud.google.com/go v0.57` as remedy.

blob/gcsblob: on GCE use the service account's email in SignedURL

---

secrets/localsecrets/localsecrets.go
secrets/localsecrets/localsecrets_test.go

secrets/localsecret: Provide key decoders for URL and Std base64, and use the former for URLs

---

mysql/mysql.go

Add ocsql.TraceOpts to default opener as we do for cloud specific ones.

mysql: add trace options to default mysql opener

---

docstore/mongodocstore/mongo.go

Fixes #2842 
With some extra logging, before this PR the test fails with:
```
PROJECTION [{DocstoreRevision 1} {f 1} {m.b 1} {DocstoreRevision 1}] 
--- FAIL: TestConformance (0.12s)                                                                                                        
--- FAIL: TestConformance/V3 (0.12s)                                                                                                 
--- FAIL: TestConformance/V3/Get (0.05s)                                                                                                                                                                                                                                  
--- FAIL: TestConformance/V3/Get/StdRev (0.05s) …
```

docstore/mongodocstore: don't include revision field projection twice; Mongo 4.4 rejects that

---

.travis.yml
internal/testing/runchecks.sh

all: update to testing with go 1.14 and go 1.15, dropping go 1.13

---

pubsub/benchmark_test.go

These tests aren't usually run, so I guess they got stale at some point. The fake needs to provide stubs for these interface methods.
I removed the "no ack" benchmark because it now prints a warning a gazillion times, which messes up the output.

pubsub: Fix benchmark tests

---

mysql/awsmysql/awsmysql.go
mysql/awsmysql/awsmysql_test.go
mysql/main.tf
mysql/mysql.go
mysql/mysql_test.go

Currently it's not possible to open a mysql instance via URL and when attempted the following error is shows:
URL: mysql://root:root@localhost/testdb
Error: default addr for network 'localhost' unknown
This occurs since mysql.OpenMySQLURL treats a mysql DSN as a URL prefixed with a schema which is incorrect.
In order to fix this I moved the `configFromURL` function I added in https://github.com/google/go-cloud/pull/2831 to mysql package and made it public. In addition I've added a terraform harnest for mysql driver using docker provider.
Fixed https://github.com/google/go-cloud/issues/2856.

mysql: fix DSN parsing from URL

---

blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go
blob/blob.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go
blob/gcsblob/gcsblob.go
blob/gcsblob/gcsblob_test.go
blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

`BeforeSign` is similar to `BeforeRead` and friends allowing users to hook into SignedURL operation. In my case it's needed to set `ContentDisposition` before signing s3blob get request.

blob/all: adding BeforeSign support to SignedURL operation

---

README.md

It linked to the old import path so you got documentation for an old version

all: fix godoc URL

---

pubsub/azuresb/azuresb_test.go

We don't have record/replay for these tests, they only run live with `-record` so I just happened to notice when I tried running everything with `-record` recently.
It looks like Azure's library changed the type of a returned error.

pubsub/azurepubsub: Modify As test for Azure-side change in type of error returned

---

internal/website/content/howto/docstore/_index.md

Docstore's how to guide points to wrong web url (the label is memdocstore, but link destination is mongodocstore). This PR just fix this link issue.

`internal/website`: fix wrong document link

---

pubsub/pubsub.go

When running go test with -race I hit the following splat:
```
WARNING: DATA RACE
Write at 0x00c00048d1e8 by goroutine 68:
gocloud.dev/pubsub.(*Subscription).Receive.func2()
/home/runner/go/pkg/mod/gocloud.dev@v0.20.1-0.20200914152856-6be5a462804a/pubsub/pubsub.go:560 +0x4a4
Previous read at 0x00c00048d1e8 by goroutine 119:
gocloud.dev/pubsub.(*Subscription).Shutdown()
/home/runner/go/pkg/mod/gocloud.dev@v0.20.1-0.20200914152856-6be5a462804a/pubsub/pubsub.go:680 +0x61d
github.com/facebookincubator/symphony/pkg/ev.(*TopicReceiver).Shutdown()
```
The issue occurs as .Shutdown reads `s.err` _after_ releasing the lock.

pubsub: fix data race accessing subscription error

---

pubsub/pubsub.go

Similar to https://github.com/google/go-cloud/pull/2901 but for topic shutdown.

pubsub: fix data race accessing topic error on shutdown

---

pubsub/awssnssqs/awssnssqs.go
pubsub/azuresb/azuresb.go
pubsub/driver/driver.go

Fixes #2897 
Fixes #2899
Fixes #2900
This code is simpler than before; it relies on the concrete type behavior of retrying driver.ReceiveBatch calls as needed, instead of trying to batch up some messages artificially inside ReceiveBatch.
It also fixes a bug introduced in #2891, where a timeout in the call to `ReceiveOne` would cause failures.
I benchmarked this, and it's not noticeably slower than before; the overhead from letting the concrete type retry vs looping inside the driver is minimal. This also lets the concrete type react faster/better with more concurrency (by calling ReceiveBatch concurrently).

pubsub/azuresb: Simplify ReceiveBatch to only return 1 message; fixes error handling

---

internal/website/content/howto/runtimevar/_index.md

Updates #2914.
Also fixes the build, the web page references the etcd examples which are no longer included since it was commented out in `allmodules`.

internal/website: add a notice about dropping etcd support to the HOWTO

---

runtimevar/drivertest/drivertest.go

This just checks for errors and makes sure we always delete the variable when needed (even if the test fails).

runtimevar: improve cleanup in drivertests

---

blob/azureblob/azureblob.go
blob/driver/driver.go

In order to sign URLs we require credentials to be generated.  The previous pull #2873 added support for authentication via MSI in Azure, this makes it so MSI-enabled environments are able to obtain credentials correctly for URL signing.
We tried to add this to the openerFromMSI, but we ran into a chicken-and-egg issue where in order to create the Credentials we needed a service URL, which wasn't being created until the openBucket function.
Happy to make any changes necessary to get this approved!

blob/azureblob: Obtain Credentials from MSI for URL Signing

---

blob/azureblob/azureblob.go
docstore/mongodocstore/go.sum
go.mod
go.sum
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.sum
samples/go.mod
samples/go.sum
secrets/hashivault/go.sum

Update azure-stoage-blob-go to v0.12.0
https://github.com/Azure/azure-storage-blob-go/releases/tag/v0.12.0

blob/azureblob: Update azure-stoage-blob-go to v0.12.0

---

mysql/mysql.go
mysql/mysql_test.go

Allow url host to take the form of `protocol(addr)` (similar to [mysql.ParseDSN](https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L323-L338)).
Fixes #2923.

mysql: parse url host in the form of 'protocol(addr)' (#2923)

---

samples/go.mod
samples/go.sum

Couldn't update this before because `v0.2.0` was broken for Windows. Now fixed by @jba.

samples: update go-cmdtest to latest

---

pubsub/azuresb/azuresb.go

pubsub/azuresb: fix non empty slice with nil message return

---

pubsub/awssnssqs/awssnssqs.go

When using multiple workers as per the example code in the docs, if it is combined with using `message.As(&sqsMessage)` the underlying SQS message will be wrong.
This fix creates a local variable for `m` which will keep scope for the asFunc. The downside I suspect is that memory usage will go up as more references are held rather than the current value which is overwritten as part of the loop.

pubsub/awssqssns: Make the SQS Message.As work with concurrent workers

---

blob/azureblob/azureblob.go

Prior to https://github.com/google/go-cloud/pull/2873, setting the
environment variable `AZURE_STORAGE_SAS_TOKEN` would work because the
default behavior was to open the bucket via the environment. However,
that pull request changed the behavior to only use the environment if an
account key were provided, but the SAS token can be thought of as a
temporary key.
To fix this, we check whether an account key or a SAS token is
provided. If one of them is available, open the container with the
environment.
Closes #2933

blob/azblob: Fix SAS token not being used to open a container

---

docstore/mongodocstore/go.sum
go.mod
go.sum
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.sum
samples/go.mod
samples/go.sum
secrets/hashivault/go.sum

The tag for this module got yanked and now checksums are failing. Pin
the version to the pseudo-version as described in
https://github.com/Azure/azure-storage-blob-go/issues/236#issuecomment-747063565.

blob/azblob: Fix azure-storage-blob-go checksum

---

pubsub/kafkapubsub/kafka.go

When using the default `kafka://` scheme, [no topic options with key are set](https://github.com/google/go-cloud/blob/e00dad626e8a600ae8028f56fbac281db67122f8/pubsub/kafkapubsub/kafka.go#L107-L110). This means that `Key` is always `sarama.ByteEncoder(nil)`: https://github.com/google/go-cloud/blob/e00dad626e8a600ae8028f56fbac281db67122f8/pubsub/kafkapubsub/kafka.go#L232-L245
Since `sarama.ByteEncoder(nil) != nil`, the underlying default hash partitioner does not fallback to the default partitioner: https://github.com/Shopify/sarama/blob/2a5254c26ef606cd9a5871a5dc4d2db86d5e35b7/partitioner.go#L183-L185
This means effectively that Kafka partitioning doesn't work with the default URL opener, because the partition is always the hash of an empty byte slice. Seems pretty serious. Unless I'm …

pubsub/kafka: fix fallback to random partitioner

---

.travis.yml

The push started failing, no idea why:
https://travis-ci.com/github/google/go-cloud/jobs/468898520
The current documentation says `${{ secrets.GITHUB_TOKEN }}` instead of just `$GITHUB_TOKEN`, so let's try that and see if it works (https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow).

internal/website: try using a different syntax for GITHUB_TOKEN

---

blob/gcsblob/gcsblob.go

Via comment only.
Fixes #2815.

blob/gcsblob: mark Options.SignBytes and .PrivateKey as deprecated

---

pubsub/gcppubsub/gcppubsub.go

pubsub/gcppubsub: Tell gRPC to allow messages up to 10MB (default is 4MB)

---

pubsub/azuresb/azuresb.go
pubsub/driver/driver.go

pubsub/azuresb: use new SendBatchDisposition function to send acks/nacks instead of amqp backchannel

---

docstore/mongodocstore/go.sum
go.mod
go.sum
pubsub/kafkapubsub/go.sum
pubsub/natspubsub/go.sum
pubsub/rabbitpubsub/go.sum
samples/go.mod
samples/go.sum
secrets/hashivault/go.sum

This fixes a hack we had to put in when they relabeled a release.

blob/azureblob: update github.com/Azure/azure-storage-blob-go

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

Not conferred by os.ModeDir, read-write permissions need to be set explicitly.

blob/fileblob: fix directory from opts.CreateDir not being writable

---

blob/fileblob/attrs.go

If `json.Encode` fails, the then-stray sidecar file should be removed—to not run afoul the contract, only correct and fully formed files are being left.

blob/fileblob: remove erroneous stray sidecar

---

runtimevar/awsparamstore/awsparamstore.go
runtimevar/awssecretsmanager/awssecretsmanager.go

runtimevar/aws*: fix flaky tests by mapping AWS errors to more standard context ones

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

An option needed to use fileblob as gracefully degraded drop-in in
legacy software, to approximate behaviour of a “dumb” file system
where sidecar files (with metadata) are not wanted.
A use-case is an image hoster who currently interfaces on-prem storage.

blob/fileblob: new param "metadata=skip" to not write sidecar files

---

docstore/memdocstore/query.go

docstore/memdocstore: apply limit after sorting

---

internal/admin/README.md
internal/website/content/howto/blob/_index.md
internal/website/content/howto/docstore/_index.md
internal/website/content/howto/pubsub/publish.md
internal/website/content/howto/pubsub/subscribe.md
internal/website/content/howto/runtimevar/_index.md
internal/website/content/howto/secrets/_index.md

Fixes #2973 
Update Documentation regarding `gcloud auth login` as it no longer (after gcloud version 128) sets Application Default Credentials.

internal: Correct Docs of ADC for GCP

---

server/requestlog/requestlog.go
server/requestlog/requestlog_test.go

I would like to have access to the request's Context in the request logger, so that I can include metadata and also reference logging implementation details that might be stashed away in the context.
This is particularly useful for request loggers that aim to perform tracing with frameworks other than opencensus. It's also helpful for integrating with certain logging frameworks. I've also noticed that it is a good way to pass information from the `http.Server`s (e.g. [`BaseContext`](https://github.com/golang/go/blob/87c6fa4f473f178f7d931ddadd10c76444f8dc7b/src/net/http/server.go#L2627-L2638)) down to the request logger.
To solve this, I've added a new field to `Entry` that is set based on the context from the request. I believe this change is relatively simple and backwards compatible.

server/requestlog: Add Request Context in requestlog.Entry

---

pubsub/awssnssqs/awssnssqs.go
pubsub/awssnssqs/awssnssqs_test.go
pubsub/azuresb/azuresb.go
pubsub/azuresb/azuresb_test.go
pubsub/driver/driver.go
pubsub/drivertest/drivertest.go
pubsub/gcppubsub/gcppubsub.go
pubsub/gcppubsub/gcppubsub_test.go
pubsub/kafkapubsub/kafka.go
pubsub/kafkapubsub/kafka_test.go
pubsub/mempubsub/mem.go
pubsub/natspubsub/nats.go
pubsub/natspubsub/nats_test.go
pubsub/pubsub.go
pubsub/rabbitpubsub/doc.go
pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go

Only a couple of drivers support a real type here (AWS and GCP), but it's reasonable to expose it if so (instead of just dropping it in the floor as we did previously).
Fixes #2986.

pubsub/all: Add support for As hook AfterSend

---

blob/azureblob/azureblob.go
blob/azureblob/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.replay
blob/azureblob/testdata/TestConformance/TestAs/verify_ContentLanguage_can_be_written_and_read_through_As.replay
blob/azureblob/testdata/TestConformance/TestCopy/NonExistentSourceFails.replay
blob/azureblob/testdata/TestConformance/TestCopy/Works.replay

Cloned from #2988 by @leezen, because it requires updating some golden files
Fixes #2982
Providing an empty map ends up causing the underlying SDK to want to have permissions to write tags against the destination blob. However, we don't actually need this permission since we're not really writing any tags. Instead, we should just pass in nil.

blob/azblob: Pass nil instead of an empty map for tags on Copy operation

---

secrets/azurekeyvault/akv.go
secrets/azurekeyvault/akv_test.go

This adds support for using Key Vault with Azure Stack Hub.
This PR makes the regexp used for parsing the Key Vault key id less strict about the key vault URI, allowing URIs on the form: `https://vault.<region>.<fqdn>/`.
Fixes #2995.

secrets/azurekeyvault: Add support for private clouds (Azure Stack)

---

pubsub/awssnssqs/awssnssqs.go
pubsub/azuresb/azuresb.go
pubsub/driver/driver.go
pubsub/drivertest/drivertest.go
pubsub/gcppubsub/gcppubsub.go
pubsub/kafkapubsub/kafka.go
pubsub/kafkapubsub/kafka_test.go
pubsub/mempubsub/mem.go
pubsub/natspubsub/nats.go
pubsub/pubsub.go
pubsub/pubsub_test.go
pubsub/rabbitpubsub/rabbit.go

An opaque field useful only for debugging and logging.
Fixes #2994.

pubsub: Add Message.LoggableID

---

pubsub/gcppubsub/gcppubsub.go
pubsub/gcppubsub/gcppubsub_test.go

Fixes #3003 
This PR allows users of the `pubsub/gcppubsub` package to configure the receive batch size via a query parameter. 
Signed-off-by: David Bond <davidsbond93@gmail.com>

pubsub/gcppubsub: Allow configuration of batch sizes

---

pubsub/batcher/batcher.go
pubsub/batcher/batcher_test.go
pubsub/driver/driver.go
pubsub/gcppubsub/gcppubsub.go

This allows configuring a maximum batch size in bytes on the batcher in an attempt to respect the GCP 10MB limitation per publish request_size as documented in https://cloud.google.com/pubsub/quotas.
Happy to add tests if this limitation should be enforced at the batcher level like proposed in this PR.

pubsub/gcppubsub: Consider publish request body size limitation when batching

---

pubsub/kafkapubsub/kafka.go
pubsub/kafkapubsub/kafka_test.go

This commit adds the ability for users of the `kafkapubsub` package to specify the initial consumer offset
when using a URL.
When creating a kafka consumer, you sometimes want to specify at which point the consumer should begin reading from
a topic. This is specified as either `oldest` or `newest`, where `oldest` is the oldest committed offset by the
consumer group and `newest` is the most recent offset.
Currently, there is no way to configure this via the URL, you'd have to use the `kafkapubsub` package directly to
build your consumer. So when you use a URL, you get the default sarama behaviour and you start consuming from
the newest point in the stream. This doesn't allow you to read streams from the start, which is a very common
usecase for consumers.
Signed-off-by: David Bond …

pubsub/kafkapubsub: Configure initial offset in URL.

---

pubsub/gcppubsub/gcppubsub.go

pubsub/gcppubsub: Tell gRPC to allow messages up to 11MB

---

blob/azureblob/azureblob.go

Due to Azure security requirements, there might be multiple service
identities attached to a particular account. In that case, the Client ID
must be provided in order to secure an authorization token.
This allows the `AZURE_CLIENT_ID` environment variable to be read in as
an optional extra bit of data and if provided will invoke the
appropriate underlying method in Azure autorest to authenticate with the
client Id instead
See
for tips on …

blob/azblob: allow for client id in MSI authentication

---

blob/blob.go

This improves the wording on the SignedURL docs by indicating the `GET` is used a default.
Currently, the reader may be led to believe that SignedURL can only be used to `GET` blobs, even though alternative methods can be specified via SignedURLOptions.

blob: improve clarity in docs

---

blob/fileblob/fileblob.go

blob/fileblob: don't overwrite URLOpener.Metadata if there's no URL param

---

blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go

Disclaimer: this change is primarily meant as a proposal. Feel free to amend or suggest other more appropriate ways to support it if needed.
Allows support for local storage emulator running on any storage domain (not only localhost or loopback addresses).
This could be the case if Azurite is running on on another node, in a local kube cluster (kind, minikube, ...) or in Jenkins Pipeline (for which Azurite may have an ip from the docker network if running itself in docker)

blob/azblob: generic storage domain support for local storage emulator (proposal)

---

internal/website/layouts/_default/baseof.html
internal/website/layouts/howto/list.html

There is a duplication of content in [How-To Guides](https://gocloud.dev/howto/) page and the side navigation.
I have removed the duplication as shown in the following image.

internal/website: remove duplicates from howto list

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

blob/fileblob: Fix pagination for dirs that end in characters smaller than the delimiter

---

internal/website/content/howto/pubsub/subscribe.md

Fix the link to the SQS publishing guide on the website.

docs: Fix link to SQS publishing guide

---

blob/azureblob/testdata/TestConformance/TestDirsWithCharactersBeforeDelimiter.replay
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go
blob/gcsblob/testdata/TestConformance/TestDirsWithCharactersBeforeDelimiter.replay
blob/s3blob/testdata/TestConformance/TestDirsWithCharactersBeforeDelimiter.replay
blob/s3blob/testdata/TestConformanceUsingLegacyList/TestDirsWithCharactersBeforeDelimiter.replay
blob/s3blob/testdata/TestConformanceUsingLegacyListV2/TestDirsWithCharactersBeforeDelimiter.replay
blob/s3blob/testdata/TestConformanceV2/TestDirsWithCharactersBeforeDelimiter.replay

A previous commit (https://github.com/google/go-cloud/commit/22c9230a5b7fc2e2131b33e2ea53786f6e577887) fixed pagination for this case, but the resulting ordering was invalid and inconsistent with other providers.
This change fixes `fileblob` to have the correct ordering, and also adds a drivertest to ensure that all drivers are compliant (they are).
Fixes #3092.

blob/fileblob: Fix ordering of keys that end in characters alphabetically before the delimiter

---

blob/s3blob/s3blob.go

Introduced in https://github.com/google/go-cloud/pull/3008](https://github.com/google/go-cloud/pull/3008.

blob/s3blob: Fix race introduced in URLOpener

---

gcp/cloudsql/cloudsql.go

This fixes #3121.
This always enables the IAM login option for GCP.
We could also have this configurable through a URL parameter, but that seems like the wrong approach. If you truly for some reason didn't want IAM authentication for cloud sql, you would have already declined to enable the flag it in the GCP setup for that database instance. If you did want to use IAM authentication, it would be annoyingly hard to debug why it wasn't working as it may surprise you to learn that the proxy has it off by default. So, it makes the most sense to just always enable it in the proxy.

postgres: Support IAM auth for GCP.

---

internal/website/data/examples.json
secrets/localsecrets/example_test.go
secrets/localsecrets/localsecrets.go

secrets/localsecrets: update docs to note that that base64 keys must be URL-safe

---

internal/testing/alldeps
internal/website/content/howto/pubsub/publish.md
internal/website/content/howto/pubsub/subscribe.md
internal/website/data/examples.json
pubsub/rabbitpubsub/amqp.go
pubsub/rabbitpubsub/example_test.go
pubsub/rabbitpubsub/fake_test.go
pubsub/rabbitpubsub/go.mod
pubsub/rabbitpubsub/go.sum
pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go
samples/go.sum

pubsub/rabbitpubsub: Switch to using github.com/rabbitmq/amqp091-go

---

runtimevar/awsparamstore/awsparamstore.go

With more than 10 entries in the SSM parameter store, runtimevar failed
to load keys unless they happened to be among the first 10 entries due
to pagination not being implemented in the AWS describeParameters API
call. This change implements the pagination.  `Fixes #3134`.

runtimevar/awsparamstore: implement pagination in describeParameter{,V2}

---

pubsub/awssnssqs/awssnssqs.go
pubsub/azuresb/azuresb.go
pubsub/batcher/batcher.go
pubsub/gcppubsub/gcppubsub.go

pubsub: Add support for overriding batch to AWS, GCP, Azure drivers

---

blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go

This PR adds "storage_account" as possible query string parameter to the URL.
It'll allow opening multiple storage accounts using the same credentials.

blob/azureblob: add storage_account query parameter

---

pubsub/kafkapubsub/kafka.go

pubsub/kafka: Allow overriding batching options for Topic

---

blob/fileblob/fileblob.go

A take at trying to make the file permissions consistent between directories, blob files and attribute files.
Rather than using a syscall to grab the umask, we replace `os.CreateTemp`/`ioutil.TempFile` with our own version that uses the permissions we desire.
Differences with `os.CreateTemp`:
- Uses `time.UnixNano()` instead of `fastrand()`
- Stores the temporary file "in-place" while it is being written
This has the following implications:
- After the year 2262 the behaviour is undefined (as per `time.UnixNano()`)
- It is possible for the file to already exist - this has a low likelihood, as the int64 is serialized as a hex value in the filename
Fixes #3165

blobl/fileblob: Add a custom createTemp function that uses consistent file permissions.

---

gcp/cloudsql/cloudsql.go
postgres/gcppostgres/gcppostgres.go
postgres/gcppostgres/gcppostgres_test.go
postgres/gcppostgres/main.tf

gcp/cloudsql: enable IAM login
Fixes #3121
Fixes #3122
Fixes #3164
The code in this pull request allows Google Cloud [IAM PostgreSQL authentication](https://cloud.google.com/sql/docs/postgres/authentication). As agreed in #3122, the option for IAM authentication is always on. The only difference is oauth2 tokenSource being added as a parameter in certs.RemoteOpts.
I've also updated terraform testing infrastructure, added variable (user_email) to be added as a SQL IAM user
Test passing for both built in and IAM authentication:
```
$ go test
2022/10/14 18:11:07 refreshing ephemeral certificate for instance project-id:europe-west1:go-cloud-test-e271c23e4c3e86e2331697d5
2022/10/14 18:11:07 Generated RSA key in 58.542136ms
2022/10/14 18:11:08 Scheduling refresh of ephemeral certificate in …
```

gcp/cloudsql: GCP postgres IAM login support

---

blob/memblob/memblob.go

Fix copy for memblob with options. Current behaviour always returns the option error value, nil with no copy done.

blob/memblob: fix copy with options

---

pubsub/benchmark_test.go
pubsub/pubsub.go

Fixes #3203.
The previous code was trying to be clever and not consider time when nobody was calling `Receive`, or something like that. 
#3203 identifies a case where a specific set of timing results in huge batch sizes, even though there are hardly any messages.
I simplified the code to just count all the time and ran the benchmarks. It ramps up slower in a couple of cases now, but still gets there, and this "intermittent" message case looks much better.

pubsub: simplify and improve batch sizes, especially for low message rates

---

pubsub/kafkapubsub/kafka.go

`ExampleOpenTopic` (pubsub/kafkapubsub/example_test.go) show a simple call to `OpenTopic` without `kafkapubsub.TopicOptions` as passing a `nil` argument.
This is done by replacing a `nil` pointer with the appropriate zero-value.  This behaviour exists in `OpenSubscription` too. However, PR #3163 introduced overriding batching options which inadvertently accesses a field of a nil pointer.
/cc @vangent I see you authored the relevant files, could you please take a look?
P.S> This is my first commit to this repository (read the contributing guidelines though) - so couple of questions: 
1. Would you like me to report a concomitant bug and reference it from the commit's message?
2. Markdown in commit body - yes/no?
```bash
$ go test ./...
?       gocloud.dev     [no test files]
ok …
```

pubsub/kafkapub: fix nil pointer dereference

---

aws/aws.go

make sure to set `SigningRegion` while using custom endpoints for aws sdk v2 
fixes: #3218

Set SigningRegion when using custom endpoint url

---

aws/aws.go

aws: fix typo on awssdk=v2 documentation

---

blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

This PR adds support in the **blob/s3blob** driver for per-request s3 options when using the underlying v2 AWS SDK.
Specifically, adds **As** support for:
* `ListOptions.BeforeList` (V2) for the type `*[]func(*s3v2.Options)`
* `ReaderOptions.BeforeRead` (V2) for the type `*[]func(*s3v2.Options)`
which gives the application the ability to supply per-request options when using the V2 SDK.
There does not appear to be any utility in doing the same for `BeforeWrite` because we already expose access to the `s3v2manager.Uploader` which includes the `ClientOptions` list.

blob/s3blob: adds support for per-request s3v2 Options, implementing #3214

---

blob/azureblob/azureblob.go
blob/azureblob/testdata/TestConformance/TestUploadDownload.replay
blob/blob.go
blob/blob_test.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/gcsblob/testdata/TestConformance/TestUploadDownload.replay
blob/memblob/memblob.go
blob/s3blob/s3blob.go
blob/s3blob/testdata/TestConformance/TestUploadDownload.replay
blob/s3blob/testdata/TestConformanceUsingLegacyList/TestUploadDownload.replay
blob/s3blob/testdata/TestConformanceUsingLegacyListV2/TestUploadDownload.replay
blob/s3blob/testdata/TestConformanceV2/TestUploadDownload.replay

Fixes https://github.com/google/go-cloud/issues/3245
Fixes https://github.com/google/go-cloud/issues/2807

blob: Add Upload and Download methods that may be more efficient for some drivers

---

pubsub/gcppubsub/gcppubsub.go
pubsub/gcppubsub/gcppubsub_test.go

Same as `max_recv_batch_size`, make it possible to customize `max_send_batch_size` at GCP pubsub package.

Make it possible to configure max_send_batch_size in GCP pubsub.

---

blob/s3blob/example_test.go
blob/s3blob/s3blob_test.go
internal/website/data/examples.json

The actual values that [are supported](https://github.com/google/go-cloud/blob/master/aws/aws.go#L155) for the `awssdk` argument for s3 are `v2` and `V2`.

internal/website: fix the s3 'awssdk' argument examples

---

blob/blob.go
blob/blob_reader_test.go
blob/drivertest/drivertest.go

The blob `Reader` and `Writer` implement `WriterTo` and `ReaderFrom`, respectively, which is meant to avoid intermediary allocations and copies (passing readers and readers through all the way down). Unfortunately, the current implementation falls short and implements those interfaces by making a local copy ala io.Copy.
Instead, reproduce the strategy in newer versions of `io.Copy`: reflect on the reader/writer provided by the user, and if they implement these interface, too, then call into that.
Local benchmarks show significant performance improvements:
```
│   /tmp/old   │              /tmp/new               │
│    sec/op    │   sec/op     vs base                │
Memblob/BenchmarkRead-10   3.449µ ± 15%   1.919µ ± 2%  -44.37% (p=0.000 n=10)
```
Most benchmarks use `ReadAll` and …

blob: pass through reader/writer to `WriteTo`/`ReadFrom` if available

---

blob/blob.go
blob/blob_fs.go
blob/blob_fs_test.go

blob: make blob.Bucket implement io/fs.FS and io/fs.SubFS

---

blob/gcsblob/gcsblob.go
blob/gcsblob/gcsblob_test.go

blob/gcsblob: add support for forcing an authenticated client

---

server/requestlog/requestlog.go

server/requestlog: make responseStats implement http.Flusher

---

server/requestlog/requestlog.go

server/requestlog: Don't consume entire body just to get a request size

---

blob/azureblob/azureblob.go

blob/azblob: fix use of SAS token in service URL

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

blob/fileblob: Add an option to avoid using os.TempDir for temp files

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

blob/fileblob: Add docstring and URL support for NoTempDir option (and alternative of TMPDIR env variable)

---

blob/gcsblob/gcsblob.go

blob/gcsblob: Don't hard-fail if no DefaultCredentials are found

---

aws/rds/rds.go

Hi folks !
AWS recently started sending out emails about the expiration of the `rds-ca-2019` CA (expires in 2024), suggesting we upgrade our instance to `rds-ca-rsa2048-g1`, `rds-ca-rsa4096-g1`, or `rds-ca-ecc384-g1`.
The corresponding documentation is [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html), and includes instructions as to client configuration and where to retrieve CA information.
I'm assuming the URL used here is a former address, and that AWS has since then changed the address of the reference CA bundle, without updating the bundle at the former address.
Creating RDS instances with both `rds-ca-2019` and `rds-ca-ecc384-g1`, I can confirm that the new bundle works with both, while the old one only works with …

aws/rds: Switch AWS RDS CA bundle to the officially documented URL

---

blob/gcsblob/gcsblob.go

blob/gcsblob: Use less-empty creds for unauthenticated mode.

---

internal/website/data/examples.json
runtimevar/constantvar/constantvar.go
runtimevar/constantvar/constantvar_test.go
runtimevar/constantvar/example_test.go

runtimevar/constantvar: Add support for reading the constantvar from an environment variable

---

docstore/gcpfirestore/fs.go
docstore/gcpfirestore/fs_test.go

Fixes: https://github.com/google/go-cloud/issues/3339
This edits the regex to allow non-default database names when creating Firestore collections.
In line with prior art, this also creates a helper function to assist with creating a valid scheme.

docstore/gcpfilestore: add support for non-default databases.

---

docstore/gcpfirestore/query.go

Add missing resource header when running query in Firestore. The header is already present in all the other operations but needs to be added when running a query.  
This prevented being able to use the Firestore emulator and running queries against it.

gcpfirestore - Add missing resource header when running query

---

pubsub/azuresb/azuresb.go
pubsub/azuresb/azuresb_test.go

new auth method to support Service principal/kubelet identity/Workload identity auth methods.(handled by Azure golang SDK)
How to use:
depends on method(Workload, kubelet, Service), set ENV variables:
`AZURE_SERVICEBUS_HOSTNAME` - to trigger new method
For service principal auth, set ENV variables described [here](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)
If you use workload/kubelet identities,  ENV variables are injected by AKS, some details can be found [here](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet)
closes https://github.com/google/go-cloud/issues/3359
was able to run performance test using new auth model:
```
AZURE_CLIENT_SECRET='secret' AZURE_CLIENT_ID=2f370f8b-XXXX-4c60-b3c7-XXXXX …
```

pubsub/azuresb: new auth method  to support Service principal/kubelet identity/Workload identity auth methods

---

docstore/driver/driver.go

Align comments with the latest changes to docstore in v0.36.0

docstore/driver: update Filter.Op comments for new in/not-in operators

---

pubsub/azuresb/azuresb.go

pubsub/azpubsub: Ensure 401s are not retryable

---

aws/aws.go
blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

Adds support to s3blob for setting AWS S3 server side encryption headers when making requests that require such headers. The additional settings can be specified with the `ssetype` and `kmskeyid` URL params, similar to the other configuration settings
Fixes #3337
Bucket policy enforces KMS headers - none provided (effectively the issue described in #3337)
Expect: `AccessDenied` failure
Bucket policy enforces KMS headers - values provided
Expect: No errors. Object is uploaded
Bucket policy doesn't enforce KMS - no values provided 
Expect: No errors. Object is uploaded
Bucket policy enforces KMS headers - none provided (effectively the issue described in #3337)
Expect: `AccessDenied` failure
Bucket policy enforces KMS headers - values provided
Expect: No errors. Object is uploaded
Bucket …

blob/s3blob: Support S3 server side encryption headers for Write and Copy

---

docstore/doc.go

docstore/all: Add a link to https://github.com/bartventer/docstore-gen.

---

docstore/mongodocstore/mongo.go

This PR resolves issue [#3393](https://github.com/google/go-cloud/issues/3393). 
This update modifies the newUpdateDoc function in the docstore/mongodocstore package to check the length of the 'sets' variable before adding the '$set' field to the 'updateDoc' map. This prevents an error when calling the update function with only 'unset' or 'inc' modifiers and no 'set' modifiers.

fix(docstore/mongodocstore): check length of sets in newUpdateDoc function

---

pubsub/azuresb/azuresb.go

Same as GCP pub/sub, make it possible to configure `max_recv_batch_size` in Azure service bus with query param.

Make it possible to configure `max_recv_batch_size` in Azure service bus.

---

internal/website/data/examples.json
pubsub/kafkapubsub/example_test.go
pubsub/kafkapubsub/kafka.go
pubsub/kafkapubsub/kafka_test.go

This PR introduce possibility to configure message key option when opening topic by url.
Related issue in [krakend-pubsub](https://github.com/krakend/krakend-pubsub/issues/18)

pubsub/kafkapubsub: Configuring key_name when OpenTopicURL

---

blob/blob.go
blob/blob_test.go

blob: Fix panics if reader recreation fails after Seek

---

blob/fileblob/fileblob.go
blob/fileblob/fileblob_test.go

blob/fileblob: Allow customization of the FileMode

---

docstore/mongodocstore/urls.go
docstore/mongodocstore/urls_test.go

Prior to this commit, the dialer for MongoDB was generated once from MONGO_SERVER_URL environment variable but was never updated even when the environment variable was updated in subsequent calls. While this works fine when MONGO_SERVER_URL is not expected to update, but as MONGO_SERVER_URL also contains the credentials to connect to MongoDB, it's a fairly common use case to rotate these credentials (and hence the environment variable) at regular intervals.
This commit fixes that and updates the dialer when MONGO_SERVER_URL is updated.
This PR blocks https://github.com/tektoncd/chains/issues/1089

docstore/mongodocstore: Update Mongo dialer when MONGO_SERVER_URL rotates

---

pubsub/rabbitpubsub/amqp.go
pubsub/rabbitpubsub/fake_test.go
pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go

Fixes #3430
Since we usually want to set the prefetch count, I simplify the rabbit url to support a single query string
we can use `rabbit://myqueue` (continues backward compatible) or the new one `rabbit://myqueue?prefetch_count=<prefetch-count-value>`
I tested locally using a rabbitmq docker image and it seems to work properly.

 pubsub/rabbitpubsub: add query string set the qos prefetch count

---

pubsub/kafkapubsub/kafka.go
pubsub/rabbitpubsub/amqp.go
pubsub/rabbitpubsub/fake_test.go
pubsub/rabbitpubsub/rabbit.go
pubsub/rabbitpubsub/rabbit_test.go

Fixes #3432 
This development is similar to pull request #3431

pubsub/rabbitpubsub: add query string to set the  routing key from metadata 

---

pubsub/rabbitpubsub/amqp.go
pubsub/rabbitpubsub/rabbit.go

I note that we mere add a %v reference to the original rabbitmq errors, and since we may need to unwrap such errors, it is better use %w
I also create few global errors to return instead allocate a new error in some trivial cases
Enjoy

pubsub/rabbitpubsub: wrap pubsub rabbitmq errors

---

blob/azureblob/azureblob.go

I found that when we're downloading an a gzipped object with `Content-Encoding: gzip`, AZB is transparently sending back an uncompressed object rather than the gzipped object, and when this happens, I also discovered that go-cloud fails and panics because the Content-Length and the Content-Range fields are not set in this situation.
To gracefully handle this, check if the ContentLength field is nil before using it, and return 0 if both ContentRange and ContentLength are missing. This unfortunately does mean `Size()` may return 0 in some cases, but I don't see a good way to fix that without a bigger change in design. With this patch, I can confirm our issue is resolved.
Unfortunately, I did not see a good reference for how I could write a unit test for this. It seems existing conformance …

blob/azureblob: Do not panic if Content-Length and Content-Range are missing

---

blob/blob_fs.go

Motivation:
- `http.ServeFileFS()` uses `errors.Is()` to match on `fs.ErrNotExist` and `fs.ErrPermission` errors and return corresponding HTTP status codes.
- gocloud currently returns `fs.PathError` which do not wrap the underlying `fs` errors, and which are not handled by `http.ServeFileFS()`'s error handling.
- gocloud returning `fs.PathError`s results in `http.ServeFileFS()` serving Internal Server Errors instead of Not Found or Permission Denied errors.
Fix:
- wraps gocloud NotFound and PermissionDenied errors encountered in `Open()` around their `io/fs` counterparts
- does not perform wrapping for other gocloud errors as they can either not occur or are ambiguous in this context

blob: convert gocloud errors in `Open()` into appropriate fs errors

---

samples/guestbook/localdb/main.go

Code didn't run on my m1 macbook pro, getting
```
$ go run localdb/main.go
go: downloading gopkg.in/pipe.v2 v2.0.0-20140414041502-3c2ca4d52544
localdb: Starting container running MySQL
Unable to find image 'mysql:5.6' locally
docker: Error response from daemon: no match for platform in manifest: not found.
See 'docker run --help'.
localdb: running [docker run --rm --env MYSQL_DATABASE=guestbook --env MYSQL_ROOT_PASSWORD=password --detach --publish 3306:3306 mysql:5.6]: exit status 125:
exit status 1
```
That's because mysql:5.6 only had a linux/amd64 image (https://hub.docker.com/layers/library/mysql/5.6/images/sha256-897086d07d1efa876224b147397ea8d3147e61dd84dce963aace1d5e9dc2802d?context=explore). Adding the platform flag tells docker to download it anyways, even on a mac. 
I always use …

samples/guestbook/localdb/main.go: add docker platform flag

---

pubsub/pubsub.go
pubsub/pubsub_test.go

Allow batch requests to return results independently without one blocking the other.
This will in turn allow `Subscription.Receive` to return a message from a request (since the `Receive` function signature returns only one message), without waiting for all the requests from the batch to complete.
Except for this, package behavior should remain as is...
Fixes: #3456

pubsub: Make batch request results independent

---

pubsub/awssnssqs/awssnssqs.go
pubsub/pubsub.go

Small tidy up of stuff that I found in my previous [PR](https://github.com/google/go-cloud/pull/3457) but didn't want to add there because they were irrelevant
Changes include:
- removal of unused variables and constants
- better error checking using `errors.Is` comparisons to catch wrapped errors
- variable naming collisions fix
- pointer dereference checks

pubsub: tidy and cleanup

---

aws/aws.go
aws/aws_test.go

It seems that this is needed in aws-sdk-v2 for minio to work.
see: https://github.com/minio/docs/issues/406#issuecomment-1246316964
refs https://github.com/google/go-cloud/issues/3472

blob/s3blob: custom endpoints with s3 and aws sdk v2

---

blob/blob.go
blob/blob_fs.go
blob/blob_fs_test.go

blob/all: Don't require SetIOFSCallback be called to use io/fs.FS functions

---

blob/s3blob/s3blob.go

w.pr cannot be used to indicate that the pipe has been closed. Instead, we use an atomic.Bool. The problem with using w.pr is that a write to it in the goroutine launched by writer.open can race with a read on w.pr in Close.
Note that it's still possible that w.pr.CloseWithError runs concurrently with w.pr.Close. But this is fine.

blob/s3blob: fix data race

---

blob/azureblob/azureblob.go

blob/azureblob: fix typo in documentation

---

blob/azureblob/azureblob.go
blob/azureblob/azureblob_test.go

blob/azblob: Support AZURE_STORAGEBLOB_CONNECTIONSTRING as an alternative for AZURE_STORAGE_CONNECTION_STRING

---

aws/aws.go
aws/aws_test.go
blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

This commit adds the following query parameters for AWS:
1. `dualstack`
2. `fips`
3. `accelerate` (S3-only)
This avoids the need for users to specify `endpoint`. For example, if my AWS S3 bucket is `my-bucket` in `us-east-1`, and you want to enable transfer acceleration, dual-stack support, and/or FIPS, you would need to configure `endpoint` with one of the following:
1. `my-bucket.s3-accelerate.amazonaws.com`
2. `my-bucket.s3-accelerate.dualstack.amazonaws.com`
3. `my-bucket.s3-fips.us-gov-east-1.amazonaws.com`
4. `my-bucket.s3-fips.dualstack.us-east-1.amazonaws.com`
For example, for the last option, users can use `s3://my-bucket?fips=true&dualstack=true`.
Closes https://github.com/google/go-cloud/issues/3484

s3blob/blob: support additional endpoint query parameters

---

internal/website/content/howto/blob/_index.md

blob: change howto docs to reflect awssdk=v2 is the default as of 0.39.

---

blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

This ensures that we can use blob/blob with s3 compatible storage like minio.
Pass `usePathStyle=true` to force PathStyle for s3. Pass `disableHTTPS=true` to disable tls for endpoint.
Fixes: https://github.com/google/go-cloud/issues/3490

Add disableHTTPS and usePathStyle s3v2.Options as query param

---

aws/aws.go
aws/aws_test.go

Issuing many S3 uploads in quick succession causes the following error:                                                                                                                         
```             
operation error S3: PutObject, failed to get rate limit token, retry quota exceeded, 0 available, 5 requested                  
```                                                                                                                          
By default, this rate limit is disabled to restore the same behavior as SDK v1. If `rate_limiter_capacity` is set, then client-side rate limits will take effect.                                                                                                       
Closes https://github.com/google/go-cloud/issues/3496

aws: add rate_limiter_capacity to configure client-side rate limits

---

blob/s3blob/s3blob.go
blob/s3blob/s3blob_test.go

blob/s3blob: Allow using s3ForcePathStyle as a synonym of use_path_style, for backwards compatibility with V1

---

pubsub/gcppubsub/example_test.go

pubsub/gcppubsub: Add an example showing how to call ModifyAckDeadline

---

aws/aws.go
aws/aws_test.go
blob/gcsblob/gcsblob.go
blob/gcsblob/gcsblob_test.go
blob/s3blob/s3blob_test.go

aws, blob: Add support for anonymous query param for gcsblob and all AWSv2 providers

---

aws/aws.go
docstore/awsdynamodb/query_test.go

[aws/aws.go:28](https://github.com/google/go-cloud/blob/9e81e8d4f2a83fc70eb74643da0485273ab2480d/aws/aws.go#L28): remove duplicate import statements, the `github.com/aws/aws-sdk-go-v2/config` is imported twice,
[docstore/awsdynamodb/query_test.go:27](https://github.com/google/go-cloud/blob/9e81e8d4f2a83fc70eb74643da0485273ab2480d/docstore/awsdynamodb/query_test.go#L27): remove duplicate import statements, the `github.com/aws/aws-sdk-go/service/dynamodb` is imported twice.

remove duplicate imports

---

pubsub/pubsub.go

[pubsub/pubsub.go:565](https://github.com/google/go-cloud/blob/9e81e8d4f2a83fc70eb74643da0485273ab2480d/pubsub/pubsub.go#L565): remove unnecessay nil check.
```
var slice []byte
if slice != nil && len(slice) > 0 {}
// is the same as
if len(slice) > 0 {}
```
because `len(slice)` where slice == nil is always equal to 0,
`staticcheck` will highlight this optimization with the following message:
```
pubsub/pubsub.go:565:9: should omit nil check; len() for []*gocloud.dev/pubsub/driver.Message is defined as zero (S1009)
```
for reference: [staticcheck S1009](https://staticcheck.dev/docs/checks#S1009)

remove unnecessary nil check

---

internal/openurl/openurl.go

- Add strings.ToLower for string normalization
- Align with RFC 3986 specifications for URL scheme handling
- Use direct map look up in ValidSchem func

openurl: fix URL scheme handling case-insensitive

---

blob/gcsblob/gcsblob.go

Fixes #3528
I have not tested this but it is a recommended change that I believe should fix the linked issue.

blob/gcsblob: fix error checking for NotFound errors

---

blob/azureblob/azureblob.go
blob/blob.go
blob/driver/driver.go
blob/drivertest/drivertest.go
blob/fileblob/fileblob.go
blob/gcsblob/gcsblob.go
blob/memblob/memblob.go
blob/s3blob/s3blob.go

This commit introduces support for conditional writes for major cloud providers: aws, gcp, azure.
It does so by adding a new write options: `IfNotExist`. 
When set to true, conditions are set for each cloud storage driver to enable the desired behavior.
Addresses #3518

blob: introduce conditional write option for storage

---

go.mod
go.sum
internal/otel/init.go
internal/otel/metrics.go
internal/otel/trace.go
internal/otel/trace_test.go
internal/testing/alldeps
internal/testing/oteltest/diff.go
internal/testing/oteltest/exporter.go

Based on the review feedback shared : This pr contains improvements to the common code for open telemetry services:

internal: feedback updates to otel common code

---

go.mod
go.sum
internal/otel/init.go
internal/otel/metrics.go
internal/otel/trace.go
internal/otel/trace_test.go
internal/testing/alldeps
internal/testing/oteltest/diff.go
internal/testing/oteltest/exporter.go
postgres/awspostgres/awspostgres.go
postgres/gcppostgres/gcppostgres.go
postgres/postgres.go

Micro PR to migrate monolith : https://github.com/google/go-cloud/pull/3539
PR affects : 
- postgres

postgres:  postgresql migration to opentelemetry

---

blob/blob.go

Updates https://github.com/google/go-cloud/issues/3596

blob: use bigger buffer to make writes faster
