- .gitignore
- samples/tutorial/README.md
> samples/tutorial: use OpenBucket instead of NewBucket

- README.md
> readme: expand project status section

- wire/cmd/wire/main.go
Fixes #237 
For now, it just shows usage.
> wire: show help when requested

- blob/gcsblob/gcsblob.go
- internal/testing/checkpr.sh
cleanup: remove namingRuleURL
closes #69
> travis: remove disabled varcheck and add build-tags

- .travis.yml
- internal/testing/checkpr.sh
- internal/testing/wirecheck.sh
> travis: add wire check step

- blob/drivertest/drivertest.go
- blob/gcsblob/testdata/TestConformance/TestAttributes/Size.yaml
- blob/s3blob/testdata/TestConformance/TestAttributes/Size.yaml
- go.mod
- go.sum
> blob: Use newest version of go-vcr; enable TestAttribute.Size subtest that was broken due to go-vcr bug

- .gitignore
- internal/contributebot/Dockerfile
- internal/contributebot/README.md
- internal/contributebot/cloudbuild.yaml
- internal/contributebot/k8s/contributebot.yaml.in
- internal/contributebot/main.tf
- internal/contributebot/outputs.tf
- internal/contributebot/variables.tf
> internal/contributebot: add GKE deployment

- mysql/rdsmysql/rdsmysql.go
> mysql/rdsmysql: enable native password authentication

- server/server.go
> server: add a Shutdown method

- blob/s3blob/s3blob.go
> blob/s3blob: set Uploader.PartSize based on opts.BufferSize

- .travis.yml
- internal/testing/checkpr.sh
> travis: remove golangci-lint

- blob/blob.go
- blob/driver/driver.go
- blob/drivertest/drivertest.go
- blob/fileblob/fileblob.go
- blob/gcsblob/testdata/TestConformance/TestCanceledWrite/EmptyContentType.yaml
- blob/gcsblob/testdata/TestConformance/TestCanceledWrite/NonEmptyContentType.yaml
- blob/s3blob/testdata/TestConformance/TestCanceledWrite/ChunkedUpload.yaml
- blob/s3blob/testdata/TestConformance/TestCanceledWrite/EmptyContentType.yaml
- blob/s3blob/testdata/TestConformance/TestCanceledWrite/NonEmptyContentType.yaml
- go.mod
- go.sum
The updated dnaeon/go-vcr is to pick up a fix I submitted to it:
https://github.com/dnaeon/go-vcr/pull/34#issuecomment-423033367
> blob: cancel the Writer ctx to abort a write

- internal/docs/design.md
> docs: add a section on enforcing portability to design.md

- wire/README.md
> wire/doc: reformat README.md

- internal/testing/terraform/terraform.go
- mysql/cloudmysql/cloudmysql_test.go
- mysql/cloudmysql/main.tf
I also created some small test infrastructure to read values from
Terraform. The test will be skipped unless Terraform state is present.
Updates #407
> mysql/cloudmysql: add integration test

- blob/blob.go
- blob/driver/driver.go
- blob/fileblob/fileblob.go
- blob/gcsblob/gcsblob.go
- blob/s3blob/s3blob.go
> blob: get rid of the blobError wrapper

- blob/blob.go
- blob/driver/driver.go
- blob/drivertest/drivertest.go
- blob/gcsblob/gcsblob.go
- blob/gcsblob/gcsblob_test.go
- blob/gcsblob/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.yaml
- blob/gcsblob/testdata/TestConformance/TestAs/verify_ContentLanguage_can_be_written_and_read_through_As.yaml
- blob/s3blob/s3blob.go
- blob/s3blob/s3blob_test.go
- blob/s3blob/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.yaml
- blob/s3blob/testdata/TestConformance/TestAs/verify_ContentLanguage_can_be_written_and_read_through_As.yaml
Fixes #542.
Modeled on WriterOptions.BeforeWrite and Attributes.As.
> blob/all: add As functionality for calling List (via ListOptions.BeforeList) and ListObject

- README.md
- Move the wire paragraph down a bit so the storage example follows
the intro paragraph.
- Reword the first sentence of the wire paragraph.
> README: slight rewrite

- blob/driver/driver.go
Following up on comments from #510 .
> blob: fix a couple of comments

- server/server.go
> server: add constructor for DefaultDriver to apply timeouts

- wire/README.md
> wire: add FAQ section

- blob/example_test.go
- blob/fileblob/fileblob.go
- blob/fileblob/fileblob_test.go
- samples/guestbook/inject_local.go
- samples/guestbook/wire_gen.go
gcsblob and s3blob both use `OpenBucket`.
> blob/fileblob: rename NewBucket -> OpenBucket for consistency

- blob/driver/driver.go
> blob: add a comment to ListPage about ordering

- internal/contributebot/wire_gen.go
example build log:
https://gopkgs.io/builds/20181105-074139-ef381867
> internal/contributebot: fix build breakage: filevar.NewVariable is now New

- .travis.yml
> test: add windows Travis build

- internal/docs/pubsub/design.md
There is no token type. I think Bryan used it in his talk for readability.
> docs: make pubsub docs compilable

- internal/testing/runchecks.sh
The current behavior is to stop at first failure.
> internal/testing: continue running other modules despite errors

- internal/pubsub/acks_test.go
- internal/pubsub/empty_sub_test.go
- internal/pubsub/pubsub.go
- internal/pubsub/pubsub_test.go
> pubsub: remove all batching knobs (TopicOptions, SubscriptionOptions)

- blob/gcsblob/example_test.go
- blob/s3blob/example_test.go
> blob: add examples for gcsblob, s3blob

- wire/internal/wire/testdata/MultipleArgsSameType/foo/foo.go
- wire/internal/wire/testdata/MultipleArgsSameType/foo/wire.go
- wire/internal/wire/testdata/MultipleArgsSameType/pkg
- wire/internal/wire/testdata/MultipleArgsSameType/want/wire_errs.txt
> wire/tests: add a test for multiple args of the same type to an injector

- internal/contributebot/prod/k8s/contributebot.yaml
This PR updates the container image tag in the contributebot YAML.
> internal/contributebot: updates the container image tag in the contributebot YAML

- gcp/gcpcloud/gcpcloud.go
- mysql/cloudmysql/cloudmysql.go
- mysql/cloudmysql/cloudmysql_test.go
- mysql/cloudmysql/example_test.go
- samples/guestbook/wire_gen.go
This implements @zombiezen 's suggestion for #608.
> mysql: remove Options struct, move the TraceOpts field into Params

- internal/pubsub/driver/driver.go
- Remove references to Topic and Subscription options that no longer exist.
- Require that all methods are goroutine-safe, to allow batching that makes
concurrent calls.
> internal/pubsub/driver: clarify doc comments

- internal/retry/retry.go
- internal/retry/retry_test.go
> internal/retry: a package for retrying calls

- internal/pubsub/acks_test.go
- internal/pubsub/driver/driver.go
- internal/pubsub/empty_sub_test.go
- internal/pubsub/gcppubsub/gcppubsub.go
- internal/pubsub/mempubsub/mem.go
- internal/pubsub/pubsub.go
- internal/pubsub/pubsub_test.go
> pubsub: add maxMessages argument to ReceiveBatch

- internal/pubsub/drivertest/drivertest.go
> pubsub: add missing ack in drivertest

- internal/pubsub/driver/driver.go
- internal/pubsub/gcppubsub/gcppubsub.go
- internal/pubsub/mempubsub/mem.go
- internal/pubsub/pubsub.go
See the issue for rationale.
Fixes #753.
> internal/pubsub: remove Close methods from driver

- CONTRIBUTING.md
- README.md
Using `mdformat`. No actual content changes.
> docs: format some .md files

- internal/pubsub/driver/driver.go
- internal/pubsub/pubsub.go
> pubsub: integrate internal/batcher

- internal/pubsub/driver/driver.go
- internal/pubsub/pubsub.go
> pubsub: Revert "pubsub: integrate internal/batcher (#796)"

- internal/batcher/batcher.go
- internal/batcher/batcher_test.go
Calling AddNoWait doesn't block.
> internal/batcher: add AddNoWait

- internal/pubsub/drivertest/drivertest.go
- Use idiomatic slice declarations.
- Rename some variables to `got` and `want`.
> internal/pubsub/drivertest: minor cleanup

- go.mod
- go.sum
- internal/contributebot/go.sum
- internal/pubsub/rabbitpubsub/doc.go
- internal/pubsub/rabbitpubsub/examples_test.go
- internal/pubsub/rabbitpubsub/rabbit.go
- internal/pubsub/rabbitpubsub/rabbit_test.go
Implementation of driver.Topic, including SendBatch.
> internal/pubsub/rabbitpubsub: RabbitMQ implementation: publish

- internal/pubsub/gcppubsub/gcppubsub.go
- internal/pubsub/gcppubsub/gcppubsub_test.go
> pubsub: move endPoint to gcppubsub.EndPoint

- runtimevar/paramstore/paramstore.go
I think this was needed in a previous incarnation of the code, but the `readParam` func and `param` struct doesn't add much value now, so I've updated it to inline the code.
> runtimevar/paramstore: simplify code by removing "param" struct

- index.html
> index.html: use an anchor tag instead of markdown

- AUTHORS
- CONTRIBUTORS
Update Steve's email in CONTRIBUTORS and AUTHORS. Amend to #892
> CONTRIBUTORS: update Steve's email address

- internal/docs/design.md
This PR updates the list of coding conventions for the Go Cloud project, per comments that came up on https://github.com/google/go-cloud/pull/899.
> internal/docs: update DESIGN.md coding conventions list

- blob/gcsblob/gcsblob.go
- Applied a format seen in godoc.org/github.com/lib/pq for bulleted lists. 
- Fixed tabbing/spacing.
- #896 (Not automatically closing since there seems to be other godoc's in similar conditions)
> blob/gcsblob: small updates to godoc formatting

- blob/blob.go
- blob/drivertest/drivertest.go
- blob/example_test.go
- blob/fileblob/fileblob.go
- blob/gcsblob/example_test.go
- blob/gcsblob/gcsblob.go
- blob/s3blob/example_test.go
- blob/s3blob/s3blob.go
- Expand package documentation.
- Ensure code formatting is applied appropriately.
- Use a consistent format for bulleted lists.
- Move a couple of Examples up the package level to make them more visible.
Updates #896.
Ping me if you want a demo.
> blob/docs: improve package godoc

- internal/pubsub/acks_test.go
- internal/pubsub/drivertest/drivertest.go
- internal/pubsub/example_test.go
- internal/pubsub/pub_test.go
- internal/pubsub/pubsub.go
- internal/pubsub/pubsub_test.go
- internal/pubsub/rabbitpubsub/examples_test.go
> pubsub: change Topic.Close() to Topic.Shutdown(ctx) 

- internal/secrets/driver/driver.go
Combine Decrypter and Encrypter into one interface.
> internal/secrets/driver: make driver one interface

- internal/contributebot/prod/k8s/contributebot.yaml
> internal/contributebot: update deployed image

- blob/memblob/memblob.go
- blob/memblob/memblob_test.go
> blob/memblob: add an in-memory implementation of blob

- runtimevar/runtimevar.go
> runtimevar/doc: refresh documentation for Decoder-related stuff

- runtimevar/constantvar/example_test.go
- runtimevar/etcdvar/example_test.go
- runtimevar/filevar/example_test.go
- runtimevar/paramstore/example_test.go
- runtimevar/runtimeconfigurator/example_test.go
> runtimevar/doc: improve/add examples for driver implementations

- internal/contributebot/ghauth.go
Makes RoundTrip easier to understand, but also allows the cached token to be reused for other purposes (like Git tool access).
Updates #687
> internal/contributebot: factor out *gitHubInstallAuth.fetchToken method

- blob/azureblob/azureblob.go
- blob/azureblob/testdata/TestConformance/TestAttributes.yaml
- blob/blob.go
- blob/driver/driver.go
- blob/drivertest/drivertest.go
- blob/fileblob/attrs.go
- blob/fileblob/fileblob.go
- blob/gcsblob/gcsblob.go
- blob/gcsblob/testdata/TestConformance/TestAttributes.yaml
- blob/memblob/memblob.go
- blob/s3blob/s3blob.go
- blob/s3blob/testdata/TestConformance/TestAttributes.yaml
> blob/all: add support for Content(Disposition,Encoding,Language) and CacheControl headers across all providers

- samples/tutorial/README.md
- samples/tutorial/main.go
- samples/tutorial/setup.go
It has code snippets that were never updated for things like the import path change, etc.
> samples/tutorial: refresh tutorial README for recent changes, and add Azure

- .travis.yml
> travis: disable windows builds for now instead of allowing them to fail

- pubsub/acks_test.go
> pubsub: deflake ack error test

- internal/secrets/awskms/example_test.go
- internal/secrets/awskms/kms.go
- internal/secrets/awskms/kms_test.go
- internal/secrets/awskms/testdata/TestConformance/TestEncryptDecrypt.yaml
- internal/secrets/driver/driver.go
- internal/secrets/gcpkms/example_test.go
> internal/secret: add an AWS KMS implementation

- pubsub/pubsub.go
Change them from functions to variables.
See #1131.
> pubsub: reduce godoc presence of NewTopic and NewSubscription

- README.md
- blob/blob.go
- runtimevar/runtimevar.go
- secrets/secrets.go
> blob, secrets, runtimevar: hide New functions

- README.md
all: Update Contributing section in README to include all targeted providers 
Fixes #1148
> all: Update Contributing section in README to include all targeted providers 

- internal/trace/trace.go
- internal/trace/trace_test.go
Set the trace status code to the gcerrors.Code.
> internal/trace: incorporate gcerrors

- internal/imports/index.html
- internal/imports/makeimports.sh
Fix the message you see before redirected.
While we're at it, use a separate file for index.html instead
of trying to twist the template file into the right shape.
> internal/imports: improve index.html

- go.mod
- go.sum
- internal/contributebot/go.sum
I had trouble updating this dependency before with all of the other ones (in #1155), but it seems to be OK now.
> all: update etcd dependency

- samples/gcmsg/main.go
- samples/guestbook/aws/main.tf
- samples/tutorial/README.md
> docs: update 'Go Cloud' to 'Go CDK' in samples

- blob/blob_test.go
- blob/driver/driver.go
- gcerrors/errors.go
- internal/gcerr/gcerr.go
- pubsub/acks_test.go
- pubsub/driver/driver.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/mempubsub/mem.go
- pubsub/pub_test.go
- pubsub/pubsub.go
- pubsub/pubsub_test.go
- pubsub/rabbitpubsub/rabbit.go
- pubsub/sub_test.go
Wrap driver errors using the gcerrors package.
> pubsub: wrap errors with gcerrors

- aws/awscloud/awscloud.go
- blob/example_test.go
- blob/gcsblob/gcsblob.go
- gcerrors/errors.go
- mysql/rdsmysql/main.tf
- postgres/rdspostgres/main.tf
- pubsub/rabbitpubsub/doc.go
- pubsub/rabbitpubsub/rabbit.go
- tests/aws/main.tf
> docs: update 'Go Cloud' to 'Go Cloud Development Kit' or 'Go CDK' in code+comments

- blob/blob.go
- blob/drivertest/drivertest.go
- runtimevar/drivertest/drivertest.go
- runtimevar/runtimevar.go
> runtime, blob: make ErrorAs panic on nil or non-pointer target

- secrets/awskms/kms.go
- secrets/driver/driver.go
- secrets/gcpkms/kms.go
- secrets/localsecrets/localsecrets.go
- secrets/localsecrets/localsecrets_test.go
- secrets/secrets.go
- secrets/secrets_test.go
- secrets/vault/vault.go
> secrets: use gcerrors

- secrets/awskms/kms_test.go
- secrets/gcpkms/kms_test.go
- secrets/vault/vault_test.go
> secrets: improve test coverages by testing fail connections

- runtimevar/blobvar/blobvar.go
- runtimevar/blobvar/blobvar_test.go
- runtimevar/constantvar/constantvar.go
- runtimevar/constantvar/constantvar_test.go
- runtimevar/constantvar/example_test.go
- runtimevar/driver/driver.go
- runtimevar/drivertest/drivertest.go
- runtimevar/etcdvar/etcdvar.go
- runtimevar/etcdvar/etcdvar_test.go
- runtimevar/filevar/filevar.go
- runtimevar/filevar/filevar_test.go
- runtimevar/paramstore/paramstore.go
- runtimevar/paramstore/paramstore_test.go
- runtimevar/runtimeconfigurator/runtimeconfigurator.go
- runtimevar/runtimeconfigurator/runtimeconfigurator_test.go
- runtimevar/runtimevar.go
- runtimevar/runtimevar_test.go
> runtimevar: use gcerrors

- gcerrors/errors.go
- internal/gcerr/errorcode_string.go
- internal/gcerr/gcerr.go
These both came up as useful codes in the review of #1207.
Also, run stringer.
> gcerrors: add PermissionDenied and ResourceExhausted

- secrets/secrets.go
- secrets/secrets_test.go
Also, restore and expand trace test.
> secrets: add metrics

- blob/blob.go
- blob/oc_test.go
- go.mod
> blob: add metrics for bytes read and written

- blob/blob.go
- secrets/secrets.go
Explain naming and give examples.
> blob,secrets: improve OpenCensus doc

- blob/blob_test.go
`TestOpenCensus` still fails but I'm hoping you'll fix that :-).
Updates #1240
> blob/tests: TestOpen now works with -count > 1

- pubsub/rabbitpubsub/example_test.go
- pubsub/rabbitpubsub/rabbit.go
- samples/gcmsg/rabbit.go
> pubsub: add options structs to rabbit topic and subscription constructors

- internal/escape/escape.go
- internal/escape/escape_test.go
> all: add a utility package for escaping/unescaping strings

- pubsub/awspubsub/awspubsub_test.go
> pubsub: add TestOpenTopic, TestOpenSubscription to awspubsub_test

- pubsub/awspubsub/awspubsub.go
- pubsub/awspubsub/awspubsub_test.go
- pubsub/azurepubsub/azurepubsub.go
- pubsub/azurepubsub/azurepubsub_test.go
- pubsub/drivertest/drivertest.go
- pubsub/rabbitpubsub/doc.go
- pubsub/rabbitpubsub/rabbit.go
Various things I noticed. Most of the changes are from running `gofmt`.
> pubsub: various test, golint, docstring fixes; run gofmt

- go.sum
This should help address #1277
> all: Remove erroring lines from go.sum and rerun go tools, go test passes now

- pubsub/awspubsub/awspubsub_test.go
- pubsub/gcppubsub/gcppubsub_test.go
> pubsub: dynamically create topics and subscriptions in AWS and GCP benchmarks

- internal/contributebot/go.sum
- pubsub/pubsub_test.go
> pubsub: add test to check for goroutine leakage in Shutdown methods

- secrets/awskms/kms.go
- secrets/awskms/kms_test.go
Support error codes used for Decrypt and Encrypt.
Update #1206
> secrets/awskms: support relevant error codes

- internal/admin/repository/main.tf
Output of `terraform plan`:
-----------------
```
-----------------------------------------------------------------------
+ create
- destroy
+ module.go_cloud_repo.github_issue_label.P0
id:         <computed>
color:      "990000"
etag:       <computed>
name:       "P0"
repository: "go-cloud"
url:        <computed>
+ module.go_cloud_repo.github_issue_label.P1
id:         <computed>
color:      "ff6666"
etag:       <computed>
name:       "P1"
repository: "go-cloud"
url:        <computed>
- module.go_cloud_repo.github_issue_label.at_risk
- module.go_cloud_repo.github_issue_label.high_priority
+ module.wire_repo.github_issue_label.P0 …
```
> admin: Modify our Github priority labels to P0-P1 (and implied unassigned)

- samples/guestbook/README.md
- samples/guestbook/main.go
> samples/guestbook: Update README for AWS guestbook so that it works

- pubsub/azurepubsub/azurepubsub.go
- pubsub/azurepubsub/azurepubsub_test.go
> pubsub/azurepubsub: fix broken test for Subscription Error.As

- secrets/example_test.go
> secrets/test: add an example for the concrete type.

- internal/contributebot/setup.go
- internal/contributebot/wire_gen.go
The build is broken right now so I'll submit after anybody approves.
> contributebot: fix build broken by #1346 + #1347

- internal/testing/runchecks.sh
Don't remove goveralls -> coveralls yet, we can do both for a while.
Updates #1353.
> travis: try using codecov

- internal/contributebot/prod/k8s/contributebot.yaml
Successfully deployed to production GKE cluster.
Fixes #637
> internal/contributebot: update deployed image to pick up changes in #1347

- .codecov.yml
> codecov: disable PR comments

- .travis.yml
- internal/website/config.toml
Copying the same setup as in https://github.com/zombiezen/gg
> travis: run Hugo to deploy GitHub pages

- samples/tutorial/README.md
> samples/tutorial: add mention of AWS_REGION environment variable

- .travis.yml
- README.md
- internal/testing/runchecks.sh
> travis: remove coveralls, only use codecov

- samples/gcmsg/url.go
- samples/gcmsg/url_test.go
> samples: show a human-friendly error msg when topic urls are used for subscription urls

- blob/example_test.go
> blob: examples of additional As() methods

- internal/admin/main.tf
> internal/admin: change GitHub repository website to gocloud.dev

- internal/admin/repository/main.tf
To better align with internal labels for the repo sync
```
+ create
+ module.go_cloud_repo.github_issue_label.process
id:          <computed>
color:       "a2aaef"
description: "Improvement to the engineering process"
etag:        <computed>
name:        "process"
repository:  "go-cloud"
url:         <computed>
+ module.wire_repo.github_issue_label.process
id:          <computed>
color:       "a2aaef"
description: "Improvement to the engineering process"
etag:        <computed>
name:        "process"
repository:  "wire"
url:         <computed>
```
> admin: add "process" label for issues

- secrets/secrets.go
- secrets/secrets_test.go
Updates #1174.
I'll add the per-driver openers in a separate PR.
> secrets: add infrastructure for opening Keepers via URL

- aws/aws.go
- blob/s3blob/s3blob.go
- samples/guestbook/wire_gen.go
> aws: set SharedConfigState=true by default

- .codecov.yml
They still come sometimes for some reason (e.g., #1436), and I actually like them. The cost seems low.
> codecov: re-enable comments

- blob/example_test.go
> blob: add example of ErrorAs

- secrets/azurekeyvault/example_test.go
Example test for #1315 ; adds to #76
> secrets: add Azure KeyVault Example

- pubsub/awspubsub/awspubsub.go
- pubsub/azurepubsub/azurepubsub.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/pubsub.go
- pubsub/rabbitpubsub/rabbit.go
> pubsub: rename target argument of ErrorAs to i, for consistency with As

- mysql/mysql.go
- mysql/mysql_test.go
New URL design implementation for MySQL, related to the https://github.com/google/go-cloud/issues/1175
> mysql: OpenUrl implementation

- blob/s3blob/s3blob.go
Be compatible with CEPH as blob store provider
See https://tracker.ceph.com/issues/37801 for the bug report with the CEPH project.
> blob/s3blob: support v1 ListObjects

- pubsub/pubsub.go
> pubsub: factor out common URL code

- runtimevar/runtimevar.go
- runtimevar/runtimevar_test.go
> runtimevar: implement health.Checker

- pubsub/awspubsub/awspubsub_test.go
Not sure what this was for, but it's all completely unused.
> pubsub/awspubsub: remove unused code in test

- runtimevar/blobvar/blobvar_test.go
- runtimevar/filevar/filevar.go
- runtimevar/filevar/filevar_test.go
> runtimevar: fix tests for blobvar and filevar on Windows

- blob/blob.go
- internal/openurl/openurl.go
- internal/openurl/openurl_test.go
- pubsub/pubsub.go
- runtimevar/runtimevar.go
- secrets/secrets.go
> all: save api on openurl.SchemeMap so it doesn't have to be passed to From*

- runtimevar/example_openvariable_test.go
> runtimevar: add an example for OpenVariable

- runtimevar/example_test.go
> runtimevar: update examples to use Latest; add one for Watch

- secrets/azurekeyvault/akv_test.go
- secrets/azurekeyvault/testdata/TestConformance/TestAs/verify_As_function.yaml
- secrets/azurekeyvault/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.yaml
- secrets/azurekeyvault/testdata/TestConformance/TestDecryptMalformedError.yaml
- secrets/azurekeyvault/testdata/TestConformance/TestEncryptDecrypt.yaml
- secrets/azurekeyvault/testdata/TestConformance/TestMultipleEncryptionsNotEqual.yaml
- secrets/azurekeyvault/testdata/TestConformance/TestMultipleKeys.yaml
Also changed the `initEnv` to check the environment setup instead of setting up.
> secrets/azurekeyvault: record the tests with Go CDK team project

- runtimevar/example_test.go
> runtimevar: add example of Snapshot.As

- runtimevar/example_test.go
> runtimevar: add example of Variable.ErrorAs

- internal/testing/runchecks.sh
Fixes the master build breakage from #1504 
Now the approach is "safe path by default". If the script can't determine the existence of the right env vars, it defaults to just running tests as usual
> testing: only skip tests for PRs

- blob/blob_test.go
- pubsub/pubsub_test.go
- runtimevar/runtimevar_test.go
- secrets/secrets_test.go
The fake Opener is more obvious, and this adds coverage for `OpenXXXURL`.
Updates #1174.
> all/tests: clean up and improve coverage for URLMux tests

- secrets/example_test.go
> secrets: add example for Keeper.ErrorAs

- blob/blob.go
- pubsub/pubsub.go
- runtimevar/runtimevar.go
- secrets/secrets.go
> doc: update docstrings to point to main doc.go for URLs

- pubsub/awspubsub/awspubsub.go
- pubsub/awspubsub/awspubsub_test.go
- pubsub/awspubsub/example_test.go
- pubsub/azurepubsub/azurepubsub.go
- pubsub/azurepubsub/azurepubsub_test.go
- pubsub/azurepubsub/example_test.go
- pubsub/example_open_test.go
- pubsub/gcppubsub/example_test.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/gcppubsub/gcppubsub_test.go
- pubsub/mempubsub/example_test.go
- pubsub/mempubsub/mem.go
- pubsub/mempubsub/mem_test.go
- pubsub/rabbitpubsub/doc.go
- pubsub/rabbitpubsub/example_test.go
- pubsub/rabbitpubsub/rabbit.go
- pubsub/rabbitpubsub/rabbit_test.go
> pubsub: add URLOpeners for all drivers

- blob/blob_test.go
- blob/example_openbucket_test.go
- doc.go
- internal/openurl/openurl.go
- internal/openurl/openurl_test.go
- pubsub/pubsub_test.go
- runtimevar/example_openvariable_test.go
- runtimevar/runtimevar_test.go
- secrets/example_openkeeper_test.go
- secrets/secrets_test.go
> all: add support for API-specific scheme prefixes for URLs

- go.mod
- go.sum
- internal/contributebot/go.mod
- internal/contributebot/go.sum
- internal/testing/alldeps
Update the cloud.google.com/go module to the latest version.
> go.mod: update cloud.google.com/go

- secrets/awskms/kms.go
- secrets/awskms/kms_test.go
- secrets/azurekeyvault/akv.go
- secrets/driver/driver.go
- secrets/gcpkms/kms.go
- secrets/gcpkms/kms_test.go
- secrets/localsecrets/example_test.go
- secrets/localsecrets/localsecrets.go
- secrets/localsecrets/localsecrets_test.go
- secrets/secrets.go
- secrets/vault/example_test.go
- secrets/vault/vault.go
- secrets/vault/vault_test.go
> secrets: rework URL comments for consistency, and update vault to use environment variables for the default opener

- secrets/azurekeyvault/akv.go
- secrets/azurekeyvault/akv_test.go
- secrets/azurekeyvault/example_test.go
- secrets/gcpkms/kms_test.go
> secrets: add tests to increase coverage

- samples/guestbook/main.go
> samples/guestbook: use runtimevar.Latest instead of Watch

- internal/openurl/openurl.go
> all: improve error message for unknown scheme to include list of available schemes

- pubsub/natspubsub/example_test.go
- pubsub/natspubsub/nats.go
- pubsub/natspubsub/nats_test.go
> pubsub/natspubsub: add an ackFunc to the Subscription constructor

- pubsub/natspubsub/nats_test.go
The tests I removed are covered by conformance tests, except for `ErrorAs`, which I covered elsewhere.
I also disabled a test which is flaky due to #1556.
> pubsub/nats: remove some tests that are covered by conformance tests

- runtimevar/runtimevar_test.go
This technique is simpler; I didn't know about `time.AfterFunc` :-|.
> runtimevar/test: use time.AfterFunc in tests instead of goroutine+Sleep

- postgres/postgres.go
- postgres/postgres_test.go
> postgres: spin up a PostgreSQL database to test URL opener

- blob/drivertest/drivertest.go
- internal/docstore/driver/codec_test.go
- internal/testing/setup/setup.go
- pubsub/acks_test.go
- samples/guestbook/main.go
> gofmt -s + typo diffrent

- internal/testing/runchecks.sh
Fixes https://github.com/google/go-cloud/issues/1588
Added a check to run `gofmt -s -d` and verify there isn't any change
> travis: add a check that "gofmt -s" doesn't change anything

- samples/gcmsg/main.go
> samples/gcmsg: add NATS to gcmsg sample

- postgres/rdspostgres/rdspostgres.go
- postgres/rdspostgres/rdspostgres_test.go
New URL design implementation for RDS PostgreSQL, related to the #1175
> postgres: RDS PostgreSQL OpenUrl implementation

- internal/website/content/internal/docstore/dynamodocstore/_index.md
- internal/website/content/internal/docstore/firedocstore/_index.md
- internal/website/content/internal/docstore/internal/fields/_index.md
- internal/website/content/internal/openurl/_index.md
- internal/website/content/mysql/_index.md
- internal/website/content/postgres/_index.md
- internal/website/content/pubsub/awssnssqs/_index.md
- internal/website/content/pubsub/azuresb/_index.md
- internal/website/content/pubsub/natspubsub/_index.md
- internal/website/content/secrets/azurekeyvault/_index.md
I played it safe on this one: this doesn't remove any stale packages, just meta tags for new import paths.
> internal/website: add new import pages

- pubsub/acks_test.go
- pubsub/awssnssqs/awssnssqs.go
- pubsub/awssnssqs/awssnssqs_test.go
- pubsub/azuresb/azuresb.go
- pubsub/benchmark_test.go
- pubsub/drivertest/drivertest.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/gcppubsub/gcppubsub_test.go
- pubsub/mempubsub/mem.go
- pubsub/natspubsub/nats.go
- pubsub/natspubsub/nats_test.go
- pubsub/pubsub.go
- pubsub/pubsub_test.go
- pubsub/rabbitpubsub/rabbit.go
- pubsub/rabbitpubsub/rabbit_test.go
- pubsub/sub_test.go
> pubsub: use fixedBatchSize int instead of dynamicBatchSize bool 

- pubsub/benchmark_test.go
These changes are to better illustrate the delta between HEAD and an upcoming PR to issue `ReceiveBatch` calls before the queue is empty.
Updates #1644.
> pubsub/tests: lengthen simulation time, and smooth datapoints; add a new sim profile

- pubsub/rabbitpubsub/fake_test.go
> pubsub/rabbit: fix data race in fake

- pubsub/pubsub.go
There's no need to make the driver.Batcher do the conversion from `pubsub.Message` to `driver.Message`.
> pubsub: convert to driver.Message earlier; clarify docstring for newBatcher funcs

- pubsub/drivertest/drivertest.go
I was seeing some occasional `martian` errors during replay, but it wasn't causing the test to fail. I think it was because `testCancelSendReceive` was cancelling the ctx it gave for cleanup functions, so cleanup was failing (but not being checked).
> pubsub/tests: check for errors during Shutdown

- runtimevar/runtimevar.go
> runtimevar: use RWMutex

- internal/docstore/driver/document.go
- internal/docstore/driver/document_test.go
Documents can only be constructed from non-nil struct pointers and maps.
Also, rewrite `Document.Decode` so it looks like `Document.Encode`. This lets us add a check in the top-level `Decode` method that the first argument is settable. (A `Document` that is a map is not settable, but that's never a problem because it will always have its fields set, not the document itself.)
> docstore/driver: make NewDocument stricter

- pubsub/azuresb/azuresb_test.go
> pubsub/azuresb: make sure to keep topics/subscriptions unique when trimming them

- pubsub/azuresb/azuresb.go
- pubsub/azuresb/azuresb_test.go
Fixes #1699.
cc/ @vsaroopchand
> pubsub/azuresb: cache amqp connection

- pubsub/pubsub.go
> pubsub/doc: fix typo in delivery types section

- runtimevar/runtimevar.go
For #1782
This should show the actually useful documentation of this function in the godoc, and list its arguments
> runtimevar: Expose DecoderByName directly

- mysql/azuremysql/azuremysql_test.go
- mysql/azuremysql/main.tf
> mysql: Add Terraform Automation for Azure MySQL 

- internal/docstore/drivertest/drivertest.go
- internal/docstore/mongodocstore/mongo.go
- internal/docstore/mongodocstore/query.go
> mongo: queries

- blob/azureblob/azureblob.go
- blob/gcsblob/gcsblob.go
- blob/gcsblob/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.yaml
- blob/gcsblob/testdata/TestConformance/TestAs/verify_ContentLanguage_can_be_written_and_read_through_As.yaml
- blob/gcsblob/testdata/TestConformance/TestCopy/NonExistentSourceFails.yaml
- blob/gcsblob/testdata/TestConformance/TestCopy/Works.yaml
> blob/gcsblob: implement Copy

- .gitignore
- internal/cmd/gocdk/add.go
- internal/cmd/gocdk/apply.go
- internal/cmd/gocdk/build.go
- internal/cmd/gocdk/build_test.go
- internal/cmd/gocdk/deploy.go
- internal/cmd/gocdk/go.mod
- internal/cmd/gocdk/go.sum
- internal/cmd/gocdk/init.go
- internal/cmd/gocdk/launch.go
- internal/cmd/gocdk/main.go
- internal/cmd/gocdk/main_test.go
- internal/cmd/gocdk/serve.go
- internal/website/content/internal/cmd/gocdk/_index.md
Adds skeletal structure and `build --list`
/cc @vangent @eliben
> internal/cmd/gocdk: first commit

- health/health.go
Convenience type similar to `http.HandlerFunc`. I would like to get this into the release if possible.
> health: add CheckerFunc type

- internal/website/content/ref/server.md
> doc: add link to new server sample on the website

- pubsub/acks_test.go
- pubsub/awssnssqs/awssnssqs.go
- pubsub/azuresb/azuresb.go
- pubsub/driver/driver.go
- pubsub/drivertest/drivertest.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/mempubsub/mem.go
- pubsub/natspubsub/nats.go
- pubsub/pub_test.go
- pubsub/pubsub.go
- pubsub/pubsub_test.go
- pubsub/rabbitpubsub/rabbit.go
- pubsub/sub_test.go
> pubsub: add a Close method to both driver.Topic and driver.Subscription

- internal/docstore/memdocstore/mem.go
- internal/docstore/memdocstore/mem_test.go
> internal/docstore/memdocstore: add URL opener

- blob/azureblob/azureblob.go
- blob/azureblob/azureblob_test.go
- blob/drivertest/drivertest.go
- blob/gcsblob/gcsblob.go
- blob/gcsblob/gcsblob_test.go
- blob/s3blob/s3blob.go
- blob/s3blob/s3blob_test.go
> blob: implement BeforeCopy As hook for all drivers; cleanup Unimplemented checks

- internal/testing/alldeps
- internal/testing/listdeps.sh
- internal/testing/runchecks.sh
Forgot to do this in earlier PRs.
> internal/testing: include gocdk CLI module

- samples/gocdk-blob/main.go
> samples/blob: download goes to stdout; add upload from stdin and ls commands

- internal/docstore/driver/codec.go
- internal/docstore/driver/codec_test.go
Add tests to exercise more the codec framework.
> docstore/driver: improve codec coverage

- secrets/awskms/example_test.go
- secrets/awskms/kms.go
- secrets/awskms/kms_test.go
- secrets/azurekeyvault/akv.go
- secrets/azurekeyvault/akv_test.go
- secrets/azurekeyvault/example_test.go
- secrets/gcpkms/example_test.go
- secrets/gcpkms/kms.go
- secrets/gcpkms/kms_test.go
- secrets/vault/example_test.go
- secrets/vault/vault.go
- secrets/vault/vault_test.go
> runtimevar/all: use OpenKeeper consistently BREAKING_CHANGE_OK

- blob/blob.go
- internal/website/content/howto/_index.md
- internal/website/content/howto/blob/_index.md
- internal/website/content/howto/blob/data.md
- internal/website/content/howto/blob/open-bucket.md
- internal/website/content/howto/pubsub/_index.md
- internal/website/content/howto/pubsub/publish.md
- internal/website/content/howto/pubsub/subscribe.md
- internal/website/content/ref/blob.md
- internal/website/content/ref/pubsub.md
- pubsub/pubsub.go
The secrets guide is still under development, so not publishing yet.
Updates #1576
> internal/website: publish blob and pub/sub how-to guides

- internal/contributebot/setup.go
- internal/contributebot/wire_gen.go
- runtimevar/awsparamstore/awsparamstore.go
- runtimevar/awsparamstore/awsparamstore_test.go
- runtimevar/awsparamstore/example_test.go
- runtimevar/blobvar/blobvar.go
- runtimevar/blobvar/example_test.go
- runtimevar/etcdvar/etcdvar.go
- runtimevar/etcdvar/etcdvar_test.go
- runtimevar/etcdvar/example_test.go
- runtimevar/filevar/example_test.go
- runtimevar/filevar/filevar.go
- runtimevar/filevar/filevar_test.go
- runtimevar/gcpruntimeconfig/example_test.go
- runtimevar/gcpruntimeconfig/gcpruntimeconfig.go
- runtimevar/gcpruntimeconfig/gcpruntimeconfig_test.go
- runtimevar/httpvar/example_test.go
- runtimevar/httpvar/httpvar.go
- runtimevar/httpvar/httpvar_test.go
- samples/guestbook/inject_aws.go
- samples/guestbook/inject_azure.go
- samples/guestbook/inject_gcp.go
- samples/guestbook/inject_local.go
- samples/guestbook/wire_gen.go
> runtimevar: use OpenVariable as constructor consistently

- blob/blob.go
- secrets/awskms/example_test.go
- secrets/awskms/kms.go
- secrets/awskms/kms_test.go
- secrets/azurekeyvault/akv.go
- secrets/azurekeyvault/akv_test.go
- secrets/azurekeyvault/example_test.go
- secrets/driver/driver.go
- secrets/example_openkeeper_test.go
- secrets/example_test.go
- secrets/gcpkms/example_test.go
- secrets/gcpkms/kms.go
- secrets/gcpkms/kms_test.go
- secrets/localsecrets/example_test.go
- secrets/localsecrets/localsecrets.go
- secrets/localsecrets/localsecrets_test.go
- secrets/secrets.go
- secrets/secrets_test.go
- secrets/vault/example_test.go
- secrets/vault/vault.go
- secrets/vault/vault_test.go
> secrets/all: add a Close function to Keeper and driver.Keeper

- internal/cmd/gocdk/apply.go
- internal/cmd/gocdk/apply_test.go
- internal/cmd/gocdk/biome.go
- internal/cmd/gocdk/biome_test.go
- internal/cmd/gocdk/go.mod
- internal/cmd/gocdk/go.sum
- internal/cmd/gocdk/main.go
- internal/cmd/gocdk/serve.go
Updated xerrors to get fix for https://golang.org/issue/30970
Fixes #1833
> internal/cmd/gocdk: verify serve_enabled before serve

- internal/docstore/dynamodocstore/dynamo.go
- internal/docstore/dynamodocstore/dynamo_test.go
> internal/docstore/dynamodocstore: add URL opener

- internal/docs/design.md
The issue referenced has been closed.
For modules there's some new thinking about the future direction now, but better leave it out to avoid rotting.
> doc: remove outdated information from design.md

- internal/docstore/firedocstore/fs.go
- internal/docstore/firedocstore/fs_test.go
> internal/docstore/firedocstore: add URL opener

- mysql/cloudmysql/cloudmysql.go
- mysql/cloudmysql/cloudmysql_test.go
- mysql/cloudmysql/example_test.go
- postgres/cloudpostgres/cloudpostgres.go
- postgres/cloudpostgres/cloudpostgres_test.go
- postgres/cloudpostgres/example_test.go
- samples/guestbook/wire_gen.go
> all: add cleanup functions to Cloud SQL Open function returns

- internal/docstore/mongodocstore/mongo.go
- internal/docstore/mongodocstore/mongo_test.go
Also, support id field URL parameter.
> mongodocstore: use two Open functions instead of options

- internal/admin/repository/main.tf
`terraform plan` output:
```
+ create
+ module.go_cloud_repo.github_issue_label.good_first_issue
id:          <computed>
color:       "7057ff"
description: "Good for newcomers"
etag:        <computed>
name:        "good first issue"
repository:  "go-cloud"
url:         <computed>
+ module.wire_repo.github_issue_label.good_first_issue
id:          <computed>
color:       "7057ff"
description: "Good for newcomers"
etag:        <computed>
name:        "good first issue"
repository:  "wire"
url:         <computed>
Plan: 2 to add, 0 to change, 0 to destroy.
```
> internal/admin: add 'good first issue' label

- internal/docstore/driver/driver.go
- internal/docstore/dynamodocstore/query.go
- internal/docstore/firedocstore/query.go
- internal/docstore/memdocstore/query.go
- internal/docstore/mongodocstore/query.go
- internal/docstore/query.go
> internal/docstore: portable API as support for query

- internal/website/gatherexamples/gatherexamples.go
- internal/website/gatherexamples/gatherexamples_test.go
Sorry for missing this in the first go-around, but after converting the
blob how-to guide, I realized this needed some fine-tuning.
-  separate imports from code in output
-  add blank import directive
-  remove "log" import (noise)
-  use `go/format` to serialize AST to make elastic tabs render correctly
Updates #1827
> internal/website/gatherexamples: add features based on usage in blob how-to guides

- pubsub/awssnssqs/awssnssqs.go
- pubsub/awssnssqs/awssnssqs_test.go
- pubsub/azuresb/azuresb.go
- pubsub/azuresb/azuresb_test.go
- pubsub/driver/driver.go
- pubsub/drivertest/drivertest.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/gcppubsub/gcppubsub_test.go
- pubsub/mempubsub/mem.go
- pubsub/natspubsub/nats.go
- pubsub/natspubsub/nats_test.go
- pubsub/pubsub.go
- pubsub/rabbitpubsub/doc.go
- pubsub/rabbitpubsub/rabbit.go
- pubsub/rabbitpubsub/rabbit_test.go
> pubsub/all: add an Message.BeforeSend As hook

- blob/gcsblob/gcsblob.go
- blob/gcsblob/gcsblob_test.go
- blob/gcsblob/testdata/TestConformance/TestAs/verify_ContentLanguage_can_be_written_and_read_through_As.yaml
- blob/gcsblob/testdata/TestPreconditions.yaml
> blob/gcsblob: expose storage.ObjectHandle via As

- internal/docstore/dynamodocstore/dynamo.go
> internal/docstore/dynamodocstore: add docstring for supported as types

- pubsub/kafkapubsub/kafka.go
- pubsub/kafkapubsub/kafka_test.go
> pubsub/kafkapubsub: implement As functions

- pubsub/drivertest/drivertest.go
I saw a flake on Travis for a timeout on one of these; we'll see if making it 30s instead of 15s helps.
> pubsub/tests: increase timeout

- internal/testing/setup/setup.go
- secrets/azurekeyvault/akv_test.go
> tests: refactor creation of httpreplay.Recorder into common code

- secrets/awskms/kms_test.go
- secrets/awskms/testdata/TestConformance/TestAs/verify_As_function.replay
- secrets/awskms/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.replay
- secrets/awskms/testdata/TestConformance/TestDecryptMalformedError.replay
- secrets/awskms/testdata/TestConformance/TestEncryptDecrypt.replay
- secrets/awskms/testdata/TestConformance/TestMultipleEncryptionsNotEqual.replay
- secrets/awskms/testdata/TestConformance/TestMultipleKeys.replay
> secrets/awskms: use httpreplay for conformance tests

- internal/docstore/driver/codec.go
- internal/docstore/driver/codec_test.go
- internal/docstore/dynamodocstore/codec.go
- internal/docstore/firedocstore/codec.go
- internal/docstore/memdocstore/codec.go
- internal/docstore/mongodocstore/codec.go
> docstore: remove isStruct argument from EncodeMap

- internal/docstore/docstore.go
- internal/docstore/driver/driver.go
- internal/docstore/dynamodocstore/dynamo.go
- internal/docstore/firedocstore/fs.go
- internal/docstore/memdocstore/mem.go
- internal/docstore/mongodocstore/mongo.go
> internal/docstore: add BeforeDo function for action list

- internal/docs/design.md
Paying off debt from last week's discussion now that I have a better idea of how conformance tests work :-)
> doc: clarify rerunning single tests in conformance

- server/server.go
- server/server_test.go
> server: fix to start span before logging

- internal/cmd/gocdk/add.go
- internal/cmd/gocdk/apply.go
- internal/cmd/gocdk/apply_test.go
- internal/cmd/gocdk/biome.go
- internal/cmd/gocdk/biome_test.go
- internal/cmd/gocdk/build.go
- internal/cmd/gocdk/build_test.go
- internal/cmd/gocdk/deploy.go
- internal/cmd/gocdk/flagset.go
- internal/cmd/gocdk/flagset_test.go
- internal/cmd/gocdk/init.go
- internal/cmd/gocdk/launch.go
- internal/cmd/gocdk/main.go
- internal/cmd/gocdk/main_test.go
- internal/cmd/gocdk/serve.go
- internal/cmd/gocdk/serve_test.go
- internal/cmd/gocdk/signal_unix.go
- internal/cmd/gocdk/signal_windows.go
- internal/docstore/query.go
- internal/docstore/query_test.go
- internal/website/gatherexamples/gatherexamples.go
- internal/website/gatherexamples/gatherexamples_test.go
- internal/website/gatherexamples/run.sh
I am not sure where these are coming from, it looks like copypasta but all of the copyrights in the repo have been updated for some time....
> all: fix some copyright comments

- internal/cmd/gocdk/fswatch.go
- internal/cmd/gocdk/fswatch_test.go
- internal/cmd/gocdk/serve.go
> internal/cmd/gocdk: listen for filesystem changes

- internal/docstore/dynamodocstore/dynamo.go
> internal/docstore/dynamodocstore: add beforeDo for acitons

- pubsub/kafkapubsub/kafka.go
> pubsub/kafkapubsub: fix data race; mu.Unlock should have defer

- aws/aws.go
- blob/s3blob/s3blob.go
- internal/docstore/dynamodocstore/dynamo.go
- internal/docstore/dynamodocstore/dynamo_test.go
- pubsub/awssnssqs/awssnssqs.go
- runtimevar/awsparamstore/awsparamstore.go
- samples/guestbook/wire_gen.go
- secrets/awskms/kms.go
> aws: add and use NewDefaultSession

- internal/cmd/gocdk/build.go
> internal/cmd/gocdk: implement build command

- internal/testing/runchecks.sh
Main module tests already run earlier in the script.
We'll have to figure out how to split the modules to different "classes" whatever approach we choose. For now, this makes tests faster again :)
> testing: don't repeat main module tests

- allmodules
- internal/testing/alldeps
Followup on #2057 
....ShameCube
> samples: fix samples path in allmodules

- internal/cmd/gocdk/add_api_test.go
- internal/testing/runchecks.sh
**High priority: tests currently reporting false positives.**
Fixed compile failure uncovered by tests.
> internal/testing: fix errors found by shellcheck

- requestlog/ncsa.go
- requestlog/stackdriver.go
- server/server.go
Also fix behavior of new(server.Server)
> requestlog: treat nil onErr as no-op

- internal/docstore/dynamodocstore/dynamo_test.go
> internal/docstore/dynamodocstore: test beforeDo

- README.md
- blob/azureblob/azureblob.go
- blob/azureblob/azureblob_test.go
- blob/drivertest/drivertest.go
- blob/gcsblob/gcsblob_test.go
- blob/s3blob/s3blob.go
- internal/docstore/firedocstore/fs.go
- internal/docstore/memdocstore/mem.go
- mysql/mysql.go
- mysql/mysql_test.go
- pubsub/drivertest/drivertest.go
- runtimevar/constantvar/constantvar_test.go
- samples/server/main.go
- secrets/awskms/example_test.go
- secrets/gcpkms/example_test.go
- secrets/localsecrets/example_test.go
https://goreportcard.com/report/github.com/google/go-cloud
I fixed a bunch of the non-controversial (I think) things it flagged like misspellings and ineffective assignments (it found a few bugs...).
Its `go vet` complaints seem wrong to me.
> all: add link to go reportcard, fix various things it flagged

- internal/cmd/gocdk/go.mod
- internal/cmd/gocdk/go.sum
- internal/cmd/gocdk/launch.go
- internal/cmd/gocdk/main.go
> internal/cmd/gocdk: add Cloud Run launcher

- internal/cmd/gocdk/go.sum
I think your last PR and mine (that added this check) conflicted.
> gocdk: go mod cleanup

- internal/testing/prereleasechecks.sh
- mysql/azuremysql/azuremysql_test.go
This is the basic idea. I couldn't get all of the tests to pass, and left a bunch of TODOs.
Updates #2060.
> tests: add a script for pre-release tests

- internal/testing/runchecks.sh
Fixes #2117.
Sample output running locally (note: some tests are failing because they are the prerelease tests and I've run Terraform for them).
You can also obviously check the Travis output.
```
$ ./internal/testing/runchecks.sh 
******************************
* Checking module: .
******************************
Running Go tests...
?   	gocloud.dev	[no test files]
ok  	gocloud.dev/aws	(cached)
ok  	gocloud.dev/aws/awscloud	(cached) [no tests to run]
?   	gocloud.dev/aws/rds	[no test files]
?   	gocloud.dev/azure/azurecloud	[no test files]
?   	gocloud.dev/azure/azuredb	[no test files]
ok  	gocloud.dev/blob	(cached)
ok  	gocloud.dev/blob/azureblob	(cached)
?   	gocloud.dev/blob/driver	[no test files]
?   	gocloud.dev/blob/drivertest	[no test files]
ok  	gocloud.dev/blob/fileblob	(cached) …
```
> runchecks: run all checks for all modules

- internal/website/content/howto/pubsub/publish.md
- internal/website/content/howto/pubsub/subscribe.md
- pubsub/pubsub.go
Update the HOW TO docs for changes from https://github.com/google/go-cloud/pull/2158.
> docs: update pubsub docs for recent changes

- internal/testing/runchecks.sh
... looking at how Travis will take it, for now
> testing: enable the test-summary tool for runchecks

- internal/testing/test-summary/test-summary_test.go
> testing: generic path expectations in test-summary_test

- internal/testing/test-summary/test-summary.go
> testing: don't include packages in failure summary

- internal/testing/test-summary/test-summary.go
Fixes #2205
Note: storing all output is unnecessary, but this leads to the simplest code. Given that our tests for the root module (the largest one) have a total output of ~1.2MB in JSON, I won't do premature optimizations
> testing: test-summary will print output for failing tests

- internal/docstore/driver/codec.go
- internal/docstore/driver/codec_test.go
- internal/docstore/drivertest/drivertest.go
- internal/docstore/dynamodocstore/codec.go
- internal/docstore/dynamodocstore/codec_test.go
- internal/docstore/firedocstore/codec.go
- internal/docstore/firedocstore/doc.go
- internal/docstore/firedocstore/fs_test.go
- internal/docstore/firedocstore/query.go
- internal/docstore/memdocstore/codec.go
- internal/docstore/mongodocstore/codec.go
- internal/docstore/mongodocstore/mongo_test.go
> docstore: remove complex numbers

- internal/testing/releasehelper.go
> testing: fix releasehelper's handling of relative paths to submodules

- secrets/vault/go.mod
- secrets/vault/go.sum
> secrets/vault: upgrade dependency

- internal/cmd/gocdk/launch.go
- internal/cmd/gocdk/launch_test.go
> internal/cmd/gocdk: re-tag image with gcr.io for Cloud Run

- internal/testing/check_api_change.sh
- internal/testing/check_mod_tidy.sh
- internal/testing/runchecks.sh
> internal/travis: run apidiff checks for most modules, not just core

- internal/testing/prereleasechecks.sh
> internal/testing: use correct GCP project ID for Terraform setups

- pubsub/kafkapubsub/localkafka.sh
The kafka test seems flaky lately, so we'll try undoing the recent
change to see if it makes any difference.
> kafkapubsub: revert faster rebalance

- internal/cmd/gocdk/init.go
> internal/gocdk: rename init_ to doInit

- CONTRIBUTING.md
Remove obsolete reference to Sprint milestone.
Add a link to file an issue.
Add missing prepositions and punctuation.
> CONTRIBUTING: Clean up contributing guidelines.

- internal/testing/releasehelper.go
Refactoring prepares for adding new commands, such as bumping versions
for release testing.
> testing: refactor release helper and switch flags to commands

- internal/testing/releasehelper.go
- internal/testing/releasehelper_test.go
The refactoring is to test both runOnGomod and the handlers in a black-box
way. The test creates a temporary directory simulating a small subset of
our repository.
> release: refactor releasehelper for easier testing and add a test.

- internal/docstore/dynamodocstore/dynamo_test.go
- internal/docstore/mongodocstore/codec.go
- internal/docstore/mongodocstore/mongo.go
- internal/docstore/mongodocstore/mongo_test.go
- internal/docstore/mongodocstore/urls.go
- internal/docstore/mongodocstore/urls_test.go
- Move URL handling to separate files.
- Clarify how LowercaseFields works and why we have it.
- Improve testing of LowercaseFields.
> mongodocstore: various changes

- internal/docs/release.md
> release: document new release process

- internal/docs/design.md
> internal/docs: document compound IDs decision

- internal/docstore/firedocstore/example_test.go
- internal/docstore/memdocstore/example_test.go
- internal/docstore/mongodocstore/example_test.go
- internal/docstore/mongodocstore/urls.go
- internal/website/content/howto/docstore/_index.md
- internal/website/content/howto/docstore/open-collection.md
- internal/website/data/examples.json
The page for how to open a collection.
> internal/website: docstore how-to, part 1

- internal/docstore/doc.go
- internal/docstore/docstore.go
- internal/docstore/docstore_test.go
- internal/docstore/driver/driver.go
- internal/docstore/drivertest/driverbenchmark.go
- internal/docstore/drivertest/drivertest.go
- internal/docstore/dynamodocstore/dynamo.go
- internal/docstore/dynamodocstore/example_test.go
- internal/docstore/examples_test.go
- internal/docstore/firedocstore/example_test.go
- internal/docstore/firedocstore/fs.go
- internal/docstore/memdocstore/example_test.go
- internal/docstore/memdocstore/mem.go
- internal/docstore/mongodocstore/example_test.go
- internal/docstore/mongodocstore/mongo.go
- internal/docstore/query.go
- internal/website/data/examples.json
> docstore: add Collection.Close

- internal/docstore/firedocstore/example_test.go
- internal/docstore/firedocstore/fs.go
- internal/docstore/firedocstore/fs_test.go
- internal/docstore/firedocstore/urls.go
- internal/docstore/firedocstore/urls_test.go
- internal/website/data/examples.json
> firedocstore: accept the full collection resource ID as a single string

- internal/cmd/gocdk/internal/launcher/cloudrun.go
- internal/cmd/gocdk/internal/launcher/cloudrun_test.go
- internal/cmd/gocdk/internal/launcher/launcher.go
- internal/cmd/gocdk/launch.go
- internal/website/content/internal/cmd/gocdk/internal/launcher/_index.md
Not changing API yet, that will come in a follow-up PR.
Updates #2046
> internal/cmd/gocdk: factor out launcher code to new package

- internal/cmd/gocdk/serve.go
I didn't read the documentation carefully enough before and now realize
that the dynamic type of an atomic.Value must stay the same. This
intermittently causes panics. The simplest fix I could think of was to
just use a mutex instead.
> internal/cmd/gocdk: use mutex instead of atomic in serve

- internal/docstore/docstore.go
- internal/docstore/example_test.go
> docstore: add ErrorAs example

- internal/testing/prereleasechecks.sh
- mysql/azuremysql/main.tf
> mysql/azuremysql: fix issues preventing test access

- .travis.yml
- internal/cmd/gocdk/apply_test.go
> internal/gocdk: install Terraform on Travis

- docstore/firedocstore/fs.go
> docstore/firedocstore: explain uses for name function

- mysql/rdsmysql/example_test.go
- mysql/rdsmysql/rdsmysql.go
- mysql/rdsmysql/rdsmysql_test.go
- samples/guestbook/inject_aws.go
- samples/guestbook/wire_gen.go
Update Guestbook Wire injection to match.
Updates #1175
> mysql/rdsmysql: remove constructor in favor of URLOpener BREAKING_CHANGE_OK

- CONTRIBUTING.md
- internal/docs/design.md
Also add some supporting references and wording about global state
that I had been meaning to add for a while.
> CONTRIBUTING: add acceptable licenses

- internal/website/content/howto/secrets/open-keeper.md
This is a cleanup on a typo in #2383
> internal/website: correct a typo

- pubsub/kafkapubsub/kafka.go
Fixes #2435.
`consumerGroup.Consume` returns a `nil` error whenever the consumer group is rebalanced. [This example](https://godoc.org/github.com/Shopify/sarama#ConsumerGroup)  makes it clear that the caller is supposed to loop over calls to `Consume`, and only abort if it returns a non-nil error. I missed that in the initial implementation, so the current code stops receiving messages after a rebalance.
We also have to check if `ctx` returns an error, because that happens during shutdown (we've cancelled it). Otherwise `Consume` will just immediately return a `nil` and we'll loop forever.
I tested this by creating a topic with multiple partitions, sending messages with different keys to it, and subscribing with two clients in the same "group". Before this change, the 2nd subscriber would …
> pubsub/kafkapubsub: continue consuming messages after a rebalance

- docstore/dynamodocstore/urls.go
- docstore/dynamodocstore/urls_test.go
- docstore/firedocstore/urls.go
- docstore/firedocstore/urls_test.go
- docstore/memdocstore/urls.go
- docstore/memdocstore/urls_test.go
- docstore/mongodocstore/urls.go
- docstore/mongodocstore/urls_test.go
> docstore: support setting revision field in URLOpeners

- internal/docs/release.md
> docs: update release instructions to update the go.mod built into gocdk

- internal/website/content/howto/secrets/open-keeper.md
- internal/website/data/examples.json
- secrets/azurekeyvault/akv.go
- secrets/azurekeyvault/example_test.go
> docs: add how-to section for secrets/azurekeyvault

- samples/order/frontend_test.go
- samples/order/order.go
- samples/order/processor.go
Some small changes:
- Improve the cleanup logic of the setup function.
- Add a little package doc.
- Remove some dead code.
> samples/order: improve cleanup logic; add package doc

- blob/fileblob/fileblob.go
- blob/fileblob/fileblob_test.go
Add the base_url and secret_key_path query parameters to the URL,
so that fileblob URLs can provide enough information to make
Bucket.SignedURL work.
> blob/fileblob: support URL query params for signed URLs

- pubsub/kafkapubsub/kafka.go
- pubsub/kafkapubsub/kafka_test.go
Fixes #2481.
After much investigation, there is a subtle race condition in tests. Sometimes, the first message sent to the topic is not received on the subscription. I believe this happens when `OpenSubscription` returns before *something* happens. Previous to this PR, we waited until `Setup` was called; after this PR, we additionally wait until all of the expected `ConsumeClaim` calls happen.
I also improved the test to verify that both subscriptions get some messages.
> pubsub/kafka: wait until consumer claims are added before returning from OpenSubscription

- internal/testing/runchecks.sh
Just removing the special case I added while debugging.
> internal/tests: remove special case chattiness for kafka

- internal/website/content/howto/server/_index.md
> internal/website: Remove draft, add TOC to server howto

- internal/cmd/gocdk/deploy.go
- internal/cmd/gocdk/testdata/deploy-help.ct
I unintentionally changed this behavior as part of #2509.
> internal/gocdk: restore default behavior for deploy to do a build

- internal/cmd/gocdk/build.go
- internal/cmd/gocdk/deploy.go
- internal/cmd/gocdk/testdata/build-help.ct
- internal/cmd/gocdk/testdata/deploy-help.ct
- internal/cmd/gocdk/testdata/help.ct
> internal/gocdk: fill in Help text for the build and deploy commands

- internal/cmd/gocdk/init.go
- internal/cmd/gocdk/resource.go
- internal/cmd/gocdk/serve.go
- internal/cmd/gocdk/testdata/help.ct
- internal/cmd/gocdk/testdata/init-help.ct
- internal/cmd/gocdk/testdata/resource-help.ct
- internal/cmd/gocdk/testdata/serve-help.ct
> internal/gocdk: fill in Help text for the init, resource, and serve commands

- internal/cmd/gocdk/biome.go
- internal/cmd/gocdk/biome_test.go
- internal/cmd/gocdk/testdata/biome-help.ct
Fixes #2453 
Added biome destroy command + unit test
> internal/gocdk: Added biome destroy command + unit test

- samples/guestbook/README.md
I think it is quite self explanatory :)
> samples/guestbook: fix links for external documentation

- docstore/memdocstore/codec.go
- docstore/memdocstore/codec_test.go
- docstore/memdocstore/mem.go
- docstore/memdocstore/mem_test.go
- docstore/memdocstore/query.go
Adding a type for documents that are stored in the collection helps
make the code clearer.
> memdocstore: introduce the storedDoc type

- docstore/awsdynamodb/query.go
- docstore/driver/compare.go
- docstore/driver/compare_test.go
- docstore/gcpfirestore/query.go
- docstore/gcpfirestore/query_test.go
- docstore/memdocstore/query.go
Factor out common code from dynamo, firestore and mem drivers.
> docstore: move time and number comparison to driver

- docstore/mongodocstore/cosmos_test.go
- docstore/mongodocstore/localmongo.sh
- docstore/mongodocstore/mongo_test.go
> docstore/mongodocstore: tests against both MongoDB v3 and v4

- internal/website/content/howto/docstore/_index.md
- internal/website/content/samples/gocdk-docstore/_index.md
- internal/website/content/tutorials/order.md
> website: undraftify docstore content and order tutorial

- docstore/memdocstore/example_test.go
- internal/website/content/howto/docstore/_index.md
- internal/website/data/examples.json
> docstore/memdocstore: Updates examples to match reality.

- .travis.yml
- docstore/mongodocstore/go.mod
- go.mod
- go.sum
- internal/contributebot/go.mod
- internal/testing/runchecks.sh
- pubsub/kafkapubsub/go.mod
- pubsub/natspubsub/go.mod
- pubsub/rabbitpubsub/go.mod
- runtimevar/etcdvar/go.mod
- samples/go.mod
- secrets/hashivault/go.mod
> internal: add go 1.13 build

- docstore/memdocstore/mem.go
- docstore/memdocstore/mem_test.go
> docstore/memdocstore: improve encoding/decoding errors

- runtimevar/runtimevar.go
Selecting on both <-haveGood and <-ctx.Done() is non deterministic so on
ctx.Done() selection (say ctx is already done to prevent blocking) an empty
snapshot will be returned by Latest even though a good snapshot might be available.
> runtimevar: Latest must check for good snapshot before selecting on passed in ctx.

- pubsub/pubsub.go
- pubsub/pubsub_test.go
> pubsub: Fix race when retrying across multiple batches

- docstore/mongodocstore/go.mod
- internal/contributebot/go.mod
- pubsub/kafkapubsub/go.mod
- pubsub/natspubsub/go.mod
- pubsub/rabbitpubsub/go.mod
- runtimevar/etcdvar/go.mod
- samples/go.mod
- secrets/hashivault/go.mod
Prep for release `v0.18.0`.
Travis is expected to fail for this PR.
> all: prep for release v0.18.0

- blob/gcsblob/gcsblob.go
Remove line for duplicated function comment.
> blob/gcsblob: Remove line for duplicated function comment

- blob/azureblob/testdata/TestConformance/TestAttributes.replay
- blob/drivertest/drivertest.go
- blob/fileblob/fileblob.go
- blob/gcsblob/testdata/TestConformance/TestAttributes.replay
- blob/s3blob/testdata/TestConformance/TestAttributes.replay
- blob/s3blob/testdata/TestConformanceUsingLegacyList/TestAttributes.replay
Also, add a conformance test for that.
Fixes #2714.
> blob/fileblob: Return NotFound when key addresses a directory

- blob/gcsblob/gcsblob.go
> blob/gcsblob: use STORAGE_EMULATOR_HOST if present

- blob/blob.go
- blob/blob_writer_test.go
> blob: Add ReadFrom to blob.Writer and WriteTo to blob.Reader

- blob/gcsblob/gcsblob.go
- blob/gcsblob/gcsblob_test.go
- blob/gcsblob/testdata/TestBeforeReadNonExistentKey.replay
> blob/gcsblob: Make sure to return false from BeforeRead if the read is going to fail

- blob/gcsblob/gcsblob.go
Fixes https://github.com/google/go-cloud/issues/2732
> blob/gcsblob: fix obj attributes when listing bucket contents

- docstore/mongodocstore/go.mod
- internal/contributebot/go.mod
- pubsub/kafkapubsub/go.mod
- pubsub/natspubsub/go.mod
- pubsub/rabbitpubsub/go.mod
- runtimevar/etcdvar/go.mod
- samples/go.mod
- secrets/hashivault/go.mod
> all: post release, add back replace directives

- blob/blob.go
In my read-heavy workloads the stats allocations completely dominated all of the allocations in my application. This amortizes the cost of those allocations so they only have to be paid once for write/read stream instead of once per write/read call.
> Blob/blob: Reduce allocations in bucket.Read() and bucket.Write()

- mysql/gcpmysql/gcpmysql.go
- mysql/gcpmysql/gcpmysql_test.go
This PR addresses Issue #2745 
When opening a `mysql` database instance, options may be needed.  For example, if you have a date/time column, the `parseTime` option will need to be set `true`.  In the `gcpmysql` package, the DSN options are not being handled when opening the instance connection.
The differences of the URLs needed for the gcp database instance prevents the usage of the drivers (github.com/go-sql-driver/mysql) parsing of the DSN options.  
GCP:
```
user:password@example-project/region/my-instance01/testdb
```
Vs
```
username:password@tcp(127.0.0.1:3306)/test
```
The code in the `OpenMySQLURL` only parses the connect parameters and none of the options that may be included when calling the driver's `OpenDB` method.
The approach taken was to minimize the code changes to add in …
> mysql/gcpmysql: Parse Options in DSN

- server/driver/driver.go
- server/server.go
- server/server_test.go
> server/all: add support for ListenAndServeTLS

- docstore/mongodocstore/go.mod
- docstore/mongodocstore/go.sum
- go.mod
- go.sum
- internal/contributebot/go.sum
- pubsub/kafkapubsub/go.sum
- pubsub/natspubsub/go.mod
- pubsub/natspubsub/go.sum
- pubsub/rabbitpubsub/go.mod
- pubsub/rabbitpubsub/go.sum
- runtimevar/etcdvar/go.sum
- samples/go.mod
- samples/go.sum
- secrets/hashivault/go.sum
> blob/s3blob: update aws-sdk-go to support IRSA

- blob/blob.go
> blob: Reduce allocations in write/read by only emitting metrics on close

- internal/website/data/examples.json
- pubsub/natspubsub/example_test.go
- pubsub/natspubsub/nats.go
- pubsub/natspubsub/nats_test.go
Implementation of Nats queue subscription through OpenSubscription function on natspubsub package.
Unit tests and example code were also added
> pubsub/natspubsub: implement nats queue subscription

- blob/fileblob/fileblob.go
- blob/fileblob/fileblob_test.go
> blob/fileblob/: Handle List() when the bucket is rooted at /

- blob/azureblob/azureblob.go
- blob/azureblob/azureblob_test.go
#2817 was incomplete.
I'm sorry for not doing enough testing.
The URL structure of the local emulator is a bit different from the real one.
> blob/azureblob: fix broken url for local emulator

- blob/fileblob/fileblob.go
Not much to say, just fix outdated comment modified by #2821
> blob/fileblob: fix outdated comment

- mysql/awsmysql/awsmysql.go
- mysql/awsmysql/awsmysql_test.go
Same as #2785 but using similar approach as `gcpmysql.go`
> mysql/awsmysql: Parse DSN options from URL

- runtimevar/httpvar/httpvar.go
> runtimevar/httpvar: use context when watching values

- .travis.yml
> internal: don't install Terraform, we no longer use it for tests

- blob/s3blob/s3blob.go
- blob/s3blob/s3blob_test.go
> blob/s3blob: Add access to s3manager.Uploader via As in WriterOptions.

- pubsub/pubsub.go
- pubsub/pubsub_test.go
I verified the behavior with a new test, and by running the benchmarks. They all look basically the same except the existing benchmark where no messages arrive in the middle third of the test; the new code decays the batch size as expected (http://screen/BnYwFsRJ432Ru7h).
I had to change the test to be in the `pubsub` package in order to access the private `preReceiveBatchHook`.
#2853
> pubsub: allow batch size to decay when there aren't any messages available

- pubsub/awssnssqs/awssnssqs.go
- pubsub/awssnssqs/awssnssqs_test.go
> pubsub/awspubsub: Expose WaitTime parameter to AWS ReceiveMessage as a SubscriberOption

- blob/azureblob/azureblob.go
- blob/blob.go
- blob/fileblob/fileblob.go
- blob/fileblob/fileblob_test.go
- blob/gcsblob/gcsblob.go
> blob: Return Unimplemented errors from SignedURL when the driver supports it but hasn't been configured correctly

- blob/fileblob/fileblob.go
- blob/fileblob/fileblob_test.go
> blob/fileblob: Add an Option to create the base fileblob directory it doesn't already exist

- blob/fileblob/fileblob.go
- blob/fileblob/fileblob_test.go
> blob/fileblob: Add support for various As functions for fileblob

- blob/azureblob/azureblob.go
- blob/blob.go
- blob/driver/driver.go
- blob/drivertest/drivertest.go
- blob/fileblob/fileblob.go
- blob/gcsblob/gcsblob.go
- blob/memblob/memblob.go
- blob/s3blob/s3blob.go
> blob: Add CreateTime and ETag to blob.Attributes

- blob/blob.go
- blob/blob_test.go
- blob/example_test.go
- blob/oc_test.go
> blob: Add a ListPage function for listing blobs in pages

- blob/azureblob/azureblob.go
- go.mod
> blob/azblob: feat added in MSI based authentication for Azure buckets

- runtimevar/awssecretsmanager/awssecretsmanager_test.go
- runtimevar/awssecretsmanager/testdata/TestConformance/TestAs/verify_As.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestDelete.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestInvalidJSON.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestJSON.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestNonExistentVariable.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestString.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestUpdate.replay
- runtimevar/awssecretsmanager/testdata/TestConformance/TestUpdateWithErrors.replay
Updates #2907.
@THE108 please review as well.
> runtimevar/awssecretsmanager: make drivertests repeatable and add .replay files

- docstore/awsdynamodb/urls.go
- docstore/awsdynamodb/urls_test.go
> docstore/awsdynamodb: add consistent read option for URL opener

- AUTHORS
- CONTRIBUTORS
- internal/website/content/howto/runtimevar/_index.md
- internal/website/data/examples.json
- runtimevar/awssecretsmanager/example_test.go
Add documentation for AWS Secrets Manager in runtimevar section.
> runtimevar/awssecretsmanager: add documentation

- internal/website/content/howto/sql/_index.md
> howto/sql: fix mistake import

- blob/azureblob/azureblob.go
- blob/azureblob/azureblob_test.go
> blob/azureblog: Add support for CDN domains

- blob/fileblob/fileblob.go
Partial writes that need to be repeated result in wrong hashsums because the unwritten tail gets hashed repeatedly (twice actually).
> blob/fileblob: fix Write hashing more than what's been written

- docstore/mongodocstore/go.sum
- go.mod
- go.sum
- pubsub/kafkapubsub/go.sum
- pubsub/natspubsub/go.sum
- pubsub/rabbitpubsub/go.sum
- samples/go.mod
- samples/go.sum
- secrets/hashivault/go.sum
> all: upgrade AWS dependency

- secrets/hashivault/vault.go
- secrets/hashivault/vault_test.go
Fixes: #2990
`VAULT_ADDR` and `VAULT_TOKEN` are the recommended way of configuring
access to vault as per the Vault docs https://www.vaultproject.io/docs/commands#environment-variables
This commit adds support for those environment variables. We check
that the *existing* VAULT_SERVER_URL and VAULT_SERVER_TOKEN env vars
are not set first. If they are, then we use those. If they are not
then we fall back to the new environment variables
See …
> secrets/hashivault: Add support for VAULT_ADDR and VAULT_TOKEN

- docstore/mongodocstore/go.mod
- pubsub/kafkapubsub/go.mod
- pubsub/natspubsub/go.mod
- pubsub/rabbitpubsub/go.mod
- samples/go.mod
- secrets/hashivault/go.mod
> all: prep for release v0.23.0

- docstore/gcpfirestore/fs.go
- docstore/gcpfirestore/urls.go
> docstore/gcpfirestore: add support for Firestore emulator

- pubsub/mempubsub/mem.go
- pubsub/mempubsub/mem_test.go
> pubsub/mempubsub: log if message sent to subscriber-less topic

- .travis.yml
Website is not getting updated, not sure why. Tried recreating the secret.
> website: update deploy secret name

- docstore/mongodocstore/go.sum
- go.mod
- go.sum
- internal/testing/alldeps
- internal/website/content/howto/runtimevar/_index.md
- internal/website/content/howto/secrets/_index.md
- internal/website/data/examples.json
- pubsub/kafkapubsub/go.sum
- pubsub/natspubsub/go.sum
- pubsub/rabbitpubsub/go.sum
- runtimevar/awsparamstore/awsparamstore.go
- runtimevar/awsparamstore/awsparamstore_test.go
- runtimevar/awsparamstore/example_test.go
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestAs/verify_As.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestAs/verify_As_returns_false_when_passed_nil.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestDelete.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestInvalidJSON.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestJSON.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestNonExistentVariable.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestString.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestUpdate.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestUpdateWithErrors.replay
- samples/go.sum
- secrets/hashivault/go.sum
> runtimevar/awsparamstore: add support for using AWS SDK V2

- docstore/mongodocstore/go.sum
- go.mod
- go.sum
- internal/testing/alldeps
- internal/website/content/howto/runtimevar/_index.md
- internal/website/data/examples.json
- pubsub/kafkapubsub/go.sum
- pubsub/natspubsub/go.sum
- pubsub/rabbitpubsub/go.sum
- runtimevar/awsparamstore/awsparamstore.go
- runtimevar/awsparamstore/awsparamstore_test.go
- runtimevar/awsparamstore/example_test.go
- runtimevar/awssecretsmanager/awssecretsmanager.go
- runtimevar/awssecretsmanager/awssecretsmanager_test.go
- runtimevar/awssecretsmanager/example_test.go
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestAs/verify_As.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestAs/verify_As_returns_false_when_passed_nil.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestDelete.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestInvalidJSON.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestJSON.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestNonExistentVariable.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestString.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestUpdate.replay
- runtimevar/awssecretsmanager/testdata/TestConformanceV2/TestUpdateWithErrors.replay
- samples/go.sum
- secrets/hashivault/go.sum
> runtimevar/awssecretsmanager: add support for using AWS SDK V2

- .github/workflows/tests.yml
- secrets/hashivault/vault.go
- secrets/hashivault/vault_test.go
> secrets/hashivault: add support for setting the secrets engine

- pubsub/gcppubsub/gcppubsub.go
> pubsub/gcppubsub: retry on DeadlineExceeded for subscriptions

- runtimevar/awsparamstore/awsparamstore.go
- runtimevar/awsparamstore/awsparamstore_test.go
- runtimevar/awssecretsmanager/awssecretsmanager.go
- runtimevar/awssecretsmanager/awssecretsmanager_test.go
- runtimevar/blobvar/blobvar.go
- runtimevar/blobvar/blobvar_test.go
- runtimevar/filevar/filevar.go
- runtimevar/filevar/filevar_test.go
- runtimevar/gcpruntimeconfig/gcpruntimeconfig.go
- runtimevar/gcpruntimeconfig/gcpruntimeconfig_test.go
- runtimevar/gcpsecretmanager/gcpsecretmanager.go
- runtimevar/gcpsecretmanager/gcpsecretmanager_test.go
- runtimevar/httpvar/httpvar.go
- runtimevar/httpvar/httpvar_test.go
> runtimevar: Add support for setting wait/timeout Option in URL params

- blob/blob.go
- blob/driver/driver.go
- blob/example_openbucket_test.go
- blob/example_test.go
- blob/wrapped_bucket_test.go
- internal/website/content/howto/blob/_index.md
- internal/website/data/examples.json
> blob: Add support for SingleKeyBucket via "key" URL parameter

- runtimevar/httpvar/httpvar.go
- runtimevar/httpvar/httpvar_test.go
> runtimevar/httpvar: Support using basic authentication on the HTTP requests

- docstore/mongodocstore/go.sum
- go.mod
- go.sum
- pubsub/kafkapubsub/go.sum
- pubsub/natspubsub/go.sum
- pubsub/rabbitpubsub/go.sum
- samples/go.sum
- secrets/hashivault/go.sum
> all: downgrade go-ieproxy, the new version has issues on darwin

- blob/azureblob/azureblob.go
> blob/azureblob: Fix a list-capture bug in As for List

- blob/azureblob/azureblob.go
- blob/blob.go
- blob/driver/driver.go
- blob/s3blob/s3blob.go
> blob: Add support for WriterOption.MaxConcurrency.

- pubsub/gcppubsub/gcppubsub.go
- pubsub/gcppubsub/gcppubsub_test.go
> pubsub/gcppubsub: Expose ReceivedMessage in As (for AckId)

- runtimevar/awsparamstore/awsparamstore.go
- runtimevar/awsparamstore/awsparamstore_test.go
- runtimevar/awsparamstore/testdata/TestConformance/TestAs/verify_As.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestDelete.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestInvalidJSON.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestJSON.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestNonExistentVariable.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestString.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestUpdate.replay
- runtimevar/awsparamstore/testdata/TestConformance/TestUpdateWithErrors.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestAs/verify_As.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestAs/verify_As_returns_false_when_passed_nil.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestDelete.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestInvalidJSON.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestJSON.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestNonExistentVariable.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestString.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestUpdate.replay
- runtimevar/awsparamstore/testdata/TestConformanceV2/TestUpdateWithErrors.replay
> runtimevar/awsparamstore: drop the DescribeParameters call, it isn't necessary

- blob/drivertest/drivertest.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
See
> blob: fix minor unreachable code in test caused by t.Fatalf

- secrets/awskms/kms.go
- secrets/awskms/kms_test.go
> secrets/awskms: Add support for EncryptionContext parameters

- gcp/cloudsql/cloudsql.go
> Revert "postgres: Support IAM auth for GCP."

- pubsub/awssnssqs/awssnssqs.go
- pubsub/awssnssqs/awssnssqs_test.go
> pubsub/awssnssqs: Make sure to handle nil TopicOptions and SubscriptionOptions in Open

- pubsub/azuresb/azuresb.go
An attempt at addressing https://github.com/google/go-cloud/issues/3183 (Fixes https://github.com/google/go-cloud/issues/3183)
Signed-off-by: Yoriyasu Yano <430092+yorinasub17@users.noreply.github.com>
> pubsub/azuresb: Make the listener timeout configurable

- pubsub/azuresb/azuresb.go
- pubsub/azuresb/azuresb_test.go
> pubsub/azuresb: Add ability to override ListenerTimeout via URLOpener

- pubsub/awssnssqs/awssnssqs.go
- pubsub/awssnssqs/awssnssqs_test.go
> pubsub/awssnssqs: Support lazy mode for Nacks

- pubsub/gcppubsub/gcppubsub.go
- pubsub/gcppubsub/gcppubsub_test.go
> pubsub/gcppubsub: Support lazy mode for Nacks

- secrets/azurekeyvault/akv.go
- secrets/azurekeyvault/testdata/TestConformance/TestAs/verify_As_function.replay
- secrets/azurekeyvault/testdata/TestConformance/TestAs/verify_As_returns_false_when_passed_nil.replay
- secrets/azurekeyvault/testdata/TestConformance/TestDecryptMalformedError.replay
- secrets/azurekeyvault/testdata/TestConformance/TestEncryptDecrypt.replay
- secrets/azurekeyvault/testdata/TestConformance/TestMultipleEncryptionsNotEqual.replay
- secrets/azurekeyvault/testdata/TestConformance/TestMultipleKeys.replay
> secrets/azurekeyvault: Use azidentity.NewDefaultAzureCredential to support other auth types

- pubsub/awssnssqs/awssnssqs.go
- pubsub/awssnssqs/awssnssqs_test.go
> pubsub/awssqs Fix BeforeSend to Enable changes to the sqs input message

- pubsub/mempubsub/mem.go
- pubsub/mempubsub/mem_test.go
> pubsub/memsub: Add Options for batching

- blob/s3blob/s3blob.go
> remove duplicate comment in S3blob.go

- aws/aws.go
Support custom endpoints for aws sdk v2 similar to aws sdk v1
#3215
> support custom endpoint for aws sdk v2

- secrets/gcpkms/kms.go
> secrets/gcpkms: update proto import

- blob/gcsblob/iam.go
- blob/gcsblob/iam_test.go
Similar to the fix in #3227
I chose to split the remaining fixes up into 4 smaller PRs, the others being: #3229 #3230 #3231
> blob/gcsblob: update proto import

- runtimevar/gcpsecretmanager/gcpsecretmanager.go
- runtimevar/gcpsecretmanager/gcpsecretmanager_test.go
Similar to the fix in #3227
I chose to split the remaining fixes up into 4 smaller PRs, the others being: #3228 #3229 #3230
> runtimevar/gcpsecretmanager: update proto import

- pubsub/example_test.go
- pubsub/gcppubsub/gcppubsub.go
- pubsub/gcppubsub/gcppubsub_test.go
Similar to the fix in #3227
I chose to split the remaining fixes up into 4 smaller PRs, the others being: #3228 #3229 #3231
> pubsub/gcppubsub: update proto import

- docstore/gcpfirestore/codec.go
- docstore/gcpfirestore/fs.go
- docstore/gcpfirestore/fs_test.go
- docstore/gcpfirestore/native_codec_test.go
- docstore/gcpfirestore/query.go
- docstore/gcpfirestore/query_test.go
Similar to the fix in #3227
I chose to split the remaining fixes up into 4 smaller PRs, the others being: #3228 #3230 #3231
> docstore/gcpfirestore: update proto import

- docstore/awsdynamodb/benchmark_test.go
- docstore/drivertest/drivertest.go
"github.com/aws/aws-sdk-go/service/dynamodb" is being imported more than once (ST1019)
package "gocloud.dev/docstore" is being imported more than once (ST1019)
> chore: import more than once

- .github/workflows/tests.yml
> all: add dragonfly build

- blob/fileblob/fileblob.go
> blob/fileblob: Create temp files in os.TempDir

- blob/blob.go
- blob/blob_writer_test.go
> blob: Avoid infinite recursion when using io.Copy between Reader and Writer

- blob/fileblob/fileblob.go
> blob/fileblob: Fix for URL parameter for no_tmp_dir option

- docstore/mongodocstore/go.mod
- internal/useragent/useragent.go
- pubsub/kafkapubsub/go.mod
- pubsub/natspubsub/go.mod
- pubsub/rabbitpubsub/go.mod
- runtimevar/etcdvar/go.mod
- samples/go.mod
- secrets/hashivault/go.mod
> all: prerelease

- blob/s3blob/s3blob.go
> blob/s3blob: fix typo in documentation

- blob/gcsblob/gcsblob.go
> blob/gcsblob: Allow providing options for storage.NewClient

- blob/s3blob/s3blob.go
- pubsub/awssnssqs/awssnssqs.go
- runtimevar/awsparamstore/awsparamstore.go
- runtimevar/awssecretsmanager/awssecretsmanager.go
- secrets/awskms/kms.go
Fixes https://github.com/google/go-cloud/issues/3526.
> all: update links for AWS URL docs

- pubsub/batcher/batcher.go
- pubsub/batcher/batcher_test.go
Based on original PR by @tonyhb (https://github.com/google/go-cloud/pull/3386).
> pubsub: Ensure batch flushes on shutdown even if MinBatchSize isn't met

- go.mod
- go.sum
- internal/otel/init.go
- internal/otel/metrics.go
- internal/otel/trace.go
- internal/otel/trace_test.go
- internal/testing/alldeps
- internal/testing/oteltest/diff.go
- internal/testing/oteltest/exporter.go
- mysql/awsmysql/awsmysql.go
- mysql/azuremysql/azuremysql.go
- mysql/gcpmysql/gcpmysql.go
- mysql/mysql.go
- samples/go.mod
- samples/go.sum
Micro PR to migrate monolith : https://github.com/google/go-cloud/pull/3539
PR affects : 
- mysql
> mysql: migrate mysql opentelemetry

- go.mod
- go.sum
- internal/otel/init.go
- internal/otel/metrics.go
- internal/otel/trace.go
- internal/otel/trace_test.go
- internal/testing/alldeps
- internal/testing/oteltest/diff.go
- internal/testing/oteltest/exporter.go
- mysql/awsmysql/awsmysql.go
- mysql/azuremysql/azuremysql.go
- mysql/gcpmysql/gcpmysql.go
- mysql/mysql.go
- samples/go.mod
- samples/go.sum
> Revert "mysql: migrate mysql opentelemetry"

- docstore/memdocstore/mem.go
- docstore/memdocstore/mem_test.go
more details: https://github.com/google/go-cloud/issues/3501
See
> docstore/memdocstore: add support for atomic writes
